"""
Pure-math computation on the object's determined matter space
  H = (doubled chiral spinor, m06) (x) (internal A4 module, m05).

Two DETERMINED operators, each at its object-fixed normalization:
  S = Cartan of the chiral su(2) carried by the srs/srs-z doubling   (m06 factor)
  Q = winding of the order-3 element sigma (the C3 generator)         (m05 factor)

We verify each normalization is forced, then take ONE common trace over the whole H.
No free rescaling of any operator; no factorized per-leg metric; no target value.
"""
import numpy as np
import sys, os
from fractions import Fraction

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "dirac_srs_mdl"))
import srs

np.set_printoptions(precision=4, suppress=True, linewidth=120)
I2 = np.eye(2)
s1 = np.array([[0, 1], [1, 0]], complex)
s2 = np.array([[0, -1j], [1j, 0]], complex)
s3 = np.array([[1, 0], [0, -1]], complex)


def comm(A, B): return A @ B - B @ A


print("=" * 90)
print(" THE SPINOR FACTOR (m06): the chiral su(2) of the srs (+) srs-z doubling")
print("=" * 90)

# ---------------------------------------------------------------------------
# The m06 spinor module is C^4 = C^2_+ (+) C^2_- , the two chiral halves.
# The doubling srs (+) srs-z is the TWO-DIMENSIONAL "copy" space (the enantiomer
# label). The chiral su(2) acts on that copy/enantiomer 2-space. In m06's COPY
# basis the C^4 splits as (copy 2-space) (x) (Weyl 2-space):
#       D = [[ +sigma.p , m I ], [ m I , -sigma.p ]]  on copy (x) Weyl.
# The "copy" su(2) (srs<->srs-z mixing) is generated by tau^a (x) I_Weyl, tau the
# Pauli matrices on the 2-dim copy space.  Its Cartan is
#       S = (1/2) tau^3 (x) I_2 .
# ---------------------------------------------------------------------------
def kron(*ms):
    out = ms[0]
    for m in ms[1:]:
        out = np.kron(out, m)
    return out

# copy-space su(2) generators T^a = (1/2) tau^a, acting on the 2-dim enantiomer label.
T = [0.5 * s1, 0.5 * s2, 0.5 * s3]

print("""
[A] The doubling is a 2-dim space (srs, srs-z). Mixing the two enantiomers is an
    su(2) action on that 2-space; its Cartan is S0 = (1/2) tau^3 (one copy-space factor).
    NORMALIZATION IS FORCED by the su(2) bracket: [T^a, T^b] = i eps^abc T^c.""")
lev = {(0, 1): 2, (1, 2): 0, (2, 0): 1}
ok_su2 = True
for (a, b), c in lev.items():
    lhs = comm(T[a], T[b])
    rhs = 1j * T[c]
    ok_su2 = ok_su2 and np.allclose(lhs, rhs)
print(f"    [T^a,T^b] = i eps^abc T^c  (a non-abelian closure) ?  {ok_su2}")
print(f"    spec(S0) = {sorted(np.linalg.eigvalsh(T[2]).round(6).tolist())}  = (+1/2, -1/2)")
print("""    A non-abelian generator CANNOT be freely rescaled: S0 -> lambda S0 would give
    [lambda S0, lambda S^1] = lambda^2 i S^2 != i (lambda S^2) unless lambda = 1.
    The structure constants pin lambda = 1.  ==> S0 is at its FORCED scale (eigvals +-1/2).""")

print("=" * 90)
print(" THE INTERNAL FACTOR (m05): the order-3 element sigma = C3 generator, its winding Q")
print("=" * 90)

# ---------------------------------------------------------------------------
# m05: the 12-dart space carries the A4 regular rep.  sigma = (1 2 3) is the
# order-3 C3 generator; on the darts it is the permutation P built in explore_03/06.
# Q = "winding of sigma" = the integer that labels which eigenspace of P you sit in.
# P^3 = I  ==>  eigenvalues of P are cube roots of unity exp(2 pi i w / 3), w in {-1,0,+1}.
# Q is the GENERATOR of that Z_3 winding: P = exp(2 pi i Q / 3), spec(Q) = {-1,0,+1}.
# ---------------------------------------------------------------------------
sigma = {0: 0, 1: 2, 2: 3, 3: 1}     # the 3-cycle (1 2 3), as in explore_03/06
DARTS = srs._darts()
n = len(DARTS)
P = np.zeros((n, n))
for a, (i, j, v) in enumerate(DARTS):
    g = (sigma[i], sigma[j])
    for b, (p, q, ww) in enumerate(DARTS):
        if (p, q) == g:
            P[b, a] = 1
            break

print(f"""
[B] sigma acts on the 12-dart A4-regular module as the permutation P.
    order-3 ? P^3 = I :  {np.allclose(np.linalg.matrix_power(P, 3), np.eye(n))}
    P is a finite-order-3 rotation, so P = exp(2 pi i Q / 3) with Q the WINDING operator.""")

# Build Q from the eigenstructure of P: eigenvalue exp(2 pi i w/3) <-> Q-eigenvalue w in {-1,0,1}.
evals, V = np.linalg.eig(P)
angles = np.angle(evals)                      # in (-pi, pi]
windings = np.round(angles / (2 * np.pi / 3)).astype(int)   # nearest of {-1,0,1}
# reconstruct Q in the dart basis: Q = V diag(windings) V^{-1}, then Hermitize numerically
Qdiag = np.diag(windings.astype(complex))
Q = V @ Qdiag @ np.linalg.inv(V)
Q = 0.5 * (Q + Q.conj().T)                    # P is a real orthogonal (unitary) perm; Q Hermitian
Qspec = sorted(set(np.round(np.linalg.eigvalsh(Q)).astype(int).tolist()))
print(f"    spec(Q) = {Qspec}  (the winding numbers of a 1/3-turn).  INTEGER spectrum.")
# check P = exp(2 pi i Q/3)
from scipy.linalg import expm
recon = expm(2j * np.pi * Q / 3)
print(f"    exp(2 pi i Q / 3) = P ?  {np.allclose(recon, P, atol=1e-9)}")
print("""    Q counts thirds-of-a-turn: it cannot be rescaled.  Q -> lambda Q would make
    exp(2 pi i (lambda Q)/3) != P unless lambda = 1 (P^3=I fixes the unit of winding).
    The eigenvalues are forced INTEGERS {-1,0,+1}; no free scale.  ==> Q FORCED.""")

# multiplicity of each winding on the 12 darts
mult = {w: int(np.sum(windings == w)) for w in (-1, 0, 1)}
print(f"    winding multiplicities on the 12 darts (sum=12): {mult}")

print("=" * 90)
print(" THE WHOLE MATTER SPACE H AND THE ONE COMMON TRACE")
print("=" * 90)

# ---------------------------------------------------------------------------
# H = (m06 spinor: C^4 = copy-2 (x) Weyl-2)  (x)  (m05 internal: C^12 darts)
# S lives on the m06 factor only:   S = S0 (x) I_Weyl (x) I_dart  acting on H.
#   In m06, S0 acts on the 2-dim COPY space; I on the Weyl 2-space.
# Q lives on the m05 factor only:   Q_H = I_copy (x) I_Weyl (x) Q_dart.
# ONE trace over all of H (dimension 2*2*12 = 48). No per-leg metric, no rescaling.
# ---------------------------------------------------------------------------
dim_copy, dim_weyl, dim_dart = 2, 2, n
S_H = kron(T[2], I2, np.eye(dim_dart))                 # (1/2 tau^3) (x) I_W (x) I_dart
Q_H = kron(I2, I2, Q.astype(complex))                  # I_copy (x) I_W (x) Q_dart

dimH = S_H.shape[0]
print(f"  dim H = {dim_copy} (copy) x {dim_weyl} (Weyl) x {dim_dart} (dart) = {dimH}")

trS2 = np.trace(S_H @ S_H).real
trQ2 = np.trace(Q_H @ Q_H).real
print(f"\n  Tr(S^2) = {trS2}   (exact: (1/4)*dim of the rest = (1/4)*{dim_weyl*dim_dart}*... )")
print(f"  Tr(Q^2) = {trQ2}")

# exact forms
# Tr(S^2): S0^2 = (1/4) I on copy 2-space -> trace over copy = 2*(1/4)=1/2; times I over weyl*dart.
trS2_exact = Fraction(1, 4) * dim_copy * dim_weyl * dim_dart
# Tr(Q^2): sum over darts of w^2, times dim_copy*dim_weyl identity.
sum_w2 = sum(w * w * mult[w] for w in (-1, 0, 1))
trQ2_exact = sum_w2 * dim_copy * dim_weyl
print(f"\n  EXACT Tr(S^2) = (1/4)*{dim_copy}*{dim_weyl}*{dim_dart} = {trS2_exact}")
print(f"  EXACT Tr(Q^2) = (sum_dart w^2)*{dim_copy}*{dim_weyl} = {sum_w2}*{dim_copy*dim_weyl} = {trQ2_exact}")

ratio = Fraction(trS2_exact) / Fraction(trQ2_exact)
print(f"\n  RATIO  Tr(S^2) / Tr(Q^2) = {trS2_exact} / {trQ2_exact} = {ratio}")

mixS = Fraction(trS2_exact) / (Fraction(trS2_exact) + Fraction(trQ2_exact))
mixQ = Fraction(trQ2_exact) / (Fraction(trS2_exact) + Fraction(trQ2_exact))
print(f"\n  MIXING INVARIANTS (single whole-space normalization):")
print(f"    Tr(S^2)/(Tr(S^2)+Tr(Q^2)) = {mixS}  = {float(mixS):.6f}")
print(f"    Tr(Q^2)/(Tr(S^2)+Tr(Q^2)) = {mixQ}  = {float(mixQ):.6f}")
print(f"    (check sum = {mixS+mixQ})")
