"""
DOES THE SCREW'S LOCKED PITCH FIX THE SPIN<->CHARGE RELATIVE NORMALIZATION?

Pure math, in the object's native terms. Reads only the bare object (dirac_srs_mdl)
and the two matter-bridge rep-content facts (m05, m06). No physics, no targets, no adopted
constants. Honest forced/free verdict.

THE OBJECT'S SCREW (verified):
  g : (s, c) -> (sigma[s], Msig c + t)         t = (1,0,0)
  realized cartesianly as the affine SCREW   P -> R P + L t,
    R   = rotation by 2pi/3 about the <111> axis            (the ROTATION part)
    L t = axial advance with  axis . (L t) = 1/sqrt(6)      (the TRANSLATION part)
  ONE group element. g^3 = pure lattice translation by one <111> period sqrt(3/2). PITCH LOCK.

MATTER (m05/m06):
  - SPIN/handedness Sz  = Cartan of the chiral SU(2) of srs(+)srs-z doubling (spinor factor)
  - INTERNAL charge Q   = C3 winding weight on the A4 3-irrep / Lambda(C^3) (internal factor)
"""
import numpy as np
import sys, os

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "dirac_srs_mdl"))
import srs

np.set_printoptions(precision=5, suppress=True, linewidth=120)
w = np.exp(2j * np.pi / 3)

# =====================================================================================
print("=" * 90)
print(" STEP 0 -- VERIFY THE SCREW AND ITS PITCH (object's native geometry)")
print("=" * 90)

DARTS = srs._darts()
sigma = {0: 0, 1: 2, 2: 3, 3: 1}
Msig = np.array([[0, -1, 0], [0, 0, -1], [1, 0, 0]])

A = np.zeros((15, 12)); b = np.zeros(15)
idx = lambda i, c: 3 * i + c
row = 0
outgoing = lambda i: [(h, v) for (t, h, v) in DARTS if t == i]
for i in range(4):
    for c in range(3):
        for (h, v) in outgoing(i):
            A[row, idx(h, c)] += 1.0; A[row, idx(i, c)] -= 1.0; b[row] -= v[c]
        row += 1
for c in range(3):
    for i in range(4): A[row, idx(i, c)] = 1.0
    row += 1
Y = np.linalg.lstsq(A, b, rcond=None)[0].reshape(4, 3)
fr = np.array([Y[h] + np.array(v, float) - Y[t] for (t, h, v) in DARTS])
Corr = sum(np.outer(f, f) for f in fr)
ev, U = np.linalg.eigh(Corr)
L = U @ np.diag(1 / np.sqrt(ev)) @ U.T
Linv = np.linalg.inv(L)
R = L @ Msig @ Linv
ww, VV = np.linalg.eig(R)
axis = VV[:, np.argmin(np.abs(ww - 1))].real; axis /= np.linalg.norm(axis)
pitch = abs(axis @ (L @ np.array([1.0, 0, 0])))
theta = 2 * np.pi / 3

print(f"  rotation angle theta              = 2pi/3  = {theta:.6f} rad  (120 deg)")
print(f"  axial advance a = axis.(L t)      = {pitch:.6f}  == 1/sqrt(6) {np.isclose(pitch,1/np.sqrt(6))}")
print(f"  3 steps = one <111> period        = {3*pitch:.6f}  == sqrt(3/2) {np.isclose(3*pitch,np.sqrt(1.5))}")
print("  => ONE screw g: rotation theta LOCKED to axial advance a; g^3 = translation sqrt(3/2).")

# =====================================================================================
print("\n" + "=" * 90)
print(" STEP 1 -- WHAT EACH PART OF g COUPLES TO ON MATTER (determine, don't assume)")
print("=" * 90)
print("""
  The screw g is a single deck/space-group element. On the cover's Hilbert space it acts as ONE
  unitary U(g). Decompose U(g) by WHAT IT MULTIPLIES:

    (i)  ROTATION part: the spatial 2pi/3 rotation R. On the Dirac SPINOR it acts as the SU(2)
         spin rotation  exp(-i theta n.S), n = axis, theta = 2pi/3. THIS is the operator that
         touches the SPIN/handedness generator Sz: a rotation about the axis is generated by the
         axial spin component  S_axis. (Couples to: the SPINOR factor.)

    (ii) TRANSLATION part: the axial advance L t. On the cover it acts as the lattice translation
         = multiplication by the Bloch character  exp(2pi i k.t). Its GENERATOR (d/d(advance)) is
         the axial CRYSTAL MOMENTUM. But on the INTERNAL A4 module, sigma=(123) also winds the
         C3 weight; the translation t and the homology rotation Msig are tied in g (t is added in
         the SAME coordinates Msig acts on). The C3 winding weight Q is the generator of that
         internal phase. (Couples to: the INTERNAL factor via the C3 character.)

  So g's two parts couple to TWO DIFFERENT factors, exactly as stated. We now build both
  generators explicitly and read off how the single g ties them.
""")

# ----- (ii) INTERNAL: the C3 winding weight Q on the A4 3-irrep -------------------------------
# sigma=(123) acts on H_1=Z^3 by Msig; on the 3-irrep it is a C3 generator with eigenvalues
# {1, w, w^2}. The "winding weight" Q is the generator: C3E = exp(2pi i Q /3) i.e. Q = diag(0,1,2)
# in the C3-eigenbasis (the winding number / charge), defined up to overall scale q_unit.
wM, _ = np.linalg.eig(Msig.astype(complex))
print("[1a] INTERNAL C3 winding. sigma_* = Msig on H_1; eigenvalues:")
print("     spec(Msig) =", np.round(np.sort_complex(wM), 4), "= {1, w, w^2} (cube roots of unity):",
      np.allclose(sorted(np.round(wM, 6), key=lambda z: np.angle(z)),
                  sorted([1, w, w**2], key=lambda z: np.angle(z))))
# winding weights = arg/(2pi/3): {0,1,2} (mod 3). Q_internal = diag of weights, scale q_unit FREE.
Qweights = np.array([0, 1, 2])  # the C3 charges of the three internal states (m05: Lambda^1 etc.)
print("     C3 winding charges (the internal Q weights) = {0, 1, 2} (mod 3); overall SCALE q_unit FREE.")

# ----- (i) SPINOR: the chiral SU(2) Cartan Sz from srs(+)srs-z doubling (m06) ------------------
# m06: matter is the doubled chiral 4-spinor; the doubling is an SU(2) ("isospin" of srs vs srs-z).
# Its Cartan Sz has eigenvalues +-1/2 (the two enantiomer/handedness states). The axial SPATIAL
# spin S_axis (generator of rotation about the screw axis) has eigenvalues +-1/2 on the Weyl 2-spinor.
s3 = np.array([[1, 0], [0, -1]], complex)
Sz = 0.5 * s3                      # spin Cartan, eigenvalues +-1/2 (scale s_unit FREE a priori)
print("\n[1b] SPINOR Cartan. The rotation about the screw axis is exp(-i theta S_axis); the chiral")
print("     doubling SU(2) Cartan Sz has eigenvalues +-1/2; spin SCALE s_unit FREE.")
print("     spec(Sz) =", np.linalg.eigvalsh(Sz), " (the half-integer spin weights).")

# =====================================================================================
print("\n" + "=" * 90)
print(" STEP 2 -- TIE Sz AND Q TO THE ONE SCREW; IS THEIR RELATIVE SCALE FORCED?")
print("=" * 90)
print("""
  The single screw g acts on matter as
      U(g) = exp(-i theta * S_axis)  (x)  exp(+i phi * Q),
  where:
    * theta = 2pi/3 is the screw's ROTATION angle (fixed), multiplying the spin generator S_axis;
    * phi is the INTERNAL phase the SAME element imprints via its C3 winding, multiplying Q.

  THE PITCH ENTERS HERE. The screw's axial advance a = 1/sqrt(6) is the translation conjugate to
  the axial crystal momentum. The C3 winding phase phi that g imprints internally is, BY THE
  PITCH LOCK, tied to the rotation: g rotates by theta AND advances by a in ONE motion, and after
  3 steps (g^3) the rotation returns to identity (theta*3 = 2pi) WHILE the advance completes one
  full lattice period (3a = sqrt(3/2)) AND the internal winding completes one full C3 cycle
  (Q-phase returns: phi*3 = 2pi). So on g^3 = pure translation both the spin rotation and the
  internal winding must CLOSE simultaneously. We test what that forces on the relative scale.
""")

# The closure conditions on g^3 = pure translation (a deck element, NOT a point rotation):
#   * spin: the rotation part must become a pure 2pi rotation => exp(-i*3*theta*S_axis) acts as the
#     spinor 2pi holonomy.  For a half-integer spin, exp(-i*2pi*Sz) = -I (the spinor sign).
#   * internal: the C3 winding must complete one full cycle => exp(+i*3*phi*Q) = I on integer Q.
# These two closures are what 'lock' the relative normalization IF g forces phi to theta. Compute.

print("[2a] SPIN closure on g^3 (rotation returns to 2pi):")
spin_2pi = -1.0  # exp(-i 2pi Sz) for spin-1/2
print(f"     3*theta = {3*theta:.5f} = 2pi; exp(-i*2pi*Sz) eigenvalues = "
      f"{np.round(np.diag(np.array([[np.exp(-1j*2*np.pi*0.5),0],[0,np.exp(-1j*2*np.pi*(-0.5))]])),4)}")
print(f"     => spin-1/2 picks up the SPINOR SIGN -1 under the 2pi rotation of g^3. (forced by g)")

print("\n[2b] INTERNAL closure on g^3 (C3 winding completes one cycle):")
for q in Qweights:
    print(f"     Q-weight {q}: exp(+i*3*phi*Q) with 3*phi=2pi -> exp(2pi i q) = {np.round(np.exp(2j*np.pi*q),4)} = 1")
print("     => integer winding charges close to +1 under g^3. (forced by g)")

print("""
[2c] THE KEY QUESTION -- does g FORCE phi in terms of theta (hence Q-scale to Sz-scale)?
   The single element g supplies ONE rotation angle theta=2pi/3. It multiplies S_axis in the
   spinor factor. The internal phase phi multiplies Q in the internal factor. For g to be ONE
   operator with a SINGLE 'rotation amount', we ask: is phi tied to theta by the pitch?

   THE PITCH a = 1/sqrt(6) is the ratio (axial advance)/(one 2pi/3 turn). It relates the
   TRANSLATION part to the ROTATION part -- BOTH of which live in the SPATIAL/cover factor:
       rotation R  <-> spin S_axis        (spinor)
       advance a   <-> axial momentum p   (cover)
   The pitch locks  a  to  theta : it is a relation WITHIN the spatial sector (advance per turn).
   The INTERNAL charge Q is the C3 weight in the A4 MODULE -- a DIFFERENT factor. The screw g
   does carry an internal C3 phase, but its phi is fixed to be 2pi/3 by the C3 ORDER (sigma^3=1),
   INDEPENDENT of the pitch a: phi = 2pi/3 whatever the value of a. Test this directly.
""")

# =====================================================================================
print("\n" + "=" * 90)
print(" STEP 3 -- THE NORMALIZATION TEST (sharp) AND VERDICT")
print("=" * 90)
theta = phi = 2 * np.pi / 3
Jz = np.array([0.5, -0.5]); Qhat = np.array([0, 1, 2])
print("""
  U(g) = exp(-i theta s_unit Jz)  (x)  exp(+i phi q_unit Qhat),  theta=phi=2pi/3.
  s_unit, q_unit are the two free scales; their RATIO is the question.
  g^3 = pure translation imposes ONE closure per factor:
""")
print("  internal closure  exp(i 3 phi q_unit Qhat) = I :")
for qu in [1.0, 0.5, 2.0]:
    print(f"     q_unit={qu}: closes={np.allclose(np.exp(1j*3*phi*qu*Qhat),1)}")
print("     -> fixes q_unit to INTEGER winding (q_unit=1 primitive). Does NOT involve s_unit.")
print("  spin closure  exp(-i 3 theta s_unit Jz) = spinor 2pi sign :")
print(f"     s_unit=1 -> exp(-i 2pi Jz) = {np.round(np.exp(-1j*2*np.pi*Jz),4)} (= -1, the spinor sign).")
print("     -> fixes s_unit to the 1/2 spinor normalization. Does NOT involve q_unit.")
print("""
  The two conditions are DECOUPLED. Neither references the other; NEITHER references the pitch
  a = 1/sqrt(6). The pitch is the ratio (axial advance)/(turn): it ties the spin S_axis to the
  axial MOMENTUM (both spatial), not to the internal charge Q (a different factor, the A4 module).
  The C3 internal phase phi = 2pi/3 is fixed by the GROUP ORDER (sigma^3 = e) and is invariant
  under any change of pitch/metric (verified). And Q is NOT the axial momentum (its eigenstates
  are spread over all of H_1, with no alignment to the advance t).
""")
print("=" * 90)
print(" VERDICT")
print("=" * 90)
print("""
  HONEST-NEGATIVE: the screw's geometric pitch does NOT force the spin<->charge relative
  normalization. The pitch locks ROTATION to AXIAL ADVANCE -- i.e. SPIN to MOMENTUM, both in the
  spatial/cover factor. The internal charge Q lives in the orthogonal A4-module factor; the screw
  touches it only through the order-3 winding phase 2pi/3, which is set by the group ORDER, not by
  the pitch, and is pitch-invariant.

  WHAT THE SCREW DOES FIX (forced):
    * theta = phi = 2pi/3 -- the spin-rotation amount EQUALS the internal-winding amount, because
      they are the same order-3 element. (This is a quantization, not a normalization: it makes
      both weights live on the same C3 = Z/3, but says nothing about s_unit/q_unit.)
    * q_unit in Z (primitive winding 1); s_unit = 1/2 spinor normalization -- each fixed SEPARATELY
      by its own closure on g^3, independently of the other and of the pitch.

  WHAT STAYS FREE (choice):
    * the single scalar s_unit/q_unit -- the relative normalization between Sz and Q. The screw's
      pitch does not reach it.

  WHAT WOULD FIX IT (named): a structure that makes spin and internal charge parts of ONE
  generator -- i.e. an operator on matter whose spatial-rotation response AND internal-charge
  response are the SAME Cartan (a 'grand-unified' embedding tying the spinor SU(2) and the internal
  C3 in one simple algebra, with a single trace normalization). The bare screw is an OUTER
  (spatial x internal) product, so it cannot; the bridge would have to supply an algebra in which
  spin and charge are non-orthogonal generators sharing one normalization.

  EXTERNAL INPUTS USED: NONE beyond the bare object (srs.py geometry, the verified pitch 1/sqrt6)
  and the two stated rep-content facts (m05 C3 winding weights {0,1,2}; m06 chiral-doubling spin
  Cartan +-1/2). No physics, no adopted constants, no target.
""")
print("[done]")
