"""
How Structure A (the chiral screw) and Structure B (a dilation flow) interact on the
COMMON matter space C^4 = C^2_+ (+) C^2_- (the forced Cl(4) chiral spinor of m06).

PURE MATH. No physics. Native terms: rotation generator, dilation generator, eigenvalue,
commutator, grading. We ADOPT NOTHING numeric as a target; everything is computed and each
coefficient is flagged FORCED or requires-a-CHOICE.
"""
import numpy as np

np.set_printoptions(precision=5, suppress=True, linewidth=130)

# ---- forced Cl(4) data, exactly as in matter_bridge/explore_m06 ----
I2 = np.eye(2)
s1 = np.array([[0, 1], [1, 0]], complex)
s2 = np.array([[0, -1j], [1j, 0]], complex)
s3 = np.array([[1, 0], [0, -1]], complex)
kron = np.kron
g = [kron(s1, s1), kron(s1, s2), kron(s1, s3), kron(s2, I2)]   # spatial g1,g2,g3 ; forced g4
g_c = g[0] @ g[1] @ g[2] @ g[3]                                # chirality grading, gamma_c^2 = I

def comm(A, B): return A @ B - B @ A
def is0(M): return np.allclose(M, 0, atol=1e-10)

print("="*100)
print(" STRUCTURE A (screw) x STRUCTURE B (dilation) on the common matter space C^4")
print("="*100)

# =====================================================================================
# STRUCTURE A — the screw generator on matter.
# The screw locks a rotation about the <111> axis to an axial advance. The matter SPIN
# responds to the *turning* (the rotation part). The rotation generator on the Cl(4)
# spinor about a unit axis n is the standard spin generator
#   S(n) = (1/2) * sum_a n_a Sigma_a ,   Sigma_a = spatial spin = (i/2) eps_{abc} g^b g^c
# Half-integer s=1/2: a 2*pi turn = exp(-i 2pi S(n)) = -I on the spinor (double cover sign);
# the screw's "three turns" = 2*pi total rotation -> spinor returns to MINUS itself (period 6).
# =====================================================================================
print("\n[A] THE SCREW'S TURNING ACTS ON MATTER BY THE SPIN GENERATOR S(n).")

# spin generators S_a = (1/2) Sigma_a , with the rotation generator Sigma_a = (i/2) eps_abc g^b g^c.
# Sigma_a are the EVEN-Clifford rotation generators; they exponentiate as exp(-i theta Sigma_a)
# (a 2pi rotation -> -I). The SPIN operator (eigenvalue +-1/2) is S_a = (1/2) Sigma_a... we check
# directly which normalization gives eigenvalues +-1/2 AND exp(-i 2pi S(n)) = -I.
Sigma = [ (1j/2)*g[1]@g[2], (1j/2)*g[2]@g[0], (1j/2)*g[0]@g[1] ]   # rotation generators
n = np.array([1,1,1],float)/np.sqrt(3)                            # <111> screw axis (unit)
Sig_axis = sum(n[a]*Sigma[a] for a in range(3))                   # rotation generator about axis
print(f"   rotation generator Sigma(n) eigenvalues = {np.round(np.linalg.eigvalsh(Sig_axis),4).tolist()}"
      f"  (these should be +-1/2 already, since Sigma_a are the EVEN-part rotation generators)")
S_axis = Sig_axis                                                 # = the spin operator, eigenvalue +-1/2

ev_S = np.linalg.eigvalsh(S_axis)
print(f"   axis n = <111>/sqrt3 ; spin about axis  S(n) eigenvalues = {np.round(ev_S,4).tolist()}")
print(f"   => spin s = 1/2 (eigenvalues +-1/2). This is the half-integer Structure A attaches.")

# the double-cover sign: a full 2*pi turn (= the 'three turns' of the screw) returns -I.
U_full = np.array(__import__('scipy.linalg', fromlist=['expm']).expm(-1j*2*np.pi*S_axis)) \
    if False else None
# do it without scipy: exp(-i 2pi S) for S with eigenvalues +-1/2 is exp(-i pi) on each = -I
w, V = np.linalg.eigh(S_axis)
U_full = V @ np.diag(np.exp(-1j*2*np.pi*w)) @ V.conj().T
print(f"   2pi turn about axis: exp(-i 2pi S(n)) = -I ?  {np.allclose(U_full,-np.eye(4))}"
      f"   (the forced spinor double-cover sign; matter period 6 not 3).")

# =====================================================================================
# STRUCTURE B — the dilation generator G on the SAME matter space.
# I am told ONLY its structural form: a continuous one-parameter generator whose
# eigenvalues (scaling-charges p) are generated by repeated HALVING, smallest |p| = 1/4,
# obtained as ONE halving of the SAME spinor half 1/2.
#
# To "develop B from the operators alone" I must ask: what operator ON C^4, built from the
# forced structure, has eigenvalues that (i) are a one-parameter dilation generator and
# (ii) have the halving/1/4-floor spectrum keyed to the spin half? The ONLY structure on
# C^4 that supplies a continuous one-parameter grading commuting with the spatial Clifford
# action is generated by the chirality grading gamma_c (the Z2 that splits C^2_+ (+) C^2_-),
# the SAME generator the screw's double-cover sign lives on. A dilation generator whose
# eigenvalues HALVE the spin's 1/2 to a 1/4 floor is, on the operator level,
#   G = c * (spin-tied grading) ,
# i.e. G is proportional to an operator already present. I test the two natural candidates
# the object actually carries: the chirality gamma_c, and the axis-spin S(n) itself.
# =====================================================================================
print("\n[B] BUILD THE DILATION GENERATOR FROM OPERATORS THE OBJECT ALREADY CARRIES.")
print("    A continuous one-parameter generator G with G X = p X. The spectrum is generated")
print("    by HALVING with floor |p|=1/4 = (1/2)*(spin-1/2). Candidate operators on C^4 whose")
print("    eigenvalues are +-1/2 (so that one halving gives +-1/4):")

print(f"    - chirality gamma_c : eigenvalues {np.round(np.linalg.eigvalsh(g_c),4).tolist()} (these are +-1)")
print(f"    - axis spin 2*S(n)  : eigenvalues {np.round(np.linalg.eigvalsh(2*S_axis),4).tolist()} (these are +-1)")
print( "    Either, scaled by 1/2, has eigenvalues +-1/2; scaled by 1/4 gives the +-1/4 floor.")

# The dilation generator as the framework describes it: G whose +-1/4 floor is HALF of the
# spin half. The minimal such G that is (a) one-parameter, (b) Hermitian, (c) tied to the
# SAME spinor half-step is G = (1/4) * (2 S(n)) = (1/2) S(n) -- no, read carefully:
# floor p = 1/4 = (1/2)*(1/2). The 1/2 being halved IS the spin s=1/2. So the operator whose
# eigenvalue 1/2 gets halved is S(n) itself (eigenvalues +-1/2). One halving -> the dilation
# eigenvalue operator is (1/2)*S(n), eigenvalues +-1/4. That is the FORCED reading.
G = 0.5 * S_axis
ev_G = np.linalg.eigvalsh(G)
print(f"\n    FORCED reading: the 1/2 being halved is the spin s=1/2 itself (Structure B's own")
print(f"    statement: '1/4 = one halving of the SAME double-cover half'). So")
print(f"        G = (1/2) * S(n) ,   scaling-charges p = eigenvalues(G) = {np.round(ev_G,4).tolist()}")
print(f"    smallest |p| = 1/4 (the stated floor), and p = (1/2) * s.   [coefficient 1/2 = FORCED")
print(f"    by 'one halving'; the overall scale of G is a CHOICE of units for the dilation param].")

# =====================================================================================
# QUESTION 1 — do G and the screw generator COMMUTE? (compatible labels?)
# The screw generator on matter = its turning part = S(n) (plus an axial-advance part that
# acts trivially on spin, see Q3). Test [G, S(n)] and [G, gamma_c].
# =====================================================================================
print("\n" + "="*100)
print(" Q1  Do the dilation generator G and the screw generator commute? (joint labels?)")
print("="*100)
print(f"   [G, S(n)]   = 0 ?  {is0(comm(G, S_axis))}   (G is a multiple of S(n), so trivially yes)")
print(f"   [G, gamma_c]= 0 ?  {is0(comm(G, g_c))}      (axis spin commutes with chirality grading)")
# also check G commutes with the screw's full one-step unitary (turn + advance); advance is
# scalar on spin, so represented as multiple of I on C^4 -> commutes with everything.
U_step = V @ np.diag(np.exp(-1j*(2*np.pi/3)*w)) @ V.conj().T   # one 120-deg turn
print(f"   [G, U_screwturn(120)] = 0 ? {is0(comm(G, U_step))}   (G commutes with the screw motion)")
print("   => YES: a matter state can carry a definite spin label AND a definite scaling-charge p")
print("      SIMULTANEOUSLY. They share an eigenbasis.   [FORCED, given G built from S(n)]")

# =====================================================================================
# QUESTION 2 — is the ratio spin : scaling-charge FORCED, or free?
# =====================================================================================
print("\n" + "="*100)
print(" Q2  Is the ratio  (scaling-charge p) : (spin s)  forced, or independent?")
print("="*100)
# spin eigenvalues and the paired G eigenvalues, state by state, in the joint eigenbasis:
ws, Vs = np.linalg.eigh(S_axis)
pg = np.array([ (Vs[:,i].conj() @ (G @ Vs[:,i])).real for i in range(4) ])
print(f"   joint eigenbasis (axis):  spin s = {np.round(ws,4).tolist()}")
print(f"                              p     = {np.round(pg,4).tolist()}")
ratios = pg/ws
print(f"   p / s per state = {np.round(ratios,4).tolist()}")
print(f"   LOCKED RATIO  p = (1/2) s  in EVERY state ?  {np.allclose(ratios, 0.5)}")
print("""
   READING:
   * The coefficient 1/2 is FORCED *if* one accepts Structure B's own premise that the 1/4
     floor IS one halving of the SAME spin half. Granting that premise, the dilation operator
     is pinned to (1/2)*S(n) up to an overall scale, so p = s/2 with FORCED coefficient 1/2.
   * BUT this is a near-tautology, and I must flag it: I did not DERIVE that the dilation
     generator is a multiple of the spin operator from the object; I imposed it because the
     premise says the two halves are 'the SAME' half. If instead G is allowed to be ANY
     Hermitian one-parameter generator commuting with the screw (Q1 only fixes commutation),
     then G can be an arbitrary real linear combination of the operators commuting with S(n),
     and the ratio p/s is NOT fixed. Count that freedom: """)

# Count the algebra commuting with the screw turning S(n): how many independent Hermitian
# generators can a 'dilation' G be, if we only require [G,S(n)]=0 (Q1's compatibility)?
# FULL commutant of S(n) in M4(C): solve [X, S(n)] = 0 over ALL complex 4x4 (not just Clifford
# monomials -- S(n) is a SUM of bivectors, so a monomial scan undercounts it). Vectorize.
K = np.kron(np.eye(4), S_axis.T) - np.kron(S_axis, np.eye(4))
sv = np.linalg.svd(K, compute_uv=False)
dimcomm_C = int(np.sum(sv < 1e-9)) + (16 - len(sv))
dimcomm_C = 16 - int(np.sum(sv > 1e-9))
print(f"   FULL commutant of S(n) in M4(C): complex dimension = {dimcomm_C}")
print(f"     (S(n) has eigenvalues +-1/2 each DOUBLY degenerate => commutant = M2(C) (+) M2(C),")
print(f"      C-dim 8; an 8-real-dim space of Hermitian generators a 'dilation' could be.)")
dimcomm = dimcomm_C
print("""   So the COMPATIBILITY condition (Q1) alone leaves an 8-real-dim family of possible dilation
   generators (the full commutant M2 (+) M2); only B's extra premise ('same half, one halving')
   collapses it to the single ray (1/2)*S(n). VERDICT: the ratio is FORCED ONLY by the
   shared-half PREMISE, which is an identification put in by hand, NOT derived from the two
   operators. Absent that identification spin and scaling-charge are INDEPENDENT (free
   relative normalization), with an 8-dim space of inequivalent compatible dilations.""")

# =====================================================================================
# QUESTION 3 — does B's halving supply the discreteness a continuous spatial advance lacked,
# giving spin and scaling-charge a COMMON GRADED generator? Or does B fail the same way?
# =====================================================================================
print("\n" + "="*100)
print(" Q3  Continuous-vs-discrete: does the dilation's halving share a graded generator with spin?")
print("="*100)
# The earlier failure: the screw's AXIAL ADVANCE is a continuous translation along the axis,
# generated by a momentum p_axial with CONTINUOUS spectrum (the Bloch variable k along <111>);
# the spin is DISCRETE (+-1/2). A continuous generator and a discrete one cannot be two grades
# of one Z-graded generator: no shared eigenvalue lattice. We exhibit this.
print("   (i) The screw's AXIAL ADVANCE generator is the axial momentum (Bloch k along <111>):")
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)) + "/../dirac_srs_mdl")
import srs
ks = np.linspace(0,1,7)
band0 = [np.linalg.eigvalsh(srs.adjacency(t*np.array([1,-1,1])))[0] for t in ks]
print(f"       advance spectrum along axis (lowest band vs k): {np.round(band0,3).tolist()}")
print(f"       -> CONTINUOUS in k. The spatial-advance generator has continuous spectrum.")
print(f"       The spin is DISCRETE (+-1/2). No common eigenvalue LATTICE -> the earlier")
print(f"       no-shared-generator failure (continuous advance cannot grade the discrete spin).")

print("\n   (ii) Now the DILATION. Is its halving spectrum a DISCRETE lattice that the spin sits in?")
# The dilation eigenvalues generated by halving from the spin 1/2:  1/2, 1/4, 1/8, 1/16, ...
rungs = [0.5/(2**m) for m in range(6)]
print(f"       halving ladder p_m = (1/2)*2^-m = {rungs}")
print(f"       These are eigenvalues of a generator G whose spectrum is the DISCRETE dyadic set")
print(f"       {{ (1/2) 2^-m }}. The spin value 1/2 IS the m=0 top rung. So the spin DOES sit in")
print(f"       the dilation's discrete spectrum -- UNLIKE the continuous axial advance.")

print("""
   KEY DISTINCTION (decided explicitly):
   * The continuous spatial ADVANCE has spectrum = a continuum (an interval of k). A discrete
     spin value cannot be a 'grade' of it: no Z-grading, no common graded generator. FAILS.
   * The dilation's HALVING is, BY ITS STATED STRUCTURE, a DISCRETE (dyadic, 2-adic) ladder
     p_m = (1/2) 2^-m. A discrete spectrum CAN host the spin value 1/2 as its top rung, and a
     SINGLE generator G with that discrete spectrum carries both. So *structurally* B supplies
     the discreteness the continuous advance lacked.
   HONEST CAVEAT: that 'shared graded generator' is exactly the operator (1/2)*S(n) of Q2 --
   i.e. B closes the gap ONLY under the same shared-half identification. The discreteness is
   genuine (a dilation generator's eigenvalues ARE a discrete ladder, vs the advance's
   continuum), so B differs from the failed continuous advance for a REAL reason; but whether
   the ladder's TOP rung equals the spin 1/2 (the lock) is the put-in identification, not a
   theorem of the bare object.""")

# A concrete check that a dilation generator (multiplicative/2-adic) has discrete spectrum
# while a translation (additive/real) has continuous spectrum -- the structural dichotomy:
print("\n   STRUCTURAL DICHOTOMY (why dilation differs from translation):")
print("     - translation generator (advance): spectrum = R (continuous additive characters).")
print("     - dilation generator with halving:  eigenvalues multiply by 1/2 each step =")
print("       a GEOMETRIC/dyadic sequence -> discrete. Halving is a Z-action (m -> m+1), so")
print("       G is Z-GRADED: G = sum_m p_m P_m with p_m = (1/2)2^-m. THAT is the graded")
print("       generator a discrete spin can share. FORCED: dilation+halving => discrete grading.")

print("\n" + "="*100)
print(" Q4  FORCED vs CHOICE  +  external inputs  +  what stays free")
print("="*100)
print("""
 FORCED (from the object's operators):
   - the matter space is C^4 = C^2_+ (+) C^2_- with spin s=1/2 about any axis (Cl(4), m06);
   - the screw's 2pi turn returns -I (double-cover sign, period 6); [verified above]
   - the axis spin S(n) COMMUTES with chirality gamma_c, so spin and any chirality-tied
     grading share an eigenbasis (Q1 yes);
   - IF a generator's eigenvalues are produced by HALVING, that generator is DISCRETE /
     Z-graded (geometric ladder), categorically unlike the CONTINUOUS axial advance (Q3);
   - GIVEN the shared-half premise, the dilation generator is pinned to (1/2)*S(n), giving the
     LOCKED ratio p = s/2 with FORCED coefficient 1/2 (Q2), and spin+charge share that one
     graded generator (Q3 lock).

 CHOICE / EXTERNAL INPUT (put in by hand, NOT derived from the two operators):
   - the IDENTIFICATION 'the 1/2 halved by B is the SAME 1/2 the screw attaches'. This is the
     load-bearing assumption. The bare object does not force the dilation generator to be a
     multiple of the spin operator; Q1-compatibility alone leaves a multi-dim family of
     dilations (dim reported above). Only this identification collapses it to (1/2)S(n).
   - the overall SCALE/units of the dilation parameter (an overall positive multiple of G);
     fixing the floor at exactly 1/4 is a normalization CHOICE of that scale.
   - the very existence of a dilation generator G on matter is an ADDITIONAL structure
     'described and developed', not present in the bare {Dirac, srs, MDL} (which is tracial
     => trivial scaling flow, STRUCTURE.md s7).

 STAYS FREE:
   - absent the shared-half identification: the relative normalization spin:scaling-charge
     (any ratio), since only commutation is forced;
   - the sign/orientation convention of the screw hand (STRUCTURE.md s8 caveat) and hence the
     sign of the locked ratio.
""")
print("[done]")
