"""
the_map — one figure: the forced object (dimensionless laws) + the one free axis (time).
Everything dimensionless is forced by recurrence-under-running on srs⊕srs-z; the only residual is
the observer's position on the time axis it creates by observing.
"""
import os
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import FancyArrowPatch, FancyBboxPatch
import numpy as np

fig, ax = plt.subplots(figsize=(15, 9.5))
ax.set_xlim(0, 100); ax.set_ylim(0, 100); ax.axis("off")
C_FORCED = "#1b5e20"; C_FREE = "#b71c1c"; C_OBJ = "#0d47a1"; C_BG = "#fafafa"
fig.patch.set_facecolor("white"); ax.set_facecolor(C_BG)

ax.text(50, 96, "THE OBJECT: fully-forced dimensionless laws  +  ONE free axis (time)",
        ha="center", va="center", fontsize=17, fontweight="bold")

# ---- the object (top) ----
box = FancyBboxPatch((34, 86), 32, 6.5, boxstyle="round,pad=0.4", fc="#e3f2fd", ec=C_OBJ, lw=2)
ax.add_patch(box)
ax.text(50, 89.2, "srs ⊕ srs-z   +   Dirac D (a Bayesian learner)   +   MDL",
        ha="center", va="center", fontsize=12.5, fontweight="bold", color=C_OBJ)

# ---- THE TIME AXIS (the one free continuum) — the spine ----
ax.add_patch(FancyArrowPatch((6, 50), (94, 50), arrowstyle="-|>", mutation_scale=28,
                             lw=3.5, color=C_FREE, zorder=3))
ax.text(50, 54.0, "TIME  —  the running ∂_N  (the observer creates it by observing)",
        ha="center", va="center", fontsize=13.5, fontweight="bold", color=C_FREE)
ax.text(7, 46.4, "BEGINNING\nβ=0 · hot · uniform\nsymmetric · GAPLESS",
        ha="left", va="center", fontsize=9.5, color="#555", style="italic")
# the one free point
ax.plot([72], [50], "o", ms=15, color=C_FREE, zorder=5)
ax.text(72, 44.0, "OBSERVER'S SLICE\n= the ONE free input\n(\"what time is it\")\n→ sets the scale = the hierarchy",
        ha="center", va="center", fontsize=9.5, fontweight="bold", color=C_FREE)

# ---- forced freeze-out sequence, ALONG the axis ----
seq = [(20, "TIME switches on", "III₁ · scale-free\ngenerated by D"),
       (40, "GAP / breaking", "srs↔srs-z 4th-γ\nU(1)_A→U(1)_V\nφ pinned {0,π}"),
       (58, "GAUGE", "SU(3)×SU(2)×U(1)\nsin²θ_W = 3/8")]
for x, t, sub in seq:
    ax.plot([x], [50], "|", ms=22, mew=3, color=C_FORCED, zorder=4)
    ax.text(x, 61.5, t, ha="center", va="center", fontsize=11, fontweight="bold", color=C_FORCED)
    ax.text(x, 57.6, sub, ha="center", va="center", fontsize=8.3, color=C_FORCED)

# ---- FORCED outputs (bottom) : the recurrence-under-running products ----
ax.text(50, 36.5, "FORCED  (every dimensionless ratio — recurrence-under-running, no free parameter)",
        ha="center", va="center", fontsize=12.5, fontweight="bold", color=C_FORCED)

def fbox(x, w, title, lines):
    b = FancyBboxPatch((x, 6), w, 26, boxstyle="round,pad=0.3", fc="#e8f5e9", ec=C_FORCED, lw=1.6)
    ax.add_patch(b)
    ax.text(x + w/2, 29.5, title, ha="center", va="center", fontsize=10.5, fontweight="bold", color=C_FORCED)
    ax.text(x + w/2, 18.5, lines, ha="center", va="center", fontsize=9.2, color="#1b3a1f")

fbox(5, 20, "LIGHT masses\n(LOCAL — a slice)",
     "complex shell modes WIND\n→ split at one slice\n\ngenerations  8 : 6 : 6\nphase 0 : ±2π√(3/7)\n[ℚ(√−7)]\nδ = forced chirality")
fbox(28, 20, "HEAVY masses\n(CUMULATIVE — history)",
     "real modes don't wind\n→ integrate the run\n\nHEAVY {k²,(k−1)²}={9,4}\n  ↓ cool by √ (v²→v)\nLIGHT {k,(k−1)}={3,2}\nPerron 4→2 into shell")
fbox(51, 20, "GAUGE / charge",
     "sin²θ_W = 3/8\n(Tr S²/Tr Q², no smuggle)\n\ncharge unit = 1/3\nθ_QCD = 0\n3 generations\nladder = ONE rung")
fbox(74, 21, "the DISSOLVED 'free' knobs",
     "g  → recurrence statistic\nδ  → forced chirality\nhierarchy → the axis (age)\n\nALL forced.\nRemainder = TIME only.")

# arrows object -> axis -> outputs
ax.add_patch(FancyArrowPatch((50, 86), (50, 56), arrowstyle="-|>", mutation_scale=18, lw=2, color="#888"))
for x in (15, 38, 61, 84.5):
    ax.add_patch(FancyArrowPatch((x, 47.5), (x, 32.5), arrowstyle="-|>", mutation_scale=13, lw=1.3, color="#aaa"))

ax.text(50, 2.5, "Static substrate: nothing.   Running observer at a slice: ALL the O(1) structure, forced.   "
        "The observer's POSITION: the scale + the hierarchy = time.",
        ha="center", va="center", fontsize=10, style="italic", color="#444")

plt.tight_layout()
plt.savefig(os.path.join(os.path.dirname(os.path.abspath(__file__)), "the_map.png"), dpi=140, bbox_inches="tight")
print("saved the_map.png")
