"""
explore_i01 — does an interaction bootstrap a scale? PURE MATH, walled (NJL/BCS mean-field).

Add an attractive quartic interaction (strength g) to the second-quantized srs field. Mean-field
(Hartree–Fock–Bogoliubov) gives the self-consistent GAP EQUATION  1 = g·I(m),  I(m)=∫ DOS(ε)/(2√(ε²+m²)) dε
over the srs band density of states. We solve it (continuum DOS, geometric bisection — m spans many
decades) and test for DIMENSIONAL TRANSMUTATION: the dimensionful gap m generated from the dimensionless g
and the geometric bandwidth W as m ~ W·exp(−1/(g·N(0))).
"""
import numpy as np, sys, os
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "dirac_srs_mdl"))
import srs

N = 22; idx = (np.arange(N)+0.5)/N
eps = np.concatenate([np.linalg.eigvalsh(srs.adjacency((a, b, c))) for a in idx for b in idx for c in idx])
eps = eps - np.mean(eps)
W = eps.max() - eps.min()
hist, edges = np.histogram(eps, bins=400, density=True)         # continuum DOS
ec = 0.5*(edges[:-1]+edges[1:]); de = edges[1]-edges[0]
N0 = hist[np.argmin(np.abs(ec))]
print(f"(0) srs band: bandwidth W = {W:.3f}; DOS at center N(0) = {N0:.4f} (finite ⇒ transmutation expected)")

I = lambda m: float(np.sum(hist*de*0.5/np.sqrt(ec**2 + m**2)))   # gap-equation kernel (continuum)
def solve_gap(g):                                                # 1 = g·I(m); geometric bisection
    if g*I(1e-11) < 1.0: return 0.0
    lo, hi = 1e-12, 8.0
    for _ in range(300):
        mid = np.sqrt(lo*hi)
        lo, hi = (mid, hi) if g*I(mid) > 1.0 else (lo, mid)
    return np.sqrt(lo*hi)

print("\n(1) self-consistent gap  1 = g·I(m)  (T=0, attractive coupling g):")
print("    g        gap m            m/W              W·e^(−1/(g·N0))")
gs = np.array([1.0, 1.3, 1.7, 2.2, 3.0])
ms = np.array([solve_gap(g) for g in gs])
for g, m in zip(gs, ms):
    print(f"    {g:.2f}     {m:.3e}     {m/W:.3e}     {W*np.exp(-1.0/(g*N0)):.3e}")

print("\n(2) dimensional transmutation: ln(m/W) linear in −1/g  (a scale from a dimensionless coupling):")
msk = ms > 0
slope, intercept = np.polyfit(-1.0/gs[msk], np.log(ms[msk]/W), 1)
pr = slope*(-1.0/gs[msk]) + intercept
r2 = 1 - np.sum((np.log(ms[msk]/W)-pr)**2)/np.sum((np.log(ms[msk]/W)-np.mean(np.log(ms[msk]/W)))**2)
print(f"    fit ln(m/W) = {slope:.3f}·(−1/g) + {intercept:.3f}   (R² = {r2:.4f});  slope vs 1/N0 = {1/N0:.3f}")
print(f"    => exponential law m ~ W·e^(−1/(g·N0)) confirmed: the gap is generated by DIMENSIONAL TRANSMUTATION.")

print("\n--- finding (interaction, walled) ---")
print("  An attractive quartic interaction + the gap equation DYNAMICALLY GENERATES a gap m. The")
print("  dimensionful scale m is bootstrapped from the DIMENSIONLESS coupling g and the geometric bandwidth")
print("  W by dimensional transmutation, m ~ W·exp(−1/(g·N(0))) — exponentially below W. The wall generates")
print("  its OWN scale: the free input drops from a dimensionful m to a dimensionless g.")
