"""
explore_t01 — the modular (Tomita–Takesaki) flow: time from a non-tracial state. PURE MATH, walled.

The bare object's natural (tracial) state has a TRIVIAL modular flow — it is static. A non-tracial state
gives a canonical 1-parameter modular flow σ_t(x) = ρ^{it} x ρ^{-it}, generated by the modular
Hamiltonian K = −log ρ; the state is the KMS (equilibrium) state of that flow at β = 1. Demonstrated on
the type-I fiber algebra M_4(C) (the Bloch fiber of the verified srs geometry); it generalizes to the
full bundle L^∞(BZ) ⊗ M_4. No physics.
"""
import numpy as np, sys, os
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "dirac_srs_mdl"))
import srs

H = srs.adjacency([0.13, 0.27, 0.41])          # the geometric Hamiltonian on the Bloch fiber (Hermitian)
x = srs.adjacency([0.50, 0.20, 0.10])          # an observable
y = srs.adjacency([0.30, 0.60, 0.05])          # another observable

def modular(rho, a, t):                          # σ_t(a) = ρ^{it} a ρ^{-it}
    w, V = np.linalg.eigh(rho)
    U = V @ np.diag(np.exp(1j*t*np.log(w))) @ V.conj().T
    return U @ a @ U.conj().T

# (A) tracial state ρ ∝ I  ->  trivial modular flow (STATIC)
rho_tr = np.eye(4)/4
static = np.allclose(modular(rho_tr, x, 1.0), x) and np.allclose(modular(rho_tr, x, 3.7), x)
print(f"(A) tracial state ρ ∝ I:  σ_t(x) = x for all t ?  {static}   => STATIC (no intrinsic time).")

# (B) non-tracial geometric state ρ ∝ e^{−βH}  ->  nontrivial modular flow generated by K = −log ρ = βH
beta = 1.0  # UNIT, not a parameter: results are beta-independent (type III_1 for all beta>0; T(M)={0})
w, V = np.linalg.eigh(H)
rho = V @ np.diag(np.exp(-beta*w)) @ V.conj().T; rho /= np.trace(rho)
nontrivial = not np.allclose(modular(rho, x, 1.0), x)
print(f"\n(B) non-tracial state ρ ∝ e^(−βH) (H = the Bloch Dirac/Laplacian):")
print(f"    σ_t(x) ≠ x ?  {nontrivial}   => a canonical flow (TIME) emerges.")
p = np.clip(np.diag(V.conj().T @ rho @ V).real, 1e-15, None)
K = -V @ np.diag(np.log(p)) @ V.conj().T                       # modular Hamiltonian K = −log ρ
Kc = K - np.trace(K)/4*np.eye(4); Hc = H - np.trace(H)/4*np.eye(4)
slope = (np.trace(Kc @ Hc)/np.trace(Hc @ Hc)).real
print(f"    modular Hamiltonian K = −log ρ = β·H + const, slope β = {slope:.4f}  =>  the flow is the")
print(f"    unitary evolution generated by the geometric Hamiltonian H; β is the (input) scale.")

# (C) KMS condition at β=1: <x σ_{−i}(y)> = <y x>  (the state is equilibrium w.r.t. its own modular flow)
def expect(A): return np.trace(rho @ A).real
sig_imag = rho @ y @ np.linalg.inv(rho)                         # σ_{t=−i}(y) = ρ y ρ^{−1}
lhs, rhs = expect(x @ sig_imag), expect(y @ x)
print(f"\n(C) KMS at β=1:  <x σ_(−i)(y)> = <y x> ?  {np.isclose(lhs, rhs)}   ({lhs:.5f} vs {rhs:.5f})")
print(f"    => the non-tracial state is the EQUILIBRIUM (KMS) state of its own modular flow: time is")
print(f"       self-consistent (the state is stationary under the very flow it generates).")

print("\n--- finding (time bridge, walled) ---")
print("  The bare object (tracial) is STATIC. A non-tracial state yields a canonical modular flow = TIME,")
print("  generated by K = −log ρ; for the geometric state ρ ∝ e^(−βH) this is the unitary evolution by H")
print("  (the Dirac/Laplacian), and the state is KMS at β=1. TIME emerges from the state, not the geometry.")
print("  OPEN (next): WHICH non-tracial state is forced, and what SCALE its K carries; and whether the flow")
print("  is intrinsic (state-independent, outer) — which on a type-I algebra it is NOT (inner). Both next.")
