"""
explore_t04 — push the type-III result: is β fixed? do the gap and the time-flow interlock? PURE MATH, walled.

Decisive findings:
 (1) the factor is III_1 for ALL β>0 (the ratio set is ℝ_+ regardless of β) ⇒ β is NOT fixed by the type.
 (2) III_1 is the SCALE-FREE type: dense modular spectrum ⇒ Connes T(M)={0}, NO period — unlike III_λ
     (a lattice ratio set ⇒ period 2π/|log λ| = an intrinsic scale). srs (continuous bands) ⇒ scale-free.
 (3) a matter gap m keeps it III_1 (gapped bands are still continuous); the gap is a frequency in D, not a
     new von Neumann scale, and a *free* field has no self-consistent gap equation.
 ⇒ the two scales (matter gap m, KMS β) are GENUINE FREE INPUTS; the walled {D,srs,MDL} program cannot fix
   them — a scale must enter from outside (the deferred cross-pollination).
"""
import numpy as np, sys, os
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "dirac_srs_mdl"))
import srs

N = 12; idx = (np.arange(N)+0.5)/N
E = np.sort(np.array([np.linalg.eigvalsh(srs.adjacency((a, b, c))) for a in idx for b in idx for c in idx]).flatten())
sub = E[::25]                                                  # ~280 levels across the full band

def span_gap(spectrum):                                        # span and max gap of the |difference| set
    d = np.unique(np.round(np.sort(np.abs(np.subtract.outer(spectrum, spectrum).flatten())), 3))
    d = d[d > 1e-9]
    return d.max(), np.max(np.diff(d))

# (1) β-independence of the type
print("(1) β-independence:  modular spectrum = β·{ε_i−ε_j}; dense ⇒ III_1.")
for beta in [0.5, 1.0, 2.0]:
    sp, gp = span_gap(beta*sub)
    print(f"    β={beta}:  span [0,{sp:.2f}],  max gap {gp:.4f}  ⇒ DENSE ⇒ III_1.")
print("    => III_1 for ALL β>0  ⇒  the TYPE does not fix β.")

# (2) scale-free III_1  vs  scale-bearing III_λ
print("\n(2) scale-free III_1  vs  scale-bearing III_λ:")
sp_c, gp_c = span_gap(sub)
disc = np.arange(-3, 3.0001, 0.5)                              # hypothetical DISCRETE (lattice) spectrum
sp_d, gp_d = span_gap(disc)
print(f"    srs (continuous bands):   max gap {gp_c:.4f}  ⇒ DENSE ratio set ⇒ III_1 ⇒ Connes T(M)={{0}}, NO period ⇒ SCALE-FREE.")
print(f"    discrete spectrum (sp .5): max gap {gp_d:.4f}  ⇒ LATTICE ratio set ⇒ III_λ ⇒ period 2π/|log λ| = a SCALE.")
print(f"    => srs has NO such intrinsic scale.")

# (3) a matter gap m keeps III_1 (and the free field self-generates no gap)
m = 0.4
gapped = np.concatenate([E[E < -m], E[E > m]])                 # open a gap (−m, m)
sp_g, gp_g = span_gap(gapped[::25])
print(f"\n(3) with a matter gap (2m={2*m}):  max gap {gp_g:.4f}  ⇒ still DENSE ⇒ still III_1.")
print(f"    the gap m is a FREQUENCY in D (minimal excitation), not a new von Neumann scale; and a free")
print(f"    field has no self-consistent gap equation (m is a bilinear parameter, not self-generated).")

print("\n--- finding (push, walled) ---")
print("  srs gives type III_1 = the SCALE-FREE type III, for ALL β. So intrinsic time exists (generated by")
print("  D) but carries NO intrinsic discrete scale; β is NOT fixed by the geometry or the type; a matter")
print("  gap stays III_1 and does not self-fix. => the two scales (gap m, KMS β) are GENUINE FREE INPUTS —")
print("  the walled {D, srs, MDL} program CANNOT fix them. A scale must enter from outside the wall.")
