"""
explore_t03 — the type-III route: intrinsic time from the second-quantized field. PURE MATH, walled.

Second-quantize the srs one-particle Dirac space (the CAR algebra over it) and put it in a quasi-free
KMS state ω_β (Fermi–Dirac two-point function). The GNS factor is an Araki–Woods factor; its type is
fixed by the one-particle spectrum. The srs band spectrum is absolutely continuous (dispersive bands,
no flat bands) ⇒ the asymptotic ratio set is ℝ_+ ⇒ TYPE III_1. For type III_1 the modular flow is OUTER
(Connes-canonical, state-independent) = INTRINSIC time, generated by the one-particle Dirac D. This is the
intrinsic time the type-I band algebra (t02) lacked — appearing at the second-quantized (field) level.
"""
import numpy as np, sys, os
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "dirac_srs_mdl"))
import srs

# (0) one-particle spectrum: sample the bands; is it absolutely continuous (dispersive, no flat bands)?
N = 12; idx = (np.arange(N)+0.5)/N
E = np.array([np.linalg.eigvalsh(srs.adjacency((a, b, c))) for a in idx for b in idx for c in idx])  # (N^3,4)
ranges = [E[:, j].max()-E[:, j].min() for j in range(4)]
allE = np.sort(E.flatten())
maxgap = np.max(np.diff(allE))
print("(0) one-particle (Dirac/band) spectrum:")
print(f"    per-band ranges = {[round(r,2) for r in ranges]}  => all dispersive (no flat band): {all(r>0.1 for r in ranges)}")
print(f"    spectrum on [{allE.min():.2f}, {allE.max():.2f}]; max gap among {len(allE)} sampled levels = {maxgap:.3f} (→0 as sample grows)")
print(f"    => absolutely continuous one-particle spectrum.")

# (1) quasi-free KMS state ω_β (Fermi–Dirac); modular flow = free dynamics generated by the Dirac D
beta = 1.0  # UNIT, not a parameter: results are beta-independent (type III_1 for all beta>0; T(M)={0})
h = np.sort(E.flatten())[:300]                                  # a finite one-particle Hamiltonian sample (diagonal)
rho = 1.0/(1.0+np.exp(beta*h))                                  # Fermi–Dirac occupations (the two-point function)
kms = np.allclose(np.exp(-beta*h)*(1.0-rho), rho)               # KMS identity e^{-βh}(1-ρ)=ρ
print(f"\n(1) quasi-free KMS state ρ=(1+e^{{βh}})^(-1):  KMS identity e^(−βh)(1−ρ)=ρ ?  {kms}")
print(f"    => ω_β is KMS w.r.t. the free dynamics α_t(a(f))=a(e^(ith)f); the modular Hamiltonian is")
print(f"       β·dΓ(h) ⇒ the modular flow IS the unitary evolution generated by the geometric Dirac D.")

# (2) type: Araki–Woods asymptotic ratio set = spectrum of the modular generator (energy differences)
sub = np.sort(E.flatten())[::25]                               # ~280 levels spread across the FULL band [-3,3]
d = np.abs(np.subtract.outer(sub, sub).flatten())
d = np.unique(np.round(np.sort(d[d > 1e-9]), 3))
print(f"\n(2) modular (Connes) spectrum = energy-difference set {{ε_i−ε_j}}:")
print(f"    spans [0, {d.max():.2f}], max gap between distinct values = {np.max(np.diff(d)):.4f}  => DENSE (continuous),")
print(f"    NOT a lattice (log λ)·ℤ.  => asymptotic ratio set r_∞ = ℝ_+  => Araki–Woods type III_1 (Connes S(M)=[0,∞)).")

print("\n--- finding (time bridge, type-III route, walled) ---")
print("  Second quantization (CAR over the srs one-particle space) + a quasi-free KMS state ⇒ an Araki–Woods")
print("  factor; the srs spectrum is a.c. ⇒ the factor is TYPE III_1. Type III_1 ⇒ the modular flow is OUTER")
print("  (Connes-canonical, state-independent) = INTRINSIC time, generated by the geometric Dirac D.")
print("  => the intrinsic time the type-I band algebra (t02) lacked, realized at the second-quantized level.")
print("     New ingredient: second quantization (a field). Remaining parameter: the KMS β (normalization).")
