"""
explore_t12 — IS THE OBSERVER'S POSITION IN THE RUN FORCED OR FREE?  PURE MATH, walled.
Reads only ../dirac_srs_mdl + this time_bridge.  No physics; no fitting; no adopted targets;
honest negatives kept.

THE SETUP (established t01-t11, re-verified in sec 0):
  The object runs forward by an INTRINSIC flow (the modular/cooling flow sigma_t, generated by D;
  concretely the Gibbs state rho_beta ~ e^{-beta H} cooled from the tracial/symmetric Gamma start,
  advancing along the C3 screw axis (1,-1,1)/sqrt3).  Everything DIMENSIONLESS it produces is forced
  (ratios).  The ONE thing not fixed by the forced structure is the OVERALL SCALE = the OBSERVER'S
  POSITION / ENDPOINT in the run: WHERE/WHEN the reading is taken.  This position is the parameter
  beta (inverse modular temperature) = "how far the run has advanced", equivalently the screw
  displacement s along the cooling axis.

  An OBSERVER is a learner: it ACCUMULATES evidence as the run advances (observe -> update -> observe;
  Bayesian conjugate).  Its "position" = the accumulated state when the reading is taken.

THE QUESTION: is the observer's position FORCED by the object, or genuinely FREE?

We lay out and TEST three candidates, NOT presuming the answer:

  (A) FREE -- a Cauchy datum.  III_1 / T(M)={0} is scale-free: the cooling flow is HOMOGENEOUS, every
      position equivalent, the "when" is contingent.  TEST: is the flow genuinely homogeneous (no
      distinguished point/scale)?  [sec 1]

  (B) FORCED by a self-consistency fixed point.  The observer reads the substrate; what it reads
      depends on its position; a SELF-CONSISTENT position is a fixed point of observe->update->observe.
      TEST: does the learner's accumulate-update dynamics have a NON-TRIVIAL stationary position
      (a distinguished "when" where observation closes on itself), or only the trivial endpoints? [sec 2]

  (C) FORCED by self-funding (MDL).  Is there a distinguished position where the information extracted
      first PAYS FOR the cost to specify it (a break-even / waterline)?  TEST: is the
      information-vs-cost balance monotone (no special point) or does it single out a position? [sec 3]

  VERDICT [sec 4].

No physics; small matrices; exact where exact; report forced-or-free plainly.
"""
import numpy as np, sys, os
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "dirac_srs_mdl"))
import srs
from scipy.optimize import brentq

np.set_printoptions(precision=6, suppress=True)
def hdr(s): print("\n" + "=" * 84 + "\n" + s + "\n" + "=" * 84)

AXIS = np.array([1.0, -1.0, 1.0]) / np.sqrt(3.0)

# A representative Bloch fiber for the band content, and the cooling axis for the run.
# The cooling state rho_beta ~ e^{-beta H} on a fiber; H = the Bloch adjacency (the geometric H of t01).
# The run forward = increasing beta (cooling) from the tracial start beta=0 (rho ~ I, uniform).

def H_fiber(k):  # the geometric Hamiltonian on a Bloch fiber (the modular generator, t01/t06)
    return srs.adjacency(tuple(k))

# Use the full Brillouin-zone spectrum as the object's one-particle energy content (a.c., t06).
Ng = 14
gg = (np.arange(Ng) + 0.5) / Ng
SPEC = np.sort(np.concatenate(
    [np.linalg.eigvalsh(srs.adjacency((u, v, w))) for u in gg for v in gg for w in gg]))
W = SPEC.max() - SPEC.min()

# =============================================================================================
hdr("(0) RE-VERIFY the setup: intrinsic cooling flow, scale-free III_1, ONE free position beta")
# =============================================================================================
# Gibbs state rho_beta on the BZ spectrum; beta=0 is the tracial (uniform) hot start.
def rho_beta(beta):
    w = np.exp(-beta * (SPEC - SPEC.min()))   # subtract min for numerical stability (a gauge of K)
    return w / w.sum()

# The modular flow sigma_t generated by H is unitary; the COOLING is the family beta -> rho_beta.
# Re-confirm the band-difference (modular) spectrum is dense (III_1) and carries NO lattice scale.
sub = SPEC[:: max(1, len(SPEC)//300)]
d = np.unique(np.round(np.abs(np.subtract.outer(sub, sub).flatten()), 3)); d = d[d > 1e-9]
print(f"  BZ one-particle support width W = {W:.4f};  modular-difference set span [0,{d.max():.3f}], "
      f"max gap {np.max(np.diff(d)):.4f}")
print(f"  => DENSE difference set, no lattice => III_1, T(M)={{0}}: SCALE-FREE.  The run has no intrinsic")
print(f"     unit; the observer's position is the one parameter beta (= how far cooled).  Now: forced?")

# =============================================================================================
hdr("(1) TEST (A): is the cooling flow HOMOGENEOUS (no distinguished point)?")
# =============================================================================================
# Homogeneity has TWO distinct meanings; we separate them, because they give OPPOSITE answers.
#
#  (1a) MODULAR-TIME homogeneity (the III_1 statement): the modular automorphism flow sigma_t is a
#       one-parameter group with NO fixed scale -- translating t by a constant is a symmetry of the
#       FLOW.  This is the genuine scale-freeness.  TRUE.
#
#  (1b) COOLING homogeneity along beta: is the FAMILY of states rho_beta translation-invariant in
#       beta (so every beta looks alike), or does the cooling have DISTINGUISHED points (a hot fixed
#       point beta=0, structural transitions, a low-T limit)?  This is what an OBSERVER that reads
#       rho_beta actually sees.  We test it.

print("  (1a) MODULAR-TIME homogeneity: sigma_{t+c} = sigma_t composed with sigma_c (group), and the")
print("       III_1 ratio set is scale-invariant -- TRUE (re-confirmed in sec 0).  The *modular clock*")
print("       has no preferred origin: this is the genuine support for (A).")

print("\n  (1b) COOLING homogeneity in beta: is rho_beta the same at every beta (a homogeneous flow),")
print("       or are there DISTINGUISHED betas?  An observer reads rho_beta, so this is what matters.")
# A clean diagnostic: the von Neumann entropy S(beta) = -sum p log p of rho_beta, and its derivative
# (the heat capacity C(beta) = -dS/d(log T) ~ beta^2 Var(H)).  A homogeneous flow has FEATURELESS
# (monotone, scale-free) S(beta); a distinguished point shows as a peak/transition in C(beta).
def S_of(beta):
    p = rho_beta(beta); p = p[p > 1e-300]; return -np.sum(p * np.log(p))
def varH(beta):
    p = rho_beta(beta); e = SPEC - SPEC.min(); m = np.sum(p*e); return np.sum(p*(e-m)**2)
betas = np.geomspace(1e-3, 1e3, 25)
print(f"  {'beta':>10} {'S(beta)':>10} {'C=beta^2 VarH':>14}")
Cvals = []
for b in betas:
    C = b*b*varH(b); Cvals.append(C)
    print(f"  {b:10.4g} {S_of(b):10.5f} {C:14.6f}")
Cvals = np.array(Cvals)
ipk = int(np.argmax(Cvals))
print(f"\n  S(beta) runs monotonically from S_max=log(N)={np.log(len(SPEC)):.3f} (hot, beta->0) down to 0")
print(f"  (cold, beta->inf).  Heat capacity C(beta) is NOT featureless: it PEAKS at beta ~ {betas[ipk]:.4g}")
print(f"  (C_max={Cvals[ipk]:.4f}) -- a Schottky-type maximum at the BAND SCALE (beta * energy-spread ~ O(1),")
print(f"  the spread fixed by the band content W={W:.3f}).  So the COOLING family is NOT homogeneous: it has")
print(f"  a distinguished beta set by the band number.  BUT: that number is a ratio fixed by k=3, and the")
print(f"  clock that PARAMETRIZES beta is itself scale-free -- so this peak fixes a distinguished beta")
print(f"  in UNITS of the band scale (beta*spread~O(1)), i.e. it fixes a RATIO, not the absolute 'when'.  Keep this for the verdict.")

# =============================================================================================
hdr("(2) TEST (B): does observe->update->observe have a NON-TRIVIAL self-consistent fixed point?")
# =============================================================================================
# Build the learner explicitly.  The observer at position beta reads the substrate THROUGH the state
# rho_beta (it samples band energies with the Gibbs weights p_i = rho_beta).  Reading is an
# accumulate-then-update step.  A SELF-CONSISTENT position is a fixed point: the position the
# accumulated reading IMPLIES equals the position that produced the reading.
#
# Concretely (a conjugate / EM-style self-consistency): the observer estimates the "temperature" of
# the run from what it sees.  If it reads energies with weights rho_beta, the MAXIMUM-LIKELIHOOD /
# moment estimate of the inverse temperature beta_hat that BEST explains the observed mean energy is a
# map  beta -> beta_hat(beta) = T(beta).  A self-consistent observer position is a FIXED POINT of T:
#   T(beta) = beta.   We ask: are there fixed points OTHER than the trivial endpoints (beta=0 hot,
#   beta=inf cold), i.e. a distinguished interior "when" where the reading closes on itself?
#
# For an exponential-family (Gibbs) model the ML temperature that reproduces the observed mean energy
# <E>_beta IS beta itself (the score equation E_q[E]=<E>_obs is solved by q=rho_beta).  => T(beta)=beta
# IDENTICALLY: EVERY position is a fixed point.  That is the precise statement that the
# observe->update map is the IDENTITY on the cooling family -- self-consistency does NOT pick a point.
# We verify this, then test a STRONGER closure (does the observer's estimate of beta from a FINITE
# accumulated sample converge to a special beta?), to be fair to (B).

e = SPEC - SPEC.min()
def mean_E(beta):
    p = rho_beta(beta); return np.sum(p*e)
def beta_from_meanE(mbar):   # invert <E>_beta = mbar  => the ML/moment temperature estimate
    lo, hi = 1e-6, 1e4
    f = lambda b: mean_E(b) - mbar
    if f(lo) < 0 or f(hi) > 0:  # mbar out of achievable range
        return None
    return brentq(f, lo, hi)
print("  (2a) IDENTITY self-consistency (exponential family): the observer reads mean energy <E>_beta,")
print("       estimates beta_hat solving <E>_{beta_hat} = <E>_beta.  Fixed points of beta->beta_hat:")
print(f"  {'beta':>10} {'<E>_beta':>10} {'beta_hat':>10} {'fixed?':>8}")
allfix = True
for b in [0.05, 0.2, 1.0, 3.0, 10.0]:
    mb = mean_E(b); bh = beta_from_meanE(mb)
    fx = (bh is not None and abs(bh-b) < 1e-4); allfix = allfix and fx
    print(f"  {b:10.4f} {mb:10.5f} {bh if bh else float('nan'):10.5f} {str(fx):>8}")
print(f"  => beta_hat(beta) = beta for ALL beta ({allfix}): the observe->update map is the IDENTITY on")
print(f"     the cooling family.  EVERY position is self-consistent.  => NO distinguished fixed point;")
print(f"     self-consistency does NOT single out a 'when'.  (Support for (A), against (B).)")

# (2b) Be fair to (B): maybe a FINITE accumulating observer has a non-trivial dynamics.  The observer
# accumulates n i.i.d. reads of the band energy under rho_beta (the run feeds it samples as it
# advances), and updates a Bayesian posterior over beta.  Does the posterior MODE flow to a special
# beta, or does it just concentrate on the TRUE beta (whatever it is)?  A conjugate-Bayes learner on
# an exponential family concentrates (Bernstein-von Mises) on the data-generating beta -- which is the
# observer's OWN position.  So it is a CONSISTENT estimator of "where it already is": it converges,
# but to a point set by the (free) true beta, not to a distinguished universal beta.  Verify by
# simulation at several "true" betas: the learner recovers each, with NO universal attractor.
rng = np.random.default_rng(0)
def learn(true_beta, n):
    p = rho_beta(true_beta)
    samples = rng.choice(e, size=n, p=p)        # the run feeds n energy reads
    mbar = samples.mean()
    bh = beta_from_meanE(mbar)                   # posterior concentrates here (conjugate/BvM)
    return bh
print("\n  (2b) FINITE accumulating learner (n reads): does it flow to a UNIVERSAL beta, or recover its")
print("       own (arbitrary) true beta?  (BvM concentration test at several true betas.)")
print(f"  {'true_beta':>10} {'n=50':>9} {'n=500':>9} {'n=5000':>9}")
universal = True; recovered = []
for tb in [0.2, 1.0, 5.0]:
    row = [learn(tb, n) for n in [50, 500, 5000]]
    recovered.append(row[-1])
    print(f"  {tb:10.3f} " + " ".join(f"{(r if r else float('nan')):9.3f}" for r in row))
print(f"  => each learner concentrates on ITS OWN true beta (recovered {np.round(recovered,2)} vs")
print(f"     {[0.2,1.0,5.0]}); there is NO universal attractor.  The learner CONVERGES (trivially) to")
print(f"     wherever it already is.  => (B) gives only TRIVIAL fixed points (the whole family); it does")
print(f"     NOT force a distinguished position.")

# =============================================================================================
hdr("(3) TEST (C): self-funding / MDL -- does info-vs-cost single out a distinguished position?")
# =============================================================================================
# The object's native cost is the MDL: the description length / harmonic energy.  An observer at
# position beta extracts INFORMATION about the substrate (it learns the state) and must PAY a
# description cost to specify its model (a code-length).  Self-funding = the position where extracted
# information first >= cost (a break-even waterline).  We build BOTH ledgers in the object's own units.
#
#  INFORMATION extracted by cooling to beta (relative to the hot/tracial ignorance state beta=0):
#     I(beta) = S(0) - S(beta) = D_KL(rho_beta || rho_0)  -- the bits the observer has GAINED about
#     the state by advancing the run to beta (the uniform hot state is the maximal-ignorance prior;
#     cooling concentrates probability = information gained).  Monotone INCREASING 0 -> log N.
#
#  COST to specify the model at beta: the description length of the cooled state.  Two natural codes,
#  we test both:
#     (i) the modular/thermodynamic WORK = beta*<E> - log Z  (= -log of the partition normalization,
#         the code-length of the Gibbs model = the "free energy" cost of holding the state at beta);
#     (ii) the MDL of the substrate is a CONSTANT (the harmonic energy is fixed by k=3, sec 0) -- the
#         object's description length does not depend on beta.  So a beta-dependent waterline can ONLY
#         come from the STATE's code-length (i), not from the substrate MDL.
#
# Self-funding NET(beta) = I(beta) - Cost(beta).  We look for a distinguished zero/extremum.
def logZ(beta):
    w = -beta*e; m = w.max(); return m + np.log(np.sum(np.exp(w-m)))   # log sum exp(-beta e)
def I_gain(beta):    # information gained vs the hot uniform state = D_KL(rho_beta || uniform)
    p = rho_beta(beta); u = np.ones_like(p)/len(p)
    pp = p[p>1e-300]; uu = u[:len(pp)]
    return np.log(len(p)) - S_of(beta)            # = D_KL(rho_beta||uniform)
def work(beta):      # thermodynamic code-length of the Gibbs model: beta<E> - log Z + log N  (>=0)
    return beta*mean_E(beta) - logZ(beta) + 0.0
# Note logZ(0)=log N, mean_E(0)=<E>_0; we measure cost relative to the hot start so both ledgers start 0.
def cost(beta):      # state code-length relative to the hot start
    return (beta*mean_E(beta) - logZ(beta)) - (0.0 - logZ(0.0))
print("  Ledgers (object units), relative to the hot/tracial start beta=0:")
print(f"  {'beta':>10} {'I_gain':>10} {'Cost(work)':>12} {'NET=I-Cost':>12}")
prev_net = None; mono_net = True; signchange = []
bs = np.geomspace(1e-3, 1e3, 30)
for b in bs:
    Ig = I_gain(b); Cg = cost(b); net = Ig - Cg
    if prev_net is not None and (np.sign(net) != np.sign(prev_net)) and abs(prev_net) > 1e-9:
        signchange.append(b)
    prev_net = net
for b in [1e-3, 1e-2, 0.1, 0.3, 1.0, 3.0, 10.0, 100.0, 1000.0]:
    Ig = I_gain(b); Cg = cost(b); print(f"  {b:10.4g} {Ig:10.5f} {Cg:12.5f} {Ig-Cg:12.5f}")
print(f"\n  Both I_gain and Cost are MONOTONE increasing in beta (more cooling = more info AND more cost).")
print(f"  NET = I - Cost: sign changes / break-even at beta = {np.round(signchange,4) if signchange else 'NONE (no interior waterline)'}")
# Quantify: is NET monotone (no special point) or does it have an interior extremum / zero?
netvals = np.array([I_gain(b)-cost(b) for b in bs])
dnet = np.diff(netvals)
turn = np.where(np.diff(np.sign(dnet)) != 0)[0]
print(f"  NET(beta) interior turning points: {len(turn)}  (0 => featureless/monotone NET => no MDL waterline).")
print(f"  Object MDL (harmonic energy / substrate description length) is beta-INDEPENDENT (constant, sec 0);")
print(f"  the only beta-dependent cost is the state code-length, which tracks I_gain => their balance is")
print(f"  monotone, NO distinguished self-funding position.")

# Cross-check with the t10/t11 cumulative-persistence ledger: the integrated log-persistence M(s) is
# also MONOTONE in the run coordinate s (it accumulates), with no interior break-even -- consistent.

# =============================================================================================
hdr("(4) VERDICT: is the observer's position FORCED or FREE?")
# =============================================================================================
print(f"""  Summary of the three tests:

   (A) HOMOGENEITY.  The MODULAR CLOCK (the III_1 flow sigma_t) is genuinely scale-free / homogeneous:
       T(M)={{0}}, no preferred origin, no intrinsic unit (sec 0,1a).  The COOLING FAMILY rho_beta is
       NOT featureless -- its heat capacity peaks at the band scale (sec 1b) -- but that peak fixes a
       distinguished beta only in UNITS of the (forced, k=3) band number, i.e. it fixes a RATIO,
       NOT the absolute 'when'.  The absolute position has no preferred value: HOMOGENEOUS.  => (A) holds
       at the level of the absolute scale.

   (B) SELF-CONSISTENCY FIXED POINT.  The observe->update map on the cooling family is the IDENTITY
       (exponential-family score equation: beta_hat(beta)=beta for all beta, sec 2a).  A finite
       accumulating learner concentrates (BvM) on ITS OWN true beta, with no universal attractor
       (sec 2b).  => self-consistency is satisfied at EVERY position; it does NOT single out a 'when'.
       (B) provides only the trivial fixed-point continuum, NOT a forced position.

   (C) SELF-FUNDING / MDL.  Information gained I(beta)=D_KL(rho_beta||hot) and the state code-length
       cost both rise MONOTONICALLY with beta; their NET has no interior break-even / waterline
       (sec 3).  The substrate MDL (harmonic energy) is beta-INDEPENDENT, so it cannot fund a
       distinguished position.  => (C) is featureless: NO self-funding 'when'.

  VERDICT:  The observer's ABSOLUTE position in the run is *** FREE -- a Cauchy datum *** (answer A).
  Neither self-consistency (B) nor self-funding (C) singles out a distinguished absolute 'when':
   - the modular flow is scale-free III_1 (homogeneous, T(M)={{0}});
   - observe->update is the identity on the cooling family (every position self-consistent);
   - the info-vs-cost balance is monotone (no waterline).
  The object FORCES everything DIMENSIONLESS (all RATIOS: the band content, the C(beta) peak in units
  of the band scale, the cumulative-persistence ratios) but leaves the OVERALL SCALE = the observer's absolute
  position 'when the reading is taken' as the ONE free input.  This is exactly the t04/t11 endpoint
  scale s*, now shown to be unforced by BOTH candidate fixing mechanisms, not merely unaddressed.

  HONEST NUANCE (the one thing that is NOT free): the object DOES carry a distinguished RELATIVE point
  -- the heat-capacity peak beta* at the band scale and the hot/tracial origin beta=0 -- so the run is not perfectly
  featureless; what is free is only the absolute UNIT/SCALE that turns that ratio into an absolute
  'when'.  FORCED: the relative structure (origin beta=0, the C(beta) peak at the band scale, all ratios).
  CHOICE: the absolute scale / the observer's absolute position (no fixed point, no waterline fixes it).
""")
