"""
explore_t06 — THE COMPLETE FORCED TEMPORAL ARCHITECTURE. PURE MATH, walled.

A single rigorous pass that nails every load-bearing operator-algebra fact behind the claim:
    {Dirac D, srs, MDL} + a (non-tracial) state  =>  INTRINSIC TIME, generated by D, at the
    second-quantized (field) level, of the unique scale-free type III_1, with a forced arrow.

Three facets (Tomita-Takesaki / modular theory):

  FACET 1 (modular flow = time):  tracial state => static; non-tracial state => a canonical
           1-parameter automorphism group sigma_t = Ad(Delta^{it}), Delta = rho (the modular
           operator).  Generator K = -log rho.  For the geometric (Gibbs) state rho ~ e^{-beta H},
           K = beta H + const => the modular flow IS unitary evolution by the Dirac/Bloch H, and
           the state is KMS (equilibrium) at inverse temperature beta.  This is the
           Connes-Rovelli "thermal time": with no external clock, the STATE defines the flow and
           is stationary under it.  beta=1 is a pure normalization (the KMS slope).

  FACET 2 (the von Neumann TYPE):
     (2a) BAND level:  the one-particle/band algebra is L^inf(T^3) (x) M_n  =  TYPE I (a direct
          integral of matrix factors over the 3-torus; amenable crystal).  Type I/semifinite
          => EVERY modular flow is INNER => the canonical map R -> Out(M) is trivial => the
          band-level "time" is STATE-DEPENDENT, NOT intrinsic.
     (2b) FIELD level: second-quantize the srs one-particle Dirac space (the CAR algebra over it)
          in a quasi-free KMS state (Fermi-Dirac).  The GNS factor is ARAKI-WOODS; its Connes
          invariant S(M) (the asymptotic ratio set) = the closed multiplicative group generated
          by {e^{-beta(e_i-e_j)}}.  Because the srs one-particle spectrum is ABSOLUTELY CONTINUOUS
          (verified: a finite union of non-degenerate intervals, dispersive bands), that group is
          DENSE in R_+, so S(M)=[0,infty) and T(M)={0}  =>  TYPE III_1  (for EVERY beta).  In a
          type III_1 factor the modular flow is OUTER and Connes-CANONICAL (state-independent
          modulo inner): INTRINSIC TIME, generated by the one-particle Dirac D (K = beta*dGamma(D)).

  FACET 3 (arrow / dynamics):  the LAW is forced (D is the generator: unitary e^{itD}, and the
           heat semigroup e^{-tD^2}); the arrow is the low-entropy INITIAL CONDITION (monotone
           entropy rise to the static max-entropy fixed point).  At the field/KMS level the same
           Gibbs/KMS state that fixes the modular flow is the equilibrium it relaxes toward; the
           modular Hamiltonian K = beta*dGamma(D) is POSITIVE-spectrum-bounded-below structure
           that orients the flow.

No physics.  Every numerical claim is computed against ../dirac_srs_mdl/srs.py.
"""
import numpy as np, sys, os, math
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "dirac_srs_mdl"))
import srs

np.set_printoptions(precision=4, suppress=True)
def hdr(s): print("\n" + "=" * 78 + "\n" + s + "\n" + "=" * 78)

# =====================================================================================
hdr("FACET 1 — the modular flow: tracial=>static, non-tracial=>time generated by D (KMS)")
# =====================================================================================
# Work on a Bloch fiber.  The fiber observable algebra is M_n(C) (here we use the full
# Hodge-Dirac fiber, n=10) acting on the GNS space; the modular operator of a (faithful) state
# rho is Delta = L_rho R_{rho^{-1}} (left-mult by rho, right-mult by rho^{-1}); sigma_t(x) =
# Delta^{it} x Delta^{-it} = rho^{it} x rho^{-it}.  This is exactly Tomita-Takesaki for a matrix
# algebra in its standard (Hilbert-Schmidt / GNS) form.

H = srs.hodge_dirac((0.13, 0.27, 0.41))          # the geometric Hamiltonian on a Bloch fiber
n = H.shape[0]
x = srs.hodge_dirac((0.50, 0.20, 0.10))           # an observable
y = srs.hodge_dirac((0.30, 0.60, 0.05))           # another observable

def sigma(rho, a, t):                              # sigma_t(a) = rho^{it} a rho^{-it}
    w, V = np.linalg.eigh(rho); w = np.clip(w, 1e-15, None)
    U = V @ np.diag(np.exp(1j * t * np.log(w))) @ V.conj().T
    return U @ a @ U.conj().T

# (1a) tracial state rho ~ I  =>  sigma_t = id  (STATIC).
rho_tr = np.eye(n) / n
static = all(np.allclose(sigma(rho_tr, x, t), x) for t in [0.5, 1.0, 3.7, -2.2])
print(f"(1a) tracial rho ~ I:  sigma_t(x)=x for all t ?  {static}   => STATIC, no intrinsic time.")

# (1b) geometric Gibbs state rho ~ e^{-beta H}; modular generator K=-log rho = beta H + const.
beta = 1.0  # UNIT, not a parameter: results are beta-independent (type III_1 for all beta>0; T(M)={0})
w, V = np.linalg.eigh(H)
rho = V @ np.diag(np.exp(-beta * w)) @ V.conj().T; rho /= np.trace(rho)
moved = not np.allclose(sigma(rho, x, 0.7), x)
# K = -log rho, compare to H (project out the trace part = the +const freedom)
K = -V @ np.diag(np.log(np.clip(np.diag(V.conj().T @ rho @ V).real, 1e-15, None))) @ V.conj().T
def traceless(M): return M - np.trace(M) / n * np.eye(n)
Kc, Hc = traceless(K), traceless(H)
beta_fit = (np.trace(Kc @ Hc) / np.trace(Hc @ Hc)).real
err = np.linalg.norm(Kc - beta_fit * Hc) / np.linalg.norm(Hc)
print(f"(1b) Gibbs rho ~ e^(-betaH):  sigma_t(x) != x ? {moved};  K=-log rho = beta*H + const,")
print(f"     fitted slope beta = {beta_fit:.6f}  (residual ||K-beta H||/||H|| = {err:.2e})")
print(f"     => the modular flow IS unitary evolution generated by the Dirac/Bloch H. beta = KMS slope.")

# (1c) KMS condition (the equilibrium identity): <x sigma_{-i}(y)> = <y x>.
def expect(M): return np.trace(rho @ M).real
sig_mi = rho @ y @ np.linalg.inv(rho)              # sigma_{t=-i}(y) = rho y rho^{-1}
lhs, rhs = expect(x @ sig_mi), expect(y @ x)
print(f"(1c) KMS at beta=1:  <x sigma_(-i)(y)> = <y x> ?  {np.isclose(lhs, rhs)}   ({lhs:.6f} vs {rhs:.6f})")
print(f"     => the Gibbs state is the EQUILIBRIUM (KMS) state of its OWN modular flow (Connes-Rovelli")
print(f"        thermal time: the state defines time and is stationary under it).")

# =====================================================================================
hdr("FACET 2a — the BAND algebra is TYPE I  =>  band-level time is INNER (state-dependent)")
# =====================================================================================
# The bare object's observable algebra is the Bloch band bundle  L^inf(T^3) (x) M_n.  Two facts
# make it type I: (i) a faithful normal TRACE (the fibrewise matrix trace integrated over T^3)
# => semifinite => NOT type III; (ii) MINIMAL (abelian) projections in each fiber => type I (not
# II).  Structural cause: srs is an AMENABLE (Z^3-periodic) crystal, so Bloch theory presents the
# algebra as a direct integral of matrix factors.
rng = np.random.default_rng(0)
rmat = lambda: rng.standard_normal((n, n)) + 1j * rng.standard_normal((n, n))
a, b = rmat(), rmat()
trace_ok = np.isclose(np.trace(a @ b), np.trace(b @ a)) and (np.trace(a.conj().T @ a).real > 0)
# minimal projection: a rank-1 projector p with p M p = (scalar) p  for all M.  The Hodge-Dirac
# fiber is M_4 (+) M_6 (vertex (x) edge blocks); a minimal projection is rank-1 WITHIN a block.
# (A generic rank-1 vector straddling both factors is NOT minimal in the direct sum.)
m4 = 4
v4 = rng.standard_normal(m4) + 1j * rng.standard_normal(m4); v4 /= np.linalg.norm(v4)
vfull = np.zeros(n, complex); vfull[:m4] = v4; p = np.outer(vfull, vfull.conj())
def blockmat():
    M = np.zeros((n, n), complex); M[:m4, :m4] = rmat()[:m4, :m4]
    M[m4:, m4:] = rmat()[m4:, m4:]; return M
minimal = all(np.allclose(p @ M @ p, (vfull.conj() @ M @ vfull) * p) for M in [blockmat() for _ in range(20)])
# patch over the actual T^3 fibers: trace is faithful & finite per fiber
print(f"(2a) faithful normal trace on the fiber M_{n} ?  {trace_ok}   => semifinite => NOT type III.")
print(f"     minimal (block-rank-1 abelian) projections exist ?  {minimal}   => TYPE I (not II).")
print(f"     => L^inf(T^3) (x) M_{n} is TYPE I (amenable crystal: a direct integral of matrix factors).")
print(f"     Connes: on type I / semifinite, sigma_t^omega = Ad((Domega/Dtau)^{{it}}) is INNER,")
print(f"        so R -> Out(M) is TRIVIAL => NO intrinsic time at the band level. (matches t02)")

# =====================================================================================
hdr("FACET 2b — second quantize: the srs spectrum is a.c. => ARAKI-WOODS TYPE III_1 (intrinsic)")
# =====================================================================================
# (2b-i) Absolute continuity of the one-particle spectrum (the analytic crux).  We use BOTH the
# adjacency A(k) (the off-diagonal Dirac block) and the full Hodge-Dirac D(k), since the modular
# generator is dGamma(D).  spec(D)= {+-sqrt(3-a): a in spec(A)} (vertex block, doubled by edges)
# plus zero modes; absolute continuity of A <=> of D on the dispersive part.
Ng = 18
g = (np.arange(Ng) + 0.5) / Ng
specA, specD = [], []
for u in g:
    for vv in g:
        for w_ in g:
            specA.append(np.linalg.eigvalsh(srs.adjacency((u, vv, w_))))
            specD.append(np.linalg.eigvalsh(srs.hodge_dirac((u, vv, w_))))
specA = np.array(specA); specD = np.array(specD)
print(f"(2b-i) ABSOLUTE CONTINUITY of the one-particle spectrum  (grid {Ng}^3):")
# per-band widths of A (4 bands)
wid = [specA[:, j].max() - specA[:, j].min() for j in range(4)]
print(f"   A(k) per-band widths = {[round(x,3) for x in wid]}  => all > 0 (NO flat band).")
# Dirac D: nonzero bands come in +-pairs; report their widths (skip the 2 near-zero columns)
Dcols = np.sort(specD, axis=1)
print(f"   D(k) support ~ [{specD.min():+.3f}, {specD.max():+.3f}];  #near-zero modes (|.|<1e-6) "
      f"per k (generic) = {int(np.median((np.abs(specD) < 1e-6).sum(1)))}")
# continuity convergence law for the COMBINED A spectrum (max intra-band gap -> 0)
def intra_gap(N, op):
    gg = (np.arange(N) + 0.5) / N
    E = np.sort(np.concatenate([np.linalg.eigvalsh(op((u, v, w))) for u in gg for v in gg for w in gg]))
    d = np.sort(np.diff(E))
    return d[:-3].max()   # drop up to 3 inter-band jumps
print(f"   max INTRA-band spacing of A(k) vs grid N (a flat band/atom would NOT shrink):")
prev = None
for N in [6, 9, 12, 16]:
    mg = intra_gap(N, srs.adjacency)
    print(f"      N={N:2d}:  {mg:.4f}" + ("" if prev is None else f"   (x{mg/prev:.2f})")); prev = mg
# non-constant bands a.e. (grad != 0): random k, count |grad E| ~ 0
h = 1e-5; zero_grad = 0; samp = 2000
for _ in range(samp):
    k = rng.random(3); j = rng.integers(4)
    base = np.linalg.eigvalsh(srs.adjacency(tuple(k)))[j]
    gr = []
    for dd in range(3):
        kp = k.copy(); kp[dd] += h
        gr.append((np.linalg.eigvalsh(srs.adjacency(tuple(kp)))[j] - base) / h)
    if np.linalg.norm(gr) < 1e-3: zero_grad += 1
print(f"   fraction of random k with |grad E(k)| < 1e-3 : {zero_grad}/{samp} = {zero_grad/samp:.4f}")
print(f"   => bands are non-degenerate intervals, N(E) continuous, dispersive a.e.  =>  spectrum A.C.")

# (2b-ii) quasi-free KMS state + modular generator = beta dGamma(D); KMS identity at the field level.
beta = 1.0  # UNIT, not a parameter: results are beta-independent (type III_1 for all beta>0; T(M)={0})
hsamp = np.sort(specA.flatten())[:: max(1, specA.size // 400)]   # one-particle energies sample
rho_fd = 1.0 / (1.0 + np.exp(beta * hsamp))                      # Fermi-Dirac occupations
kms_field = np.allclose(np.exp(-beta * hsamp) * (1.0 - rho_fd), rho_fd)
print(f"\n(2b-ii) quasi-free KMS state rho=(1+e^(beta h))^(-1):  KMS identity e^(-beta h)(1-rho)=rho ?"
      f"  {kms_field}")
print(f"   => omega_beta is KMS w.r.t. the free dynamics alpha_t(a(f))=a(e^(ith) f); modular")
print(f"      Hamiltonian = beta*dGamma(h) = beta*dGamma(D): the field modular flow = evolution by D.")

# (2b-iii) Araki-Woods type: S(M) = closed mult. group gen by {e^{-beta(e_i-e_j)}}; dense => III_1.
specfull = np.sort(specA.flatten())
sub = specfull[:: max(1, len(specfull) // 350)]                 # ~350 levels across full support
diffs = np.subtract.outer(sub, sub).flatten()
diffs = diffs[np.abs(diffs) > 1e-12]
W = specA.max() - specA.min()
print(f"\n(2b-iii) ARAKI-WOODS ratio set / Connes S(M):")
print(f"   one-particle support width W = {W:.4f};  energy-difference set |e_i-e_j| range "
      f"[0+, {np.abs(diffs).max():.4f}]  (reaches W).")
for bb in [0.5, 1.0, 2.0, 7.3]:
    logr = np.unique(np.round(-bb * diffs, 3))     # log of the ratio set = modular log-spectrum
    print(f"   beta={bb:>4}:  modular log-spectrum span [{logr.min():+.2f},{logr.max():+.2f}], "
          f"max gap {np.max(np.diff(logr)):.4f}  => DENSE (no lattice (log lambda)Z)  => III_1.")
print(f"   => S(M)=[0,infty), T(M)={{0}} (no period, scale-free) for EVERY beta>0  =>  TYPE III_1.")
print(f"   => in III_1 the modular flow is OUTER & Connes-canonical (state-independent mod inner):")
print(f"      INTRINSIC TIME, generated by the one-particle Dirac D.")

# Contrast: a discrete (lattice) spectrum would give III_lambda (a SCALE).
disc = np.arange(-3, 3.0001, 0.5)
dl = np.unique(np.round(np.abs(np.subtract.outer(disc, disc).flatten()), 6)); dl = dl[dl > 1e-9]
print(f"   [contrast] discrete spectrum (spacing 0.5): differences = {dl[:5]}... a LATTICE "
      f"=> III_lambda, period 2pi/|log lambda| = a SCALE.  srs has NONE.")

# =====================================================================================
hdr("FACET 3 — the arrow: the LAW is forced (gen. by D); the arrow is the low-entropy initial data")
# =====================================================================================
# On a finite srs patch, evolve a localized state by the heat semigroup e^{-tL} (L=D^2=Laplacian)
# and show monotone entropy rise to the static max-entropy fixed point; the unitary Dirac flow
# e^{itA} is reversible/ballistic.  The field KMS state of FACET 2 is the equilibrium this relaxes
# to; K=beta*dGamma(D) (bounded-below modular generator) ORIENTS the modular flow.
R = 3
cells = [(x_, y_, z_) for x_ in range(-R, R+1) for y_ in range(-R, R+1) for z_ in range(-R, R+1)]
cidx = {c: i for i, c in enumerate(cells)}; nv = 4 * len(cells)
def vid(s, cell): return cidx[cell] * 4 + s
Adj = np.zeros((nv, nv))
for cell in cells:
    aa, bb, cc = cell
    for (i, j, vv) in srs.EDGES:
        nbr = (aa + vv[0], bb + vv[1], cc + vv[2])
        if nbr in cidx:
            xx, yy = vid(i, cell), vid(j, nbr); Adj[xx, yy] += 1; Adj[yy, xx] += 1
deg = Adj.sum(1); L = np.diag(deg) - Adj
posv = np.zeros((nv, 3))
for cell in cells:
    for s in range(4): posv[vid(s, cell)] = cell
r2 = (posv ** 2).sum(1)
psi0 = np.zeros(nv); psi0[vid(0, (0, 0, 0))] = 1.0
wL, VL = np.linalg.eigh(L); wA, VA = np.linalg.eigh(Adj)
def heat(t): p = VL @ (np.exp(-t * wL) * (VL.T @ psi0)); p = np.clip(p, 0, None); return p / p.sum()
def wave(t): ps = VA @ (np.exp(1j * t * wA) * (VA.T @ psi0)); p = np.abs(ps) ** 2; return p / p.sum()
print(f"(3) finite srs patch R={R}: {len(cells)} cells, {nv} vertices.  Heat flow e^(-tL), L=D^2:")
prevS = -1; mono = True
print(f"     t        S(t) [max {math.log(nv):.3f}]    <r^2>")
for t in [0.0, 0.3, 1.0, 3.0, 10.0, 30.0, 100.0]:
    p = heat(t); S = -np.sum(p[p > 1e-15] * np.log(p[p > 1e-15]))
    if S < prevS - 1e-9: mono = False
    prevS = S
    print(f"   {t:6.1f}    {S:.4f}                {np.sum(p * r2):.3f}")
print(f"   entropy monotone non-decreasing ?  {mono}   => the ARROW (relaxation to the static")
print(f"      max-entropy fixed point); the law e^(-tL) is forced, the arrow is the initial datum.")
# spreading exponents
th = np.array([1.0, 2.0, 3.0]); ph = [np.sum(heat(t) * r2) for t in th]
tw = np.array([0.6, 0.9, 1.2]); pw = [np.sum(wave(t) * r2) for t in tw]
print(f"   spreading <r^2>~t^p:  heat p={np.polyfit(np.log(th), np.log(ph),1)[0]:.2f} (diffusive),"
      f"  wave p={np.polyfit(np.log(tw), np.log(pw),1)[0]:.2f} (ballistic light-cone).")

hdr("VERDICT — the complete forced temporal architecture (all facets verified)")
print("""  FORCED:
   * the modular-flow MECHANISM (tracial=>static; non-tracial=>sigma_t=Ad(rho^{it}), K=-log rho);
   * for the geometric state, K = beta*H : the flow IS unitary evolution by the Dirac D, KMS;
   * the band algebra is TYPE I (amenable crystal) => band time INNER/state-dependent;
   * the one-particle srs spectrum is ABSOLUTELY CONTINUOUS (no flat band; dispersive a.e.);
   * second-quantized + KMS => Araki-Woods TYPE III_1 (S(M)=[0,inf), T(M)={0}) for ALL beta
     => the modular flow is OUTER/Connes-canonical = INTRINSIC TIME generated by D;
   * the dynamical LAW (e^{itD}, e^{-tD^2}) and the ARROW = relaxation to the static fixed point.
  IRREDUCIBLE-INPUT:  second quantization (passing from band algebra to the CAR field) is the
     structural ingredient that turns type I into type III_1; the KMS beta is a pure normalization
     (the type is beta-independent), and III_1 is scale-FREE (T(M)={0}) so the program supplies NO
     intrinsic temporal scale.
  OPEN:  none internal to the temporal architecture; fixing an external scale (beta, or a matter
     gap) is the deferred, permission-gated cross-pollination, NOT an internal refinement.""")
