#!/usr/bin/env python3
"""
OS-2 Session 1 audit-before-ansatz — rate-gap magnitude bound probe (2026-05-15).

CONTEXT
-------
Session handoff `session_handoff_2026-05-15_path_D_via_observer_substrate_split.md`
proposed (D.6') = OS-2 reframing: derive epsilon_toggle(z) and check whether
H_obs(z) = (1 + eps(z)/k*) * H_substrate(z) closes r_s under coasting.

The narrow form is rho(z) = 1 + eps(z)/k* where eps(z) is the Bayesian-toggle
posterior asymmetry generalized to epoch z.

STRUCTURAL BOUND BEING CHECKED
------------------------------
By Bayesian-probability normalization, eps_toggle = (P_perp - P_par)/(P_perp + P_par)
with P_perp, P_par in [0, 1].  Therefore |eps| <= 1, and rho <= 1 + 1/k* = 4/3.

For r_s convergence under coasting H_substrate(z) = H_0 * (1+z), the conformal-time
integral

    r_s = int_{z_*}^{inf} c_s * dz / H_obs(z) = int_{z_*}^{inf} c_s * dz / (rho(z) * H_0 * (1+z))

is divergent for rho(z) bounded.  Closure to Planck r_s ~ 147 Mpc requires
rho(z) ~ (1+z) at high z (so that H_obs ~ (1+z)^2 like radiation-domination).

This probe quantifies the magnitude gap between rho_max = 4/3 (allowed by Bayesian
normalization, narrow form) and rho_required ~ 1100 at z_* (required for r_s
closure).  Verdict: the gap is ~3 orders of magnitude.

This is the audit-before-ansatz outcome for OS-2 Session 1.  OS-2 in the narrow
form rho(z) = 1 + eps_toggle(z)/k* is structurally impossible to close r_s
regardless of how the framework derives eps(z), because the bound is set by
Bayesian probability normalization, not by the specific Beta-posterior derivation.

Per parameter_linter Clause 8 (numerical-match audit): a derivation that cannot
reach within 3 orders of magnitude of the target is structurally negative.

K-RATIONALITY (Clause 6) CHECK
------------------------------
Any eps(z) of the narrow Bayesian-asymmetry form is K-rational at each z (Beta
posteriors give rational P_perp, P_par).  Bound eps in [-1, 1] forces rho in
[1-1/k*, 1+1/k*] = [2/3, 4/3] — a K-rational interval.  But the required rho(z*)
~ z* ~ 1100 is outside this interval at z_* and grows.  K-rational structural
content is bounded; required rho(z) is not.

This is structural, not numerological.  No fitting; just the bound from the
definition.

DOWNSTREAM
----------
OS-2 broad form (rho(z) generated by a different mechanism, not 1 + eps/k*)
would require a NEW substrate-observer coupling primitive beyond cascade D2-ext.
Per substrate_r_s_mechanism_audit_2026-05-09.md, this is L6-blocked
(intermediate-scale field theory; estimated 5-10 sessions research-program scope).
"""

from __future__ import annotations

import math
import os
import sys

_REPO_ROOT = os.path.abspath(
    os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..')
)
if _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)


# Framework primitives
K_STAR = 3
EPS_TOGGLE = 1.0 / 5.0          # Beta(1,1) -> Beta(2,1) asymmetry at z=0 (Row P28)
RHO_Z_ZERO = 1.0 + EPS_TOGGLE / K_STAR  # 16/15 at z=0, theorem-grade

# Cosmology setup
H_0_KMSMPC = 67.4
c_KMS = 2.998e5
HUBBLE_RADIUS_MPC = c_KMS / H_0_KMSMPC
R_S_PLANCK_MPC = 147.06
Z_STAR = 1089.0

# Substrate-stability cutoff (per path_D5 probe)
T_PLANCK_K = 1.416784e32
T_CMB_TODAY_K = 2.7255
G_GIRTH = 10
ALPHA_1 = (2.0 / 3.0) ** (G_GIRTH - 2)
N_G = 15
C_SRS_BITS = N_G * math.log2(1.0 / ALPHA_1)
T_SRS_PLANCK = C_SRS_BITS / math.log(2)
Z_SRS = T_SRS_PLANCK * T_PLANCK_K / T_CMB_TODAY_K


def rho_max_narrow_form(k_star: int) -> float:
    """
    Maximum value of rho(z) = 1 + eps/k* under |eps| <= 1.

    Bayesian-probability normalization forces |eps_toggle| <= 1 at any epoch.
    Therefore rho_max = 1 + 1/k*.

    For k* = 3, this gives 4/3.
    """
    return 1.0 + 1.0 / k_star


def r_s_under_narrow_form_max(rho_max: float, c_s_over_c: float, z_star: float,
                              z_uv_cutoff: float) -> float:
    """
    r_s under the MOST FAVORABLE narrow-form profile: rho(z) = rho_max constant
    across the integration range, with UV cutoff at substrate-stability z_srs.

    Under coasting H_obs(z) = rho_max * H_0 * (1+z), the integral

        r_s = c_s int_{z_*}^{z_uv} dz / H_obs(z)
            = (c_s/H_0) / rho_max * ln((1+z_uv)/(1+z_*))

    This is the LOWER BOUND on r_s achievable in the narrow form: any actual
    profile rho(z) <= rho_max gives r_s >= this value.  If even this lower
    bound is too large vs Planck r_s, the narrow form cannot close r_s.

    Returns r_s in Mpc.
    """
    return (HUBBLE_RADIUS_MPC * c_s_over_c / rho_max) * math.log(
        (1.0 + z_uv_cutoff) / (1.0 + z_star)
    )


def r_s_required_rho_high_z(c_s_over_c: float, z_star: float) -> float:
    """
    Best-case rho(z) profile to give EXACTLY r_s = Planck under coasting.

    Assume rho(z) = rho_1 * (1+z) (linear, mimicking radiation-era H ~ (1+z)^2).
    Then H_obs = rho_1 * H_0 * (1+z)^2 and

        r_s = c_s int_{z_*}^inf dz / (rho_1 * H_0 * (1+z)^2)
            = (c_s/H_0)/rho_1 * 1/(1+z_*)

    Solving for rho(z_*) = rho_1 * (1+z_*) = (c_s/H_0) / r_s.

    This is the MINIMUM rho(z_*) needed at z_* for r_s closure (the linear
    profile is the slowest-growing convergent option).  Anything sub-linear
    gives divergent r_s; anything super-linear over-corrects.
    """
    return HUBBLE_RADIUS_MPC * c_s_over_c / R_S_PLANCK_MPC


def main():
    print("=" * 80)
    print(" OS-2 Session 1 audit-before-ansatz — narrow-form magnitude bound")
    print("=" * 80)
    print()

    print(" §A. Framework-fixed quantities (theorem-grade)")
    print(" " + "-" * 76)
    print(f"   eps_toggle (z=0)                      = 1/{int(1/EPS_TOGGLE)} = {EPS_TOGGLE}")
    print(f"     [Row P28, persistence theorem 2026-05-07]")
    print(f"   k*                                     = {K_STAR}")
    print(f"     [Gleason d_spatial=3, theorem-grade]")
    print(f"   rho(z=0) = 1 + eps_toggle/k*           = {RHO_Z_ZERO:.6f} = 16/15")
    print(f"     [cascade D2-ext, theorem-grade 2026-05-07 PM]")
    print()

    print(" §B. Narrow-form structural bound on rho(z)")
    print(" " + "-" * 76)
    print(f"   Definition: eps_toggle(z) = (P_perp(z) - P_par(z)) / (P_perp(z) + P_par(z))")
    print(f"   With P_perp(z), P_par(z) in [0, 1], standard probability theory gives:")
    print(f"     |eps_toggle(z)| <= 1  (Bayesian normalization)")
    print(f"   Therefore:")
    rho_max = rho_max_narrow_form(K_STAR)
    print(f"     rho_max(z) = 1 + 1/k*  = 1 + 1/{K_STAR} = {rho_max:.6f} = 4/3")
    print()
    print(f"   This bound is K-rational (4/3 in Q).  It is structural, not numerical:")
    print(f"   it follows from probability normalization regardless of which mechanism")
    print(f"   generates eps_toggle(z) within the Bayesian-asymmetry form.")
    print()

    print(" §C. Two routes to falsify narrow form vs Planck r_s")
    print(" " + "-" * 76)
    print()
    print(f"   Route 1 — DIVERGENCE: bounded rho gives divergent r_s.")
    print(f"   Under coasting H_obs(z) = rho(z) H_0 (1+z), r_s = c_s int dz/H_obs.")
    print(f"   For bounded rho(z) in [1, rho_max], r_s is LOWER-BOUNDED by the")
    print(f"   integral at rho = rho_max, which gives:")
    cs_over_c = 1.0 / math.sqrt(3)
    z_srs_eff = Z_SRS
    r_s_best_narrow = r_s_under_narrow_form_max(rho_max, cs_over_c, Z_STAR, z_srs_eff)
    print(f"     r_s_min(narrow) = (c_s/(rho_max*H_0)) * ln((1+z_srs)/(1+z_*))")
    print(f"     With c_s/c = 1/sqrt(3), rho_max = 4/3, z_srs = {Z_SRS:.2e}:")
    print(f"     r_s_min(narrow) ~ {r_s_best_narrow:.0f} Mpc")
    print(f"     Planck r_s      = {R_S_PLANCK_MPC} Mpc")
    print()
    ratio_div = r_s_best_narrow / R_S_PLANCK_MPC
    print(f"   Ratio: narrow-form r_s lower-bound / Planck = {ratio_div:.1f}")
    print(f"   The narrow form OVERSHOOTS Planck r_s by ~{math.log10(ratio_div):.1f}")
    print(f"   orders of magnitude even at its most favorable saturated profile.")
    print(f"   (Without UV cutoff, r_s diverges logarithmically; with substrate")
    print(f"   T_srs cutoff, finite-but-far-too-large.)")
    print()
    print(f"   Route 2 — REQUIRED rho(z) PROFILE: closure needs unbounded growth.")
    print(f"   For r_s = Planck under coasting, best-case rho(z) ~ rho_0*(1+z) gives:")
    rho_req_zstar = r_s_required_rho_high_z(cs_over_c, Z_STAR)
    print(f"     rho(z_*) >= (c_s/H_0)/r_s_Planck = {rho_req_zstar:.2f}")
    ratio_req = rho_req_zstar / rho_max
    print(f"   Compare narrow-form bound rho_max = 4/3 = {rho_max:.4f}.")
    print(f"   Required at z_* ~ {ratio_req:.1f}x higher than allowed.")
    print(f"   And rho must KEEP GROWING with z (unbounded), incompatible with")
    print(f"   any bounded mechanism within the Bayesian-asymmetry form.")
    print()

    print(" §D. Magnitude gap synthesis")
    print(" " + "-" * 76)
    print(f"   Route 1 (r_s overshoot)  : {ratio_div:.1f}x  ({math.log10(ratio_div):.1f} orders)")
    print(f"   Route 2 (rho(z_*) gap)   : {ratio_req:.1f}x  ({math.log10(ratio_req):.1f} orders)")
    print()
    print(f"   Both routes agree the gap is real and structural.  Route 1 says")
    print(f"   that even the most favorable saturated narrow-form profile gives")
    print(f"   r_s far too large (by ~3 orders of magnitude).  Route 2 says even")
    print(f"   if we tried a growing rho(z) profile, you'd need it to exceed the")
    print(f"   narrow-form Bayesian bound by ~1 order of magnitude at z_* and")
    print(f"   grow without bound at z > z_*.")
    print()
    print(f"   Both observations are structural (set by |eps_toggle| <= 1, by")
    print(f"   the cascade D2-ext form 1 + eps/k*, and by coasting H ~ (1+z)).")
    print(f"   No choice of MECHANISM for generating eps(z) within the narrow")
    print(f"   form rescues either route.")
    print()

    print(" §E. Cross-check against persistence theorem 2026-05-07")
    print(" " + "-" * 76)
    print(f"   theorem_observer_persistence_closure_IC_amplitude.md §4 chain:")
    print(f"     Step 3 (Bridge 1): eps_toggle = 1/5 derived at N=1 IC")
    print(f"     Step 5 (P1' persistence): M_IC retained from N=1 to N_hub")
    print(f"     Step 6: observer's predictions = eps_toggle along z-hat")
    print()
    print(f"   This locks eps_toggle = 1/5 in the OBSERVER'S COMPRESSED MODEL")
    print(f"   at every N (every observable epoch).  Two reconciliations possible:")
    print()
    print(f"   (alpha) Persistence theorem still holds — but at high z, the SUBSTRATE")
    print(f"           value of eps_toggle differs from the observer's model.")
    print(f"           This breaks Bridge 1's 'eps fixed at N=1' framing — it would")
    print(f"           require N=1 to set a DIFFERENT eps than 1/5, or for the")
    print(f"           Bayesian update to be multi-event with z-dependence.")
    print(f"           Bridge 1 is theorem-grade in current framework; (alpha) requires")
    print(f"           reformulating it.")
    print()
    print(f"   (beta)  Persistence theorem retains eps = 1/5 always, and rho(z)")
    print(f"           is generated by a NEW substrate-observer coupling primitive")
    print(f"           beyond cascade D2-ext.  Such a primitive would not be of the")
    print(f"           1 + eps/k* form, so it could in principle break the 4/3 bound.")
    print(f"           Per substrate_r_s_mechanism_audit_2026-05-09.md, this is")
    print(f"           L6-blocked (intermediate-scale field theory from substrate).")
    print()
    print(f"   Within current theorem-grade framework, the narrow form is closed.")
    print()

    print(" §F. K-rationality assessment (parameter_linter Clause 6)")
    print(" " + "-" * 76)
    print(f"   For OS-2 to produce a K-rational rho(z) (per Clause 6, K = Q(sqrt2,3,5)):")
    print(f"   - Narrow-form rho(z) = 1 + eps(z)/k* with eps(z) from Beta posteriors:")
    print(f"     Each Beta posterior gives a K-rational eps_toggle(z) at each z.")
    print(f"     But the FUNCTIONAL FORM rho(z) — a continuous function of z —")
    print(f"     is not itself K-valued unless z is restricted to discrete substrate")
    print(f"     count values N(z) and rho is evaluated at each N.")
    print(f"   - At each discrete N, rho_N would be K-rational, but the IMAGE of")
    print(f"     {{rho_N : N in [1, N_hub]}} would be bounded by [2/3, 4/3] — too narrow.")
    print(f"   - Broad-form rho(z) with new primitive: K-rationality at each fixed")
    print(f"     epoch is required by Clause 6, but the new primitive must produce")
    print(f"     unbounded values (rho ~ z at high z) which is incompatible with any")
    print(f"     K-rational mechanism that's bounded by structural finiteness.")
    print()
    print(f"   Verdict: OS-2 cannot close r_s via K-rational, structurally bounded")
    print(f"   rho(z).  Any closure would require an UNBOUNDED rho(z) profile, which")
    print(f"   exits Clause 6 by definition (K-rational mechanisms must be bounded by")
    print(f"   substrate finiteness).")
    print()

    print("=" * 80)
    print(" VERDICT — OS-2 Session 1")
    print("=" * 80)
    print()
    print(f"   OS-2 NARROW FORM (rho = 1 + eps/k*) is STRUCTURALLY BOUNDED at 4/3.")
    print(f"   Route 1: gives r_s ~ {r_s_best_narrow:.0f} Mpc vs Planck {R_S_PLANCK_MPC} Mpc")
    print(f"   ({math.log10(ratio_div):.1f} orders too large).")
    print(f"   Route 2: rho(z_*) needs >= {rho_req_zstar:.1f}, vs bound 4/3")
    print(f"   ({math.log10(ratio_req):.1f} orders too small).  Both structurally impossible")
    print(f"   in the Bayesian-asymmetry narrow form.")
    print()
    print(f"   This bound is theorem-grade (Bayesian probability normalization),")
    print(f"   K-rational (4/3 in Q), and INDEPENDENT of how eps(z) is generated")
    print(f"   within the Bayesian-asymmetry framework.")
    print()
    print(f"   Therefore OS-2 narrow form is CLOSED-NEGATIVE this session, joining")
    print(f"   (D.1), (D.4), (D.5) as the fourth bounded Path D / OS-2 probe with")
    print(f"   structural negative verdict.")
    print()
    print(f"   OS-2 BROAD FORM (new substrate-observer coupling primitive beyond")
    print(f"   cascade D2-ext) inherits substrate_r_s_mechanism_audit_2026-05-09's")
    print(f"   L6 blocker (intermediate-scale field theory; research-program scope")
    print(f"   5-10 sessions, NA-4-adjacent NEG ×3 history).")
    print()
    print(f"   The narrow-form magnitude bound is the audit-before-ansatz output")
    print(f"   that converts OS-2 from 'open multi-sprint' to 'narrow CLOSED-NEG +")
    print(f"   broad L6-blocked'.")
    print()

    # Hard checks — these are structural facts, not fitted
    assert abs(rho_max - 4.0/3.0) < 1e-12, "rho_max should be exactly 4/3"
    assert r_s_best_narrow > 100.0 * R_S_PLANCK_MPC, \
        "narrow-form r_s lower-bound should exceed Planck by >100x (Route 1)"
    assert ratio_req > 10.0, \
        "required rho(z_*) should exceed narrow-form bound by >10x (Route 2)"
    print(f"   Assertions: rho_max = 4/3 ✓ | Route 1 overshoot >100x ✓ | "
          f"Route 2 gap >10x ✓")
    return 0


if __name__ == "__main__":
    sys.exit(main())
