"""
explore_m07 — THE FORCED SYMMETRY-BREAKING / VACUUM ARCHITECTURE of the srs Dirac operator.
PURE MATH, walled (no physics; see README). Builds on the verified bare object (../dirac_srs_mdl/srs.py),
the spinor architecture (m06), the srs(+)srs-z doubling (m04), and the gap equation (../interaction/i01).

This is the *symmetry-breaking / scalar(Higgs-analog) / vacuum* facet, derived as theorems and verified by
computation. Every result is marked FORCED / IRREDUCIBLE-INPUT / OPEN.

  (1) THE SCALAR (HIGGS-ANALOG) SECTOR as the inner fluctuation of D in the FINITE (internal /
      enantiomer) direction: what scalar field structure is FORCED — the connection along the
      discrete srs<->srs-z direction.  Result: the order parameter is a SINGLE COMPLEX scalar
      M = m e^{i phi}; its space is exactly 2-dimensional, span{gamma^4, gamma_c}; |M| is the gap,
      arg(M) the chiral/axial phase = the srs-z<->srs relative orientation.

  (2) THE VACUUM / BREAKING PATTERN: the massless doubled Dirac has a continuous chiral symmetry
      U(1)_V x U(1)_A; the gap (M != 0) breaks U(1)_A spontaneously: U(1)_V x U(1)_A -> U(1)_V.
      The relative orientation phi is NOT a continuous free angle — MDL (the harmonic / shortest-
      description standard realization in the SHARED Z^3 lattice) forces a CRYSTALLOGRAPHIC
      (finite, quantized) registration; the unique canonical one is the INVERSION -I, which PINS
      phi to a definite value (0 mod pi).  The breaking is DETERMINED, not a knob.

  (3) THE DIMENSIONAL-TRANSMUTATION / GAP STRUCTURE: |M| is generated by the gap equation
      m ~ W e^{-1/(g N0)} (the wall makes its own scale, ../interaction/i01).  What is FORCED is the
      mechanism + the geometric inputs (W, N0); the one IRREDUCIBLE-INPUT is the overall scale (the
      unit/ruler).  arg(M) (the breaking phase) is forced by MDL; |M| is set by transmutation up to
      the unit.

Convention: Euclidean Clifford {g^a,g^b}=+2 delta^{ab}, Hermitian generators (g^a)^dag = g^a.
"""
import numpy as np
from scipy.linalg import expm
import sys
import os
import itertools

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "dirac_srs_mdl"))
import srs  # verified bare geometry

np.set_printoptions(precision=5, suppress=True, linewidth=120)

I2 = np.eye(2)
s1 = np.array([[0, 1], [1, 0]], complex)
s2 = np.array([[0, -1j], [1j, 0]], complex)
s3 = np.array([[1, 0], [0, -1]], complex)
kron = np.kron


def comm(A, B):
    return A @ B - B @ A


def acomm(A, B):
    return A @ B + B @ A


def is0(M):
    return np.allclose(M, 0, atol=1e-10)


# The forced Cl(4) spinor (m06): g1,g2,g3 = spatial; g4 = the forced 4th generator = the gap term.
g = [kron(s1, s1), kron(s1, s2), kron(s1, s3), kron(s2, I2)]
gc = g[0] @ g[1] @ g[2] @ g[3]                      # chirality / volume element

print("=" * 96)
print(" THE FORCED SYMMETRY-BREAKING / VACUUM ARCHITECTURE OF THE srs DIRAC OPERATOR  (m07, walled)")
print("=" * 96)

# =====================================================================================
# PART (1) — THE SCALAR (HIGGS-ANALOG) SECTOR = INNER FLUCTUATION IN THE FINITE DIRECTION.
# =====================================================================================
print("\n" + "#" * 96)
print("# PART (1)  The scalar sector = the connection along the discrete srs<->srs-z direction")
print("#" * 96)

print("""
[1.0] THE SCALAR IS THE INNER FLUCTUATION OF D IN THE FINITE DIRECTION.
   In a spectral triple, gauge/scalar fields are the inner fluctuations D -> D + A,
   A = sum a_i [D, b_i], a_i,b_i in the algebra.  Along the CONTINUOUS (srs) directions this is the
   gauge connection; along the FINITE/internal (enantiomer) direction it is a SCALAR (Higgs-analog):
   the part of D that connects the two sheets srs and srs-z.  We ask what scalar structure is FORCED.""")

# (1a) The order-parameter space = Hermitian operators that anticommute with the 3 spatial Dirac
#      terms (a genuine gap: D = sum g^a p_a + Phi, D^2 = (sum p_a^2) + Phi^2 with no cross terms).
basis16 = [kron(a, b) for a in [I2, s1, s2, s3] for b in [I2, s1, s2, s3]]
cols = []
for B in basis16:
    v = np.concatenate([acomm(B, g[a]).flatten() for a in range(3)])
    cols.append(np.concatenate([v.real, v.imag]))
Cm = np.array(cols).T
u_, sv, vt = np.linalg.svd(Cm)
nb = vt[np.sum(sv > 1e-9):]                          # nullspace = the gap-direction space
gapops = [sum(nb[r, i] * basis16[i] for i in range(16)) for r in range(nb.shape[0])]
print(f"""
[1.1] THE ORDER-PARAMETER SPACE IS EXACTLY 2-DIMENSIONAL = span{{gamma^4, gamma_c}}.
   dim{{ Phi : {{Phi, g^a}} = 0 for a=1,2,3 }} = {nb.shape[0]}.
   A basis is {{gamma^4, gamma_c}} (gamma_c = g^1 g^2 g^3 g^4, the volume element):
     gamma^4 anticommutes with g^1,g^2,g^3 ?  {all(is0(acomm(g[3], g[a])) for a in range(3))}
     gamma_c anticommutes with g^1,g^2,g^3 ?  {all(is0(acomm(gc, g[a])) for a in range(3))}
     gamma^4, gamma_c anticommute with each other ?  {is0(acomm(g[3], gc))}
   So the most general gap term is  Phi = m4 gamma^4 + m5 gamma_c  ==  a SINGLE COMPLEX scalar
   M := m4 + i m5,  with |M|^2 = m4^2 + m5^2 the gap and arg(M) a phase.   [FORCED]""")

# (1b) verify Phi^2 = |M|^2 I (a true, isotropic gap)
m4, m5 = 0.7, 0.4
D = 0.3 * g[0] - 0.5 * g[1] + 0.9 * g[2] + m4 * g[3] + m5 * gc
gap2 = 0.3**2 + 0.5**2 + 0.9**2 + m4**2 + m5**2
print(f"""[1.2] THE GAP IS |M| (ISOTROPIC).   For D = sum g^a p_a + m4 gamma^4 + m5 gamma_c:
   D^2 = (sum p_a^2 + m4^2 + m5^2) I ?  {np.allclose(D @ D, gap2 * np.eye(4))}
   => the spectral gap is |M| = sqrt(m4^2 + m5^2); the phase arg(M) does not change the gap.   [FORCED]""")

# (1c) the scalar is genuinely the OFF-DIAGONAL (inter-sheet) connection in the chirality basis
w_, V = np.linalg.eigh(gc)


def inbasis(Mx):
    return np.round(np.abs(V.conj().T @ Mx @ V), 6)


g4c = inbasis(g[3])
offdiag = np.allclose(g4c[:2, :2], 0) and np.allclose(g4c[2:, 2:], 0)
print(f"""[1.3] THE SCALAR IS THE INTER-SHEET CONNECTION.   In the chirality eigenbasis (the two halves =
   srs and srs-z), the order parameter is purely OFF-DIAGONAL (maps srs <-> srs-z) ?  {offdiag}.
   So M is literally the Higgs-analog: the connection D_F along the discrete enantiomer direction,
   a complex scalar whose vacuum value gaps the spectrum.   [FORCED]""")

print("""
[1.4] FORCED SCALAR STRUCTURE (summary of Part 1):
   The scalar (Higgs-analog) sector forced by srs is exactly ONE COMPLEX SCALAR M = m e^{i phi},
   = the inner fluctuation of D along the finite srs<->srs-z direction = the off-diagonal inter-
   enantiomer connection.  |M| = the gap; arg(M) = the chiral/axial phase.  No larger multiplet is
   forced (the order-parameter space is rigidly 2-real-dimensional = 1 complex).   [FORCED]""")

# =====================================================================================
# PART (2) — THE VACUUM / BREAKING PATTERN, AND HOW MDL SELECTS IT.
# =====================================================================================
print("\n" + "#" * 96)
print("# PART (2)  The breaking pattern  U(1)_V x U(1)_A -> U(1)_V,  and MDL forces the vacuum")
print("#" * 96)

# (2a) the continuous symmetry of the MASSLESS doubled Dirac.
cols = []
for B in basis16:
    v = np.concatenate([comm(B, g[a]).flatten() for a in range(3)])
    cols.append(np.concatenate([v.real, v.imag]))
Cm = np.array(cols).T
u_, sv, vt = np.linalg.svd(Cm)
ncomm = np.sum(sv < 1e-9)
G_A = 0.5j * g[3] @ gc                               # the axial generator (rotates the M-plane)
print(f"""
[2.1] THE MASSLESS DOUBLED DIRAC HAS A CONTINUOUS CHIRAL SYMMETRY  U(1)_V x U(1)_A.
   The continuous symmetries of the gapless theory D0 = sum_{{a=1,2,3}} g^a p_a are the Hermitian X
   with [X, g^a] = 0 for a=1,2,3.   complex dim{{ X : [X,g^a]=0 }} = {ncomm}.
   A basis is {{ I , G_A }} with  G_A := (i/2) gamma^4 gamma_c:
     [I, g^a] = 0 (the VECTOR U(1)_V — common phase of both sheets);
     [G_A, g^a] = 0 for a=1,2,3 ?  {all(is0(comm(G_A, g[a])) for a in range(3))}  (the AXIAL U(1)_A).
   G_A generates rotations IN the order-parameter plane span{{gamma^4, gamma_c}} (it is the only
   symmetry generator that moves M); G_A^2 = (1/4) I so e^{{i a G_A}} is a genuine U(1).  The massless
   symmetry acting on the order parameter is U(1)_V x U(1)_A.   [FORCED]
   (Note gamma_c itself ANTI-commutes with all 3 spatial generators, so it is a GAP DIRECTION, not a
    symmetry generator — the axial charge is carried by G_A = (i/2) gamma^4 gamma_c.)""")

# (2b) the gap breaks U(1)_A, preserves U(1)_V.
print(f"""[2.2] THE GAP BREAKS THE AXIAL U(1), PRESERVES THE VECTOR U(1).
   gamma^4 (the gap term) commutes with I (vector) ?  {is0(comm(g[3], np.eye(4)))}  -> U(1)_V UNBROKEN.
   [G_A, gamma^4] = 0 ?  {is0(comm(G_A, g[3]))}  -> gamma^4 is NOT G_A-invariant -> U(1)_A BROKEN.
   The axial rotation moves the order parameter:  e^{{i a G_A}} gamma^4 e^{{-i a G_A}}
   = cos(a) gamma^4 + sin(a) gamma_c,  i.e. it rotates arg(M) by a.   So M != 0 SPONTANEOUSLY breaks
   U(1)_A, and arg(M) is the would-be Goldstone direction.   PATTERN:  U(1)_V x U(1)_A -> U(1)_V.   [FORCED]""")
a = 0.7
Ua = expm(1j * a * G_A)                              # e^{i a G_A}, a genuine U(1)_A element
print(f"   check axial rotation: e^(i a G_A) gamma^4 e^(-i a G_A) = cos a gamma^4 + sin a gamma_c ?  "
      f"{np.allclose(Ua @ g[3] @ Ua.conj().T, np.cos(a) * g[3] + np.sin(a) * gc)}")

# (2c) MDL forces the vacuum to a crystallographic registration -- NOT a continuous angle.
print("""
[2.3] MDL FORCES A CRYSTALLOGRAPHIC VACUUM, NOT A CONTINUOUS ANGLE.
   The phase arg(M) is the relative orientation of srs-z to srs.  Both nets live in the SAME deck
   lattice Z^3 (srs-z = the mirror/inversion image of srs; A_srsz(k) = conj A_srs(k) = A_srs(-k)).
   The relative orientation that is COMMENSURATE with the shared lattice is constrained by lattice
   symmetry: the orthogonal maps preserving Z^3 form the FINITE cubic point group O_h (order 48),
   NOT a continuous U(1).  So the srs<->srs-z registration is crystallographically QUANTIZED.""")
print(f"   srs-z = conj(srs net) = A(-k) (the enantiomer/time-reversal) ? "
      f"{np.allclose(np.conj(srs.adjacency([0.13, 0.27, 0.41])), srs.adjacency([-0.13, -0.27, -0.41]))}")
# build O_h and count
perms = [np.array([[1 if p[i] == j else 0 for j in range(3)] for i in range(3)])
         for p in itertools.permutations(range(3))]
signs = [np.diag([a, b, c]) for a in (1, -1) for b in (1, -1) for c in (1, -1)]
Oh = {tuple((P @ S).astype(int).flatten()) for P in perms for S in signs}
proper = [M for M in Oh if round(np.linalg.det(np.array(M).reshape(3, 3))) == 1]
improper = [M for M in Oh if round(np.linalg.det(np.array(M).reshape(3, 3))) == -1]
print(f"   |O_h| = {len(Oh)} (FINITE) = {len(proper)} rotations + {len(improper)} orientation-reversing.")
# the canonical (central) orientation-reversing map = inversion -I
central = [M for M in improper
           if all(np.allclose(np.array(M).reshape(3, 3) @ np.array(N).reshape(3, 3),
                              np.array(N).reshape(3, 3) @ np.array(M).reshape(3, 3)) for N in proper)]
print(f"   orientation-reversing maps commuting with ALL rotations (canonical / shortest-description):")
print(f"     {[np.array(M).reshape(3, 3).tolist() for M in central]}  = the INVERSION -I, UNIQUE.")
print("""   MDL (the Kotani-Sunada standard realization = harmonic-energy minimization) places BOTH nets
   at the unique harmonic minimizer; the only residual freedom is a lattice isometry (the finite O_h).
   Among orientation-reversing isometries the inversion -I is the unique one commuting with the whole
   rotation group A_4 (the shortest / most symmetric description).  MDL SELECTS IT.   [FORCED]""")

# (2d) the canonical vacuum (inversion) PINS the phase: phi in {0, pi}, a definite value.
print("""
[2.4] THE FORCED VACUUM PINS THE PHASE  (the breaking is DETERMINED, not a free knob).
   The inversion P: x -> -x sends p -> -p, so the spatial Dirac sum g^a p_a -> -sum g^a p_a.  The
   unitary implementing P on Cl(4) flips the spatial generators and fixes the gap direction:""")
for name, UP in [("gamma^4", g[3]), ("gamma_c", gc), ("g1 g2 g3", g[0] @ g[1] @ g[2])]:
    flips = all(np.allclose(UP @ g[a] @ np.linalg.inv(UP), -g[a]) for a in range(3))
    fixes = np.allclose(UP @ g[3] @ np.linalg.inv(UP), g[3])
    onc = UP @ gc @ np.linalg.inv(UP)
    lab = "+gamma_c" if np.allclose(onc, gc) else ("-gamma_c" if np.allclose(onc, -gc) else "?")
    print(f"   U_P = {name:9s}: flips g^a->-g^a ? {flips};  fixes gamma^4 ? {fixes};  U_P gamma_c U_P^-1 = {lab}")
print("""   => parity is implemented by U_P = gamma^4: it flips the 3 spatial generators, FIXES gamma^4,
   and sends gamma_c -> -gamma_c.  Hence on the order parameter  M = m4 gamma^4 + m5 gamma_c:
       gamma^4 -> +gamma^4,  gamma_c -> -gamma_c,   i.e.   M = m e^{i phi}  ->  m e^{-i phi}.
   Invariance under the FORCED vacuum map (the inversion) requires  phi = -phi  (mod 2pi),  so
       phi in {0, pi}   (a definite, quantized value — the P-even / P-odd mass).
   The continuous would-be-Goldstone direction is COLLAPSED to a discrete choice by the crystallo-
   graphic vacuum: arg(M) is NOT a free dial.  The vacuum is DETERMINED.   [FORCED]""")

# =====================================================================================
# PART (3) — THE GAP MAGNITUDE: DIMENSIONAL TRANSMUTATION (mechanism FORCED, scale = the unit).
# =====================================================================================
print("\n" + "#" * 96)
print("# PART (3)  The gap MAGNITUDE |M|: dimensional transmutation (the wall makes its own scale)")
print("#" * 96)

# Reproduce the i01 transmutation, framed as: |M| = the magnitude of the order parameter.
N = 22
idx = (np.arange(N) + 0.5) / N
eps = np.concatenate([np.linalg.eigvalsh(srs.adjacency((a, b, c))) for a in idx for b in idx for c in idx])
eps = eps - np.mean(eps)
W = eps.max() - eps.min()
hist, edges = np.histogram(eps, bins=400, density=True)
ec = 0.5 * (edges[:-1] + edges[1:])
de = edges[1] - edges[0]
N0 = hist[np.argmin(np.abs(ec))]
Ifun = lambda m: float(np.sum(hist * de * 0.5 / np.sqrt(ec**2 + m**2)))


def solve_gap(gc_):
    if gc_ * Ifun(1e-11) < 1.0:
        return 0.0
    lo, hi = 1e-12, 8.0
    for _ in range(300):
        mid = np.sqrt(lo * hi)
        lo, hi = (mid, hi) if gc_ * Ifun(mid) > 1.0 else (lo, mid)
    return np.sqrt(lo * hi)


print(f"""
[3.1] |M| IS GENERATED BY DIMENSIONAL TRANSMUTATION (the gap equation, ../interaction/i01).
   An attractive inter-enantiomer interaction (the only channel: the gap term is the inter-sheet
   coupling) + mean field gives the self-consistent gap equation 1 = g I(|M|), I from the srs band
   DOS (bandwidth W = {W:.3f}, DOS at band center N0 = {N0:.4f}).  Solving it:""")
gs = np.array([1.3, 1.7, 2.2, 3.0])
ms = np.array([solve_gap(gv) for gv in gs])
print("     g       |M|/W        W e^(-1/(g N0))")
for gv, m in zip(gs, ms):
    print(f"     {gv:.2f}    {m / W:.3e}    {W * np.exp(-1.0 / (gv * N0)):.3e}")
msk = ms > 0
slope, intercept = np.polyfit(-1.0 / gs[msk], np.log(ms[msk] / W), 1)
pr = slope * (-1.0 / gs[msk]) + intercept
r2 = 1 - np.sum((np.log(ms[msk] / W) - pr)**2) / np.sum((np.log(ms[msk] / W) - np.mean(np.log(ms[msk] / W)))**2)
print(f"   fit ln(|M|/W) = {slope:.3f}(-1/g) + {intercept:.3f}, R^2 = {r2:.4f}  =>  |M| ~ W e^(-1/(g N0)).")
print("""   The MECHANISM (dynamical |M| from a marginal coupling) and the GEOMETRIC inputs (W, N0 — both
   read off the srs band) are FORCED.  The free input is the OVERALL UNIT (the ruler): in pure math
   there are no units, only the dimensionless ratio |M|/W; the wall fixes the ratio (given g) but not
   the absolute scale.   |M|: mechanism + ratio FORCED;  absolute scale = IRREDUCIBLE-INPUT (the unit).""")

# =====================================================================================
# MASTER SUMMARY
# =====================================================================================
print("\n" + "=" * 96)
print(" MASTER SUMMARY — the forced symmetry-breaking / vacuum architecture")
print("=" * 96)
print("""
 (1) SCALAR SECTOR (Higgs-analog) = inner fluctuation of D along the finite srs<->srs-z direction.
     FORCED: a SINGLE COMPLEX scalar M = m e^{i phi}; its space is rigidly 2-real-dim = span{gamma^4,
     gamma_c} (1 complex); |M| = the gap, arg(M) = the chiral/axial phase = srs-z<->srs orientation;
     M is the off-diagonal inter-enantiomer connection.   [FORCED]
 (2) BREAKING PATTERN.  The massless doubled Dirac has U(1)_V x U(1)_A (commutant of the spatial
     generators = {I, G_A}, G_A = (i/2) gamma^4 gamma_c the axial charge).
     The gap (M != 0) spontaneously breaks U(1)_A -> nothing, preserving U(1)_V:
         U(1)_V x U(1)_A  --(M)-->  U(1)_V.                                            [FORCED]
     VACUUM SELECTION (MDL).  arg(M) is NOT a continuous free angle: both nets share the deck Z^3,
     so the relative orientation is crystallographically QUANTIZED (finite O_h, |O_h|=48, not U(1));
     the Kotani-Sunada standard realization (harmonic-energy = MDL) places both at the unique
     minimizer; the canonical orientation-reversing isometry is the INVERSION -I (unique central one);
     and the inversion PINS arg(M) to {0, pi}.  The breaking is DETERMINED, not a knob.   [FORCED]
 (3) GAP MAGNITUDE.  |M| is generated by dimensional transmutation |M| ~ W e^(-1/(g N0)) (the gap
     equation over the srs band DOS).  Mechanism + geometric inputs (W, N0) + the ratio |M|/W FORCED;
     the absolute scale is the one IRREDUCIBLE-INPUT (the unit/ruler).
 ONE PICTURE: the spectral gap is a complex order parameter M = m e^{i phi}; |M| is set by
     transmutation (up to the unit), arg(M) is forced to a crystallographic value by the MDL vacuum
     (the inversion registration of srs-z on srs).  The breaking U(1)_A -> 1 is forced; the vacuum is
     forced; only the absolute scale is an irreducible unit.  NO continuous free breaking angle.
""")
print("[m07 done]")
