#!/usr/bin/env python3
"""
proofs/foundations/alpha2triplprime_PIVOT_intravertex_matrix_elements_2026-05-15.py

α2'''-PIVOT — Walker-level substrate Δρ via intra-vertex Cl(6) Fock matrix
elements.

CONTEXT (post-Phase-A.2-closed-negative)

Phase A.2 (commit 0e45941, 2026-05-15 EOD+11) closed the per-atom Bloch
species filter mechanism: the 4 srs atoms carry IDENTICAL Cl(6) Fock
content; species labels live in the per-vertex Fock factor (different
tensor factor than the velocity vertex).  ‖[v^μ, P_n^Fock]‖ = 0 trivially.

This pivot tests a STRUCTURALLY DISTINCT mechanism: substrate gauge
currents J_Z and J_W as operators on the per-vertex 8-dim Cl(6) Fock,
with matrix elements between Hamming-weight sectors.

  J_Z^μ (flavor-conserving): T_3^L Cartan diagonal in Hamming sectors
  J_W^μ (flavor-changing):   T_±^L raising/lowering between sectors

If structural matrix elements obey the SM tree custodial relation
m_W²/M_Z² = cos²θ_W (i.e., ρ_substrate = 1 at tree level), close
NEGATIVE per pre-declared abort (P.1).  If they differ at K-rational
form matching δρ_emp ≈ 1.05% within sub-percent, POSITIVE.

KEY STRUCTURAL INPUTS (existing, no adoption):

(I1) Per-vertex Cl(6) Fock = Λ^•(C^3), 8-dim, Hamming weights {0,1,2,3}
     ↔ {ν_L, d-quark colors, ū_R-bar colors, e+_L} (Furey 2018 +
     `theorem_charge_before_color.md` §9).

(I2) SU(2)_L = Spin(3) ⊂ Spin(6) per B3, generated by M_{12}, M_{13},
     M_{23} = (1/(2i))Γ_aΓ_b.  Cartan T_3^L = M_{12};
     T_±^L = M_{23} ∓ i M_{13} per the [M_ab, M_cd] = i(δ_ac M_bd - ...)
     algebra.  (an internal note).

(I3) SU(4)_PS Cartan triple {T_1=M_{12}, T_2=M_{34}, Y=M_{56}} per
     R1.1 part B.  Hypercharge Y_PS = M_{56}.

(I4) Hamming weight n = N_op = Σ a_dag_i a_i = (3/2)·I − (M_{12} + M_{34}
     + M_{56}) = (3/2)I − T_1 − T_2 − Y, derived from a_dag_i =
     (Γ_{2i-1} − iΓ_{2i})/2.

PROBE STRUCTURE

T1: Build Cl(6) Brauer-Weyl + bivectors (re-use R1.1 construction).
T2: Identify SU(2)_L generators (M_{12}, M_{13}, M_{23}) and verify
    Spin(3) algebra [T_a, T_b] = iε_{abc}T_c.
T3: Build Hamming-weight projectors P_n; identify SU(2)_L doublets
    in Cl(6) Fock (subspaces with definite N=n_doublet, T_3=±1/2).
T4: Compute structural matrix-element sums:
      Π_Z(N=n) := Σ_{ψ ∈ Λ^n} |⟨ψ|T_3^L|ψ⟩|²        [Z, flavor-cons]
      Π_W(N=n) := Σ_{ψ ∈ Λ^n, ψ' ∈ Λ^{n±k}} |⟨ψ|T_+^L|ψ'⟩|²  [W flavor-change]
T5: Compute substrate ρ_substrate from full traces:
      ρ_substrate = Π_W / Π_Z  (modulo sin²θ_W mixing factor)
T6: Check whether ρ_substrate matches SM tree-level (ρ=1 modulo charge
    factors) or gives Δρ ≠ 0 structural prediction.
T7: K-rationality check on Δρ_substrate.
T8: Magnitude vs δρ_emp ≈ 1.05% per pre-declared abort criteria.

PRE-DECLARED ABORT (per an internal working note
closed_negative_2026-05-15.md §6):
  (P.1) SM tree-level structural relation Δρ_substrate = 0 → close NEG
  (P.2) Δρ ≠ 0 but off by order-of-magnitude vs δρ_emp ≈ 1.05% → close NEG
  (P.3) K-rational form matches δρ_emp within sub-percent → POSITIVE
"""
from __future__ import annotations
import os
import sys
from itertools import combinations, product
from fractions import Fraction

import numpy as np

K_STAR = 3
DIM_FOCK = 2 ** K_STAR
TOL = 1e-12

# Empirical anchors (PDG 2024)
M_Z_PDG = 91.1876
m_W_PDG = 80.3692
COS2_THETA_W_PDG = (m_W_PDG / M_Z_PDG) ** 2  # ≈ 0.7770 (on-shell scheme)
SIN2_THETA_W_MZ = 0.23122  # MS-bar at M_Z, PDG 2024

# Empirical δρ
RHO_EMP = (m_W_PDG ** 2) / ((M_Z_PDG ** 2) * COS2_THETA_W_PDG)
# RHO_EMP = 1 by construction in on-shell scheme; the relevant quantity is
# δρ_T (oblique-T-parameter convention) which is ~1.05% based on radiative
# corrections on top of tree-level ρ=1.

# Standard SM δρ_T from oblique T-parameter (LEP electroweak fit):
DELTA_RHO_T_PDG = 0.00038  # PDG 2024 (T = 0.03 ± 0.12 ⇒ α·T ≈ 2.2e-4)
# Per scoping doc we used δρ ≈ 1.05% as the rough target — this is the
# NLO-level top-quark-induced custodial breaking magnitude.
DELTA_RHO_TOP_NLO = 3 * (172.69 / (4 * np.pi * 246.22)) ** 2  # ≈ 9.4e-3 ≈ 0.94%


def kron(*mats):
    out = mats[0]
    for m in mats[1:]:
        out = np.kron(out, m)
    return out


I2 = np.eye(2, dtype=complex)
SX = np.array([[0, 1], [1, 0]], dtype=complex)
SY = np.array([[0, -1j], [1j, 0]], dtype=complex)
SZ = np.array([[1, 0], [0, -1]], dtype=complex)


def build_gamma():
    """Cl(6,0) Brauer-Weyl on ℂ^8 (same as R1.1 / theorem_B3_spinor_fermion.py)."""
    G = [None] * 7  # 1-indexed
    G[1] = kron(SX, I2, I2)
    G[2] = kron(SY, I2, I2)
    G[3] = kron(SZ, SX, I2)
    G[4] = kron(SZ, SY, I2)
    G[5] = kron(SZ, SZ, SX)
    G[6] = kron(SZ, SZ, SY)
    return G


def bivector(G, a, b):
    """M_{ab} = (1/(2i)) Γ_a Γ_b for a ≠ b."""
    return (G[a] @ G[b] - G[b] @ G[a]) / (4j)


print("=" * 78)
print("  α2'''-PIVOT — Intra-vertex Cl(6) Fock matrix elements for substrate Δρ")
print("=" * 78)
print()


# -----------------------------------------------------------------------------
# T1: Build Cl(6) + bivectors
# -----------------------------------------------------------------------------
print("=" * 78)
print("T1: Cl(6,0) Brauer-Weyl + Spin(6) bivectors")
print("=" * 78)
G = build_gamma()
# Verify Clifford
for a, b in product(range(1, 7), repeat=2):
    lhs = G[a] @ G[b] + G[b] @ G[a]
    rhs = 2 * (1 if a == b else 0) * np.eye(8, dtype=complex)
    assert np.allclose(lhs, rhs, atol=TOL), f"Cl(6) anticomm fail at {a},{b}"
print("  Cl(6) anticommutation {Γ_a, Γ_b} = 2δ_ab : OK")

bivs = {(a, b): bivector(G, a, b) for a in range(1, 7) for b in range(a + 1, 7)}
print(f"  Built 15 Spin(6) bivectors M_{{ab}}.")


# -----------------------------------------------------------------------------
# T2: SU(2)_L generators per B3
# -----------------------------------------------------------------------------
print()
print("=" * 78)
print("T2: SU(2)_L = Spin(3) ⊂ Spin(6) generators per B3")
print("=" * 78)
print("  T_3^L = M_{12},  T_-^L candidates = M_{13}, M_{23}")
print()
T3L = bivs[(1, 2)]
M13 = bivs[(1, 3)]
M23 = bivs[(2, 3)]

# Check Spin(3) algebra: [M_12, M_13] = +i M_23, [M_12, M_23] = -i M_13, etc.
def comm(A, B):
    return A @ B - B @ A


def near(A, B, atol=TOL):
    return np.allclose(A, B, atol=atol)

print(f"  [M_12, M_13] − i·M_23 :  ‖.‖ = {np.max(np.abs(comm(T3L, M13) - 1j * M23)):.2e}  (expect 0)")
print(f"  [M_12, M_23] + i·M_13 :  ‖.‖ = {np.max(np.abs(comm(T3L, M23) + 1j * M13)):.2e}  (expect 0)")
print(f"  [M_13, M_23] − i·M_12 :  ‖.‖ = {np.max(np.abs(comm(M13, M23) - 1j * T3L)):.2e}  (expect 0)")

# Standard SU(2) basis: T_a obeying [T_a, T_b] = iε_{abc} T_c
T1L = M23  # by the algebra above
T2L = -M13
print()
print("  SU(2)_L basis T_a = (M_23, -M_13, M_12) with [T_a, T_b] = iε_{abc}T_c")

# Raising/lowering: T_± = T_1 ± i T_2 = M_23 ∓ i M_13
T_plus = T1L + 1j * T2L  # = M_23 - i M_13
T_minus = T1L - 1j * T2L  # = M_23 + i M_13

# Sanity: [T_3, T_+] = +T_+, [T_3, T_-] = -T_-
print(f"  [T_3, T_+] − T_+ :  ‖.‖ = {np.max(np.abs(comm(T3L, T_plus) - T_plus)):.2e}  (expect 0)")
print(f"  [T_3, T_-] + T_- :  ‖.‖ = {np.max(np.abs(comm(T3L, T_minus) + T_minus)):.2e}  (expect 0)")


# -----------------------------------------------------------------------------
# T3: Hamming-weight projectors and SU(2)_L doublet identification
# -----------------------------------------------------------------------------
print()
print("=" * 78)
print("T3: Hamming-weight projectors P_n + SU(2)_L doublet structure in Λ^•(C^3)")
print("=" * 78)


def hamming_weight_projector(n: int) -> np.ndarray:
    P = np.zeros((DIM_FOCK, DIM_FOCK), dtype=complex)
    for s in range(DIM_FOCK):
        bits = [(s >> j) & 1 for j in range(K_STAR)]
        if sum(bits) == n:
            P[s, s] = 1.0
    return P


P_per_n = {n: hamming_weight_projector(n) for n in range(K_STAR + 1)}

# T_3^L eigenvalues per Hamming sector
print(f"\n  T_3^L = M_{{12}} eigenvalues per Hamming sector:")
print(f"  (recall N_1 = a_dag_1 a_1 = 1/2 − M_12, so T_3 acts on mode 1 occupation only)")
print()
for n in range(K_STAR + 1):
    P_n = P_per_n[n]
    # Project T_3 onto Λ^n
    T3_in_n = P_n @ T3L @ P_n
    eigs = np.linalg.eigvalsh(T3_in_n + 1e-15 * np.eye(8))
    # Only keep eigenvalues in the support of P_n
    relevant = sorted([round(np.real(e), 6) for e in eigs if abs(e) > 1e-9 or np.real(e) == 0])
    n_support = int(round(np.trace(P_n).real))
    relevant_in_support = relevant[-n_support:] if n_support > 0 else []
    print(f"    n={n}, dim={n_support}, T_3 spectrum = "
          f"{relevant_in_support}")

# T_3 has eigenvalues ±1/2 on each subspace where mode 1 is occupied differently.
# In the bit-string basis, |b_1 b_2 b_3⟩, M_12 = (1/2)·diag(... per bit b_1).
# Actually T_3 = M_12 acts only on b_1 occupation (since Γ_1, Γ_2 act on bit 1).
# So T_3 has eigenvalues only ±1/2 (NOT zero), distributed across all 8 states.


# -----------------------------------------------------------------------------
# T4: Structural matrix-element sums over Cl(6) Fock
# -----------------------------------------------------------------------------
print()
print("=" * 78)
print("T4: Structural matrix-element sums Tr[T_3²], Tr[T_+ T_-]")
print("=" * 78)
print()

# Full Cl(6) Fock trace
Tr_T3_sq = np.real(np.trace(T3L @ T3L))
Tr_Tplus_Tminus = np.real(np.trace(T_plus @ T_minus))
Tr_Tminus_Tplus = np.real(np.trace(T_minus @ T_plus))
Tr_T_sum = Tr_T3_sq + (Tr_Tplus_Tminus + Tr_Tminus_Tplus) / 2  # Casimir T(T+1)

print(f"  Full Cl(6) Fock (8-dim):")
print(f"    Tr[T_3²]            = {Tr_T3_sq:.6f}")
print(f"    Tr[T_+ T_-]         = {Tr_Tplus_Tminus:.6f}")
print(f"    Tr[T_- T_+]         = {Tr_Tminus_Tplus:.6f}")
print(f"    Tr[T²] (Casimir sum)= {Tr_T_sum:.6f}")
print()

# Per Hamming sector
print(f"  Per Hamming-weight sector:")
print(f"  {'n':>3}  {'dim':>3}  {'Tr[T_3²]':>12}  {'Tr[T_+T_-]':>12}  {'Tr[T_-T_+]':>12}  {'sum':>12}")
sector_Z_W = {}
for n in range(K_STAR + 1):
    P_n = P_per_n[n]
    dim_n = int(round(np.trace(P_n).real))
    # Z-like trace: Tr[P_n T_3 P_n T_3] -- diagonal block
    z_sum = np.real(np.trace(P_n @ T3L @ P_n @ T3L))
    # W-like traces: Tr[P_n T_+ P_? T_-] -- off-diagonal between sectors
    # T_+ raises some quantum number (actually T_+ on Λ^n: need to check what it does)
    # General Tr[T_+ T_-] over full space includes all contributions
    # Per-sector restriction: what does T_+ map P_n into?
    Tplus_Pn = T_plus @ P_n
    Tminus_Pn = T_minus @ P_n
    w_plus_sum = np.real(np.trace(Tplus_Pn.conj().T @ Tplus_Pn))  # |T_+ |P_n||²
    w_minus_sum = np.real(np.trace(Tminus_Pn.conj().T @ Tminus_Pn))  # |T_- |P_n||²
    print(f"  {n:>3}  {dim_n:>3}  {z_sum:>+12.6f}  {w_plus_sum:>+12.6f}  {w_minus_sum:>+12.6f}  "
          f"{z_sum + (w_plus_sum + w_minus_sum) / 2:>+12.6f}")
    sector_Z_W[n] = (dim_n, z_sum, w_plus_sum, w_minus_sum)

# Identify what Hamming sector T_+ maps to
print()
print(f"  T_+ |P_n⟩ → which sectors? (overlap with each P_m)")
print(f"  {'n':>3}  ", "  ".join(f"P_{m} overlap" for m in range(K_STAR + 1)))
for n in range(K_STAR + 1):
    P_n = P_per_n[n]
    Tplus_Pn = T_plus @ P_n
    overlaps = []
    for m in range(K_STAR + 1):
        P_m = P_per_n[m]
        overlap = np.real(np.trace(Tplus_Pn.conj().T @ P_m @ Tplus_Pn))
        overlaps.append(f"{overlap:+.4f}")
    print(f"  {n:>3}    " + "  ".join(f"{o:>11}" for o in overlaps))


# -----------------------------------------------------------------------------
# T5: Substrate ρ_substrate from sum
# -----------------------------------------------------------------------------
print()
print("=" * 78)
print("T5: Substrate gauge structure factor ratio")
print("=" * 78)
print()

# In SM, per SU(2)_L doublet:
#   Π_Z|isospin = Σ T_3² × g²/cos²θ × (kinetic factor)
#   Π_W = Σ T_+ T_- / 2 × g² × (kinetic factor)
#   ρ = (Π_W / cos²θ) / Π_Z = (Σ T_+ T_-) / (2 Σ T_3²) × cos²θ / cos²θ
#   per doublet: Σ T_+ T_- = 1, Σ T_3² = 1/2 → ρ = 1
#
# Cl(6) Fock substrate analog:
#   ρ_substrate = Tr[T_+ T_-] / (2 × Tr[T_3²])

ratio_substrate = Tr_Tplus_Tminus / (2 * Tr_T3_sq)
print(f"  Full-Fock substrate ratio:")
print(f"    Tr[T_+ T_-] / (2 × Tr[T_3²]) = {Tr_Tplus_Tminus:.4f} / "
      f"(2 × {Tr_T3_sq:.4f}) = {ratio_substrate:.6f}")
print()
print(f"  SM custodial expectation (per doublet): 1.000000")
print(f"  Substrate value:                        {ratio_substrate:.6f}")
print()
delta_rho_substrate = ratio_substrate - 1.0
print(f"  Δρ_substrate = ratio - 1 = {delta_rho_substrate:+.6f} = {delta_rho_substrate * 100:+.4f}%")


# -----------------------------------------------------------------------------
# T6: Verification — does the substrate match SM tree-level?
# -----------------------------------------------------------------------------
print()
print("=" * 78)
print("T6: Comparison to SM tree-level custodial relation")
print("=" * 78)
print()
print("  In SM: each SU(2)_L doublet contributes ρ = 1 exactly (custodial).")
print("  Multiple doublets stack additively in self-energy; custodial preserved.")
print()
print("  Cl(6) Fock contains how many SU(2)_L doublets?")
print()

# Count SU(2)_L doublets via Casimir T² eigenvalues
T_sq = T1L @ T1L + T2L @ T2L + T3L @ T3L
eigs_T_sq = np.linalg.eigvalsh(T_sq)
print(f"  T² eigenvalues on Cl(6) Fock: {sorted([round(np.real(e), 4) for e in eigs_T_sq])}")
print(f"  Expected for j=1/2 (doublet): T² = 3/4")
print(f"  Expected for j=0 (singlet):   T² = 0")
print(f"  Expected for j=1 (triplet):   T² = 2")
print()

# Tally
casimir_count = {}
for e in eigs_T_sq:
    key = round(np.real(e), 4)
    casimir_count[key] = casimir_count.get(key, 0) + 1
for j_sq, count in sorted(casimir_count.items()):
    print(f"    T² = {j_sq:.4f}: {count} states")

# n_doublets = #(states with T² = 3/4) / 2
n_doublets = casimir_count.get(0.75, 0) // 2
n_singlets = casimir_count.get(0.0, 0)
n_triplets = casimir_count.get(2.0, 0) // 3
print()
print(f"  → SU(2)_L decomposition: {n_doublets} doublet(s) + {n_singlets} singlet(s) + "
      f"{n_triplets} triplet(s)")
print(f"  → Total state count: {2 * n_doublets + n_singlets + 3 * n_triplets} (should be 8) "
      f"{'✓' if 2 * n_doublets + n_singlets + 3 * n_triplets == 8 else '✗'}")


# -----------------------------------------------------------------------------
# T7: K-rationality
# -----------------------------------------------------------------------------
print()
print("=" * 78)
print("T7: K-rationality check (ratio must be in K = ℚ(√2,√3,√5))")
print("=" * 78)
print()
print(f"  Ratio = {ratio_substrate:.10f}")
# Check against simple rationals
for num, den in [(1, 1), (2, 1), (3, 1), (4, 1), (1, 2), (3, 2), (4, 3), (8, 5)]:
    if abs(ratio_substrate - num/den) < 1e-6:
        print(f"  Matches {num}/{den} = {num/den:.10f}")

# Check K-rational extensions
import math
for k_val, k_name in [(math.sqrt(2), "√2"), (math.sqrt(3), "√3"), (math.sqrt(5), "√5")]:
    for num in [1, 2, 3, 4]:
        for den in [1, 2, 3, 4]:
            test = num * k_val / den
            if abs(ratio_substrate - test) < 1e-6:
                print(f"  Matches {num}{k_name}/{den} = {test:.10f}")


# -----------------------------------------------------------------------------
# T8: Magnitude vs δρ_emp
# -----------------------------------------------------------------------------
print()
print("=" * 78)
print("T8: Magnitude check vs empirical δρ ≈ 1%")
print("=" * 78)
print()
print(f"  Empirical δρ-T (oblique-T):              ≈ 0.038%  (PDG fit, T = 0.03 ± 0.12)")
print(f"  Empirical δρ from top-quark NLO:          ≈ 0.94%   (3 m_t² / 16π² v²)")
print(f"  Empirical δρ from M_Z/m_W deviations:     ≈ 1.05%   (sum of |δM_Z| + |δm_W|)")
print()
print(f"  Substrate Δρ from intra-vertex Cl(6) Fock:  {delta_rho_substrate * 100:+.4f}%")
print()

# Verdict
target_emp = 0.0105  # rough δρ target per scoping
deviation = abs(delta_rho_substrate - target_emp) / target_emp if target_emp > 0 else float('inf')
matches_within_subpercent = abs(delta_rho_substrate * 100 - 1.05) < 0.5  # ±0.5% absolute = sub-percent

print(f"  Pre-declared abort criteria:")
print(f"    (P.1) ρ_substrate = 1 exactly (SM tree relation):  "
      f"{'YES — close NEG' if abs(delta_rho_substrate) < 1e-10 else 'NO'}")
print(f"    (P.2) Δρ ≠ 0 but off by order-of-magnitude:         "
      f"{'YES — close NEG' if (not abs(delta_rho_substrate) < 1e-10) and (deviation > 1.0) else 'NO'}")
print(f"    (P.3) K-rational form within sub-percent of 1.05%:  "
      f"{'YES — POSITIVE' if matches_within_subpercent else 'NO'}")


# -----------------------------------------------------------------------------
# Verdict
# -----------------------------------------------------------------------------
print()
print("=" * 78)
print("α2'''-PIVOT verdict")
print("=" * 78)
print()
if abs(delta_rho_substrate) < 1e-10:
    print("OUTCOME: Substrate Cl(6) Fock matrix elements give Δρ = 0 EXACTLY")
    print("         at single-vertex level.  Pre-declared abort (P.1) HITS.")
    print()
    print("INTERPRETATION: The full Cl(6) Fock 8-dim contains a balanced")
    print("                set of SU(2)_L doublets + singlets such that the")
    print("                Casimir relation Tr[T_+T_-] = 2·Tr[T_3²] holds")
    print("                exactly (custodial preserved).")
    print()
    print("                This is structurally analogous to the SM tree-level")
    print("                preservation of ρ = 1 by the Higgs custodial SU(2).")
    print("                Per-vertex Cl(6) Fock walker mechanism cannot")
    print("                generate Δρ ≠ 0 at this structural level.")
    print()
    print("CONCLUSION: α2'''-PIVOT CLOSES NEGATIVE at single-vertex level.")
    print()
    print("REMAINING CANDIDATES for M_Z/m_W cluster Δρ:")
    print("  - α-Path β proper (M_3(ℂ)-level species sectors): 6-12 sessions, high risk")
    print("  - α-Path B (multiway DAG NA-4): 8-16 sessions, high risk")
    print("  - Higgs custodial breaking from ⟨h⟩=(√3+i√5)/2 asymmetry: scoping needed")
elif deviation > 1.0:
    print(f"OUTCOME: Substrate Δρ = {delta_rho_substrate*100:+.4f}%, off by order-of-magnitude")
    print(f"         from empirical ≈ 1.05%.  Pre-declared abort (P.2) HITS.")
    print()
    print("CONCLUSION: α2'''-PIVOT CLOSES NEGATIVE (mechanism captures something")
    print("            else, not Δρ).")
elif matches_within_subpercent:
    print(f"OUTCOME: Substrate Δρ = {delta_rho_substrate*100:+.4f}%, matches empirical")
    print(f"         within sub-percent.  Pre-declared (P.3) POSITIVE.")
    print()
    print("CONCLUSION: α2'''-PIVOT POSITIVE — substrate Cl(6) Fock matrix elements")
    print("            give Δρ structural prediction.  Proceed to elevate")
    print("            M_Z, m_W from STRUCTURAL-DERIVATION-CONDITIONAL.")
else:
    print(f"OUTCOME: Substrate Δρ = {delta_rho_substrate*100:+.4f}% — non-zero but")
    print(f"         doesn't cleanly match (P.1)-(P.3).  Intermediate result —")
    print(f"         needs deeper structural analysis.")

print()
print("=" * 78)
print("End of α2'''-PIVOT probe.")
print("=" * 78)
