#!/usr/bin/env python3
"""
arc_transitivity_ground_truth.py
================================

GROUND-TRUTH arc-orbit calculator for crystal nets — computed from the actual
space-group action, NOT asserted from Sunada.

Motivation
----------
The framework's substrate-selection argument runs:
    (A) no-privilege  ->  "treat all directed edges equivalently"
                      ->  arc-transitive (one directed-edge / arc orbit)
                      ->  (Sunada 2012) unique 3-regular 3D net = srs.

Two distinct properties get conflated in the canon:
  * ARC-TRANSITIVE  : Aut acts transitively on directed edges (arcs).
                      One arc orbit. Local vertex action merely TRANSITIVE
                      on the k incident edges (a k-cycle / C_k suffices).
  * STRONGLY ISOTROPIC (Sunada): for ANY ordering of the edges at x and ANY
                      ordering at y, a congruence maps x->y respecting the
                      orderings. Local vertex action = FULL symmetric group
                      S_k on the k incident edges. STRICTLY STRONGER.

Sunada's uniqueness theorem ("only diamond and srs/K4 are strongly isotropic")
is about the STRONG property. No-privilege only delivers the WEAK property.

The numeric arc-orbit count used in `srs_vs_srs_z_dl_audit.py` is hardcoded
(`srs -> 1, srs-z -> 2`) and justified by *citing Sunada* — circular. This
script computes the arc-orbit count directly from the space group, so the
claim rests on computation.

Method (exact, finite)
-----------------------
A crystal net is a periodic graph. Symmetry = space group G (rotations R_g +
translations t_g, plus all lattice translations). Vertices = a Wyckoff orbit;
edges = nearest-neighbour bonds.

Represent each ARC as (i, j, shift): from unit-cell atom i to atom j in the
cell offset by integer vector `shift`. Its reverse is (j, i, -shift).

A space-group op g acts on atom i (frac coord r_i) by  R_g r_i + t_g = r_{s(i)} + n_i,
with s(i) the image atom index in the home cell and n_i in Z^3. Then
    g : (i, j, shift) -> (s(i), s(j), R_g . shift + n_j - n_i).

Counting:
  * undirected-edge orbits  -> edge-transitive?  (one orbit)
  * directed-arc orbits     -> arc-transitive?   (one orbit)
  * an edge is REVERSIBLE iff some g maps arc (i,j,shift) to (j,i,-shift):
        s(i)=j, s(j)=i, R_g.shift + n_j - n_i = -shift.
    edge-transitive + reversible  <=>  arc-transitive (1 arc orbit).
    edge-transitive + NOT reversible  =>  2 arc orbits (half-arc-transitive).

We also report the LOCAL VERTEX ACTION (the permutation group induced on the
k incident edges by the vertex stabiliser) and whether it is the full S_k
(= Sunada strong isotropy) or only a proper transitive subgroup (e.g. C_k).

No RCSR download needed; Wyckoff coordinates are standard ITA data.
"""

import numpy as np
import spglib
from itertools import product
from collections import defaultdict

TOL = 1e-5


def wrap(frac):
    """Reduce fractional coords into [0,1) and return (wrapped, integer_cell)."""
    cell = np.floor(frac + TOL)
    return (frac - cell) % 1.0, cell.astype(int)


def build_net(name):
    """Return (lattice, positions, numbers, label) for a named net.

    Cubic conventional cell, a=1. Positions = the Wyckoff orbit, generated by
    feeding the single Wyckoff representative to spglib via a refined cell.
    """
    a = 1.0
    lattice = np.eye(3) * a
    if name == 'srs':
        # I4_132 (#214), Wyckoff 8a, x = 1/8.  8 atoms in conventional cell.
        x = 1.0 / 8.0
        base = [
            (x, x, x),
            (x + 0.5, 0.5 - x, -x),
            (-x, x + 0.5, 0.5 - x),
            (0.5 - x, -x, x + 0.5),
        ]
        positions = [np.array(p) % 1.0 for p in base]
        positions += [(p + 0.5) % 1.0 for p in positions]  # body-centering
        hall = None  # let spglib detect
    elif name == 'srs-z':
        # P4_132 (#213), Wyckoff 8c, x = 0.6607.  8 atoms (primitive = conventional).
        x = 0.6607
        # 8c orbit of P4_132 (#213): generated explicitly below from the
        # standard generator list; here we seed and let spglib find the full
        # group + we regenerate the orbit from the detected symmetry.
        positions = [np.array([x, x, x]) % 1.0]
        hall = None
    elif name == 'dia':
        # VALIDATION: diamond, Fd-3m (#227), 8a. Sunada's OTHER strongly
        # isotropic net (4-regular). Must come out strongly isotropic.
        base = [(0, 0, 0), (0.25, 0.25, 0.25)]
        fcc = [(0, 0, 0), (0, 0.5, 0.5), (0.5, 0, 0.5), (0.5, 0.5, 0)]
        positions = [(np.array(b) + np.array(f)) % 1.0 for b in base for f in fcc]
    elif name == 'pcu':
        # VALIDATION: simple cubic, Pm-3m (#221). Arc-transitive, edge-transitive,
        # but NOT strongly isotropic (only dia and srs are). 6-regular.
        positions = [np.array([0.0, 0.0, 0.0])]
    else:
        raise ValueError(name)
    return lattice, [np.asarray(p) for p in positions], name


def ops_from_database(sg_number):
    """Return (rotations, translations, symbol) for the standard setting of an
    international space-group number, taken from spglib's Hall database.

    This avoids the single-atom-seed pitfall (spglib snapping a sparse cell to
    a higher-symmetry group). The ops ARE the space group, by construction.
    """
    for h in range(1, 531):
        t = spglib.get_spacegroup_type(h)
        num = t.number if hasattr(t, 'number') else t['number']
        if num == sg_number:
            sym = spglib.get_symmetry_from_database(h)
            R = sym.rotations if hasattr(sym, 'rotations') else sym['rotations']
            T = sym.translations if hasattr(sym, 'translations') else sym['translations']
            short = t.international_short if hasattr(t, 'international_short') else t['international_short']
            return R, T, short
    raise ValueError(f"no hall number for #{sg_number}")


def orbit_from_ops(rots, trans, seed):
    orbit = []
    for R, t in zip(rots, trans):
        p = (R @ seed + t) % 1.0
        if not any(np.linalg.norm(((p - q + 0.5) % 1.0) - 0.5) < TOL for q in orbit):
            orbit.append(p)
    return orbit


def get_symmetry_and_orbit(lattice, seed_positions, target_count=None):
    """Use spglib to get the space group of the seeded cell, then regenerate
    the FULL Wyckoff orbit by applying all ops to the seed atom(s).

    Returns (rotations, translations, positions, sg_symbol, sg_number).
    """
    numbers = [1] * len(seed_positions)
    cell = (lattice, np.array(seed_positions), numbers)
    dataset = spglib.get_symmetry_dataset(cell, symprec=1e-3)
    rots = dataset.rotations
    trans = dataset.translations
    sg_symbol = dataset.international
    sg_number = dataset.number

    # Regenerate full orbit from the FIRST seed atom under all ops.
    seed = seed_positions[0]
    orbit = orbit_from_ops(rots, trans, seed)
    return rots, trans, orbit, sg_symbol, sg_number


def nearest_neighbor_bonds(lattice, positions, k_expected=3):
    """Find the k nearest neighbours of each atom -> arc list (i, j, shift).

    shift = integer cell offset of the neighbour. Returns the directed arcs
    (both orientations appear since each atom lists its own neighbours).
    """
    n = len(positions)
    P = np.array(positions)
    # Candidate neighbours within +-1 cell.
    cells = list(product([-1, 0, 1], repeat=3))
    dists = []
    for i in range(n):
        for j in range(n):
            for c in cells:
                shift = np.array(c)
                d = np.linalg.norm(lattice @ (P[j] + shift - P[i]))
                if d > TOL:
                    dists.append((d, i, j, tuple(c)))
    dists.sort()
    # Determine the nearest-neighbour distance (smallest), with tolerance.
    d0 = dists[0][0]
    arcs = [(i, j, shift) for (d, i, j, shift) in dists if abs(d - d0) < 1e-3]
    # sanity: each atom should have k_expected outgoing arcs
    deg = defaultdict(int)
    for (i, j, s) in arcs:
        deg[i] += 1
    return arcs, d0, dict(deg)


def op_atom_map(rots, trans, positions):
    """For each op g, compute s_g[i] = image atom index of atom i, and
    n_g[i] = integer cell the image lands in. Returns list of (s, n) per op."""
    n = len(positions)
    P = np.array(positions)
    maps = []
    for R, t in zip(rots, trans):
        s = [-1] * n
        ncell = [None] * n
        for i in range(n):
            img = R @ P[i] + t
            w, cell = wrap(img)
            # find which atom w matches
            for j in range(n):
                if np.linalg.norm(((w - P[j] + 0.5) % 1.0) - 0.5) < TOL:
                    s[i] = j
                    ncell[i] = cell
                    break
            if s[i] == -1:
                # op does not map onto the orbit (shouldn't happen for a real op)
                s = None
                break
        if s is not None:
            maps.append((s, ncell, R))
    return maps


def canon_arc(arc):
    return (arc[0], arc[1], tuple(int(v) for v in arc[2]))


def apply_op_to_arc(arc, smap, ncell, R):
    i, j, shift = arc
    shift = np.array(shift)
    new_i = smap[i]
    new_j = smap[j]
    new_shift = R @ shift + ncell[j] - ncell[i]
    return (new_i, new_j, tuple(int(round(v)) for v in new_shift))


def orbit_count(arc_set, maps, directed=True):
    """Partition arc_set into orbits under the ops in `maps`. If directed=False,
    identify each arc with its reverse first."""
    def key(arc):
        if directed:
            return canon_arc(arc)
        a = canon_arc(arc)
        rev = (a[1], a[0], tuple(-v for v in a[2]))
        return min(a, rev)

    arcs = {key(a) for a in arc_set}
    seen = set()
    n_orbits = 0
    orbit_reps = []
    for a0 in arcs:
        if a0 in seen:
            continue
        n_orbits += 1
        orbit_reps.append(a0)
        # BFS the orbit
        frontier = [a0]
        seen.add(a0)
        while frontier:
            cur = frontier.pop()
            i, j, shift = cur
            for (smap, ncell, R) in maps:
                img = apply_op_to_arc((i, j, shift), smap, ncell, R)
                k = key(img)
                if k not in seen:
                    seen.add(k)
                    frontier.append(k)
    return n_orbits, orbit_reps


def edge_reversible(arcs, maps):
    """Does some op map a representative arc to its exact reverse?"""
    a0 = canon_arc(arcs[0])
    rev0 = (a0[1], a0[0], tuple(-v for v in a0[2]))
    # search the whole orbit of a0 for rev0
    seen = {a0}
    frontier = [a0]
    while frontier:
        cur = frontier.pop()
        for (smap, ncell, R) in maps:
            img = apply_op_to_arc(cur, smap, ncell, R)
            if img == rev0:
                return True
            if img not in seen:
                seen.add(img)
                frontier.append(img)
    return False


def local_vertex_action(arcs, maps, vertex=0):
    """Compute the permutation group induced on the outgoing arcs at `vertex`
    by the ops that fix `vertex` (in the home cell). Report its order and
    whether it is the full S_k."""
    out_arcs = [canon_arc(a) for a in arcs if a[0] == vertex]
    k = len(out_arcs)
    idx = {a: m for m, a in enumerate(out_arcs)}
    perms = set()
    for (smap, ncell, R) in maps:
        # op must fix the vertex in the home cell: s(vertex)=vertex and n=0
        if smap[vertex] != vertex or tuple(int(v) for v in ncell[vertex]) != (0, 0, 0):
            continue
        perm = []
        ok = True
        for a in out_arcs:
            img = apply_op_to_arc(a, smap, ncell, R)
            if img in idx:
                perm.append(idx[img])
            else:
                ok = False
                break
        if ok:
            perms.add(tuple(perm))
    import math
    return k, len(perms), math.factorial(k)


def analyze(name, seed_builder_name):
    print("=" * 78)
    print(f"NET: {name}")
    print("=" * 78)
    lattice, seed_positions, _ = build_net(seed_builder_name)
    if seed_builder_name == 'srs-z':
        # Use the genuine P4_132 (#213) operations from the database; build the
        # 8c orbit from them. (Single-atom spglib detection wrongly snaps to a
        # higher-symmetry cubic lattice.)
        rots, trans, sg_symbol = ops_from_database(213)
        sg_number = 213
        positions = orbit_from_ops(rots, trans, seed_positions[0])
    elif seed_builder_name == 'pcu':
        rots, trans, sg_symbol = ops_from_database(221)
        sg_number = 221
        positions = orbit_from_ops(rots, trans, seed_positions[0])
    else:
        rots, trans, positions, sg_symbol, sg_number = get_symmetry_and_orbit(lattice, seed_positions)
    print(f"  space group (spglib): {sg_symbol}  (#{sg_number})")
    print(f"  symmetry operations: {len(rots)}")
    print(f"  atoms in conventional cell (regenerated orbit): {len(positions)}")

    arcs, d0, deg = nearest_neighbor_bonds(lattice, positions)
    degvals = sorted(set(deg.values()))
    print(f"  nearest-neighbour distance: {d0:.5f}")
    print(f"  coordination (out-degree): {degvals}  (#arcs in cell = {len(arcs)})")

    maps = op_atom_map(rots, trans, positions)
    print(f"  ops that permute the orbit: {len(maps)}")

    # vertex orbits
    vseen = set()
    vorbits = 0
    for v in range(len(positions)):
        if v in vseen:
            continue
        vorbits += 1
        for (smap, _, _) in maps:
            vseen.add(smap[v])
    print(f"  VERTEX orbits: {vorbits}  ({'vertex-transitive' if vorbits==1 else 'NOT vertex-transitive'})")

    n_edge, _ = orbit_count(arcs, maps, directed=False)
    print(f"  UNDIRECTED-EDGE orbits: {n_edge}  ({'edge-transitive' if n_edge==1 else 'NOT edge-transitive'})")

    n_arc, reps = orbit_count(arcs, maps, directed=True)
    print(f"  DIRECTED-ARC orbits: {n_arc}")

    rev = edge_reversible(arcs, maps)
    print(f"  edge reversible by a symmetry? {rev}")

    k, loc_order, full = local_vertex_action(arcs, maps)
    print(f"  LOCAL vertex action on the {k} incident edges: order {loc_order} "
          f"(full S_{k} has order {full})")
    print(f"    -> local action is {'FULL S_k (Sunada strong isotropy)' if loc_order==full else 'a PROPER subgroup (transitive but NOT full S_k)'}"
          if loc_order in (full,) or True else "")

    print("\n  VERDICT:")
    arc_trans = (n_arc == 1)
    strong = (loc_order == full and vorbits == 1)
    print(f"    arc-transitive (1 arc orbit, = what no-privilege delivers): {arc_trans}")
    print(f"    strongly isotropic (full local S_k, = what Sunada's uniqueness needs): {strong}")
    return {
        'name': name, 'sg': sg_symbol, 'sg_number': sg_number,
        'vertex_orbits': vorbits, 'edge_orbits': n_edge, 'arc_orbits': n_arc,
        'reversible': rev, 'local_order': loc_order, 'full_Sk': full,
        'arc_transitive': arc_trans, 'strongly_isotropic': strong,
    }


if __name__ == '__main__':
    results = []
    results.append(analyze('dia (VALIDATION: Sunada strong-iso)', 'dia'))
    print()
    results.append(analyze('pcu (VALIDATION: not strong-iso)', 'pcu'))
    print()
    results.append(analyze('srs (Laves / K4 / (10,3)-a)', 'srs'))
    print()
    results.append(analyze('srs-z (bipartite double cover)', 'srs-z'))

    print("\n" + "=" * 78)
    print("SUMMARY")
    print("=" * 78)
    hdr = f"{'net':<8s} {'SG':<10s} {'V-orb':>5s} {'E-orb':>5s} {'arc-orb':>7s} {'rev':>4s} {'loc|Sk':>8s} {'arc-T':>6s} {'strong':>7s}"
    print(hdr)
    for r in results:
        print(f"{r['name'][:8]:<8s} {r['sg']:<10s} {r['vertex_orbits']:>5d} {r['edge_orbits']:>5d} "
              f"{r['arc_orbits']:>7d} {str(r['reversible']):>4s} {str(r['local_order'])+'/'+str(r['full_Sk']):>8s} "
              f"{str(r['arc_transitive']):>6s} {str(r['strongly_isotropic']):>7s}")
