#!/usr/bin/env python3
"""
proofs/foundations/G8_IF_inner_fluctuation_2026-07-09.py

G8-IF -- THE INNER-FLUCTUATION SECTOR (first build).  Pre-registered in
internal research notes (commit 8cfb10b; adjudications 1-4, contracts
IF-0..IF-5, POISONS -- all frozen BEFORE this file was written).  Target: OMEGA_T1's named open -- "the
a4 of the internal (Cl(6)/D_F) fluctuation sector against the D4 cone, whose TARGET SHAPE is now known
exactly: -3C2(G) + Sum T" -- i.e. instantiate NCG's inner-fluctuation calculus A = Sum a_i[D_F,b_i],
D -> D + A + J A J^-1, on the framework's OWN certified internal space (the Cl(6) Fock, KO-6 confirmed
by R2b).  RESEARCH-grade: the honest outcome may be structure-only.

ARCHITECT ADJUDICATIONS (frozen, verbatim from the pre-reg)
  1. Internal space = the certified 8-dim Cl(6) Fock with the KO-6-confirming pair
     (gamma_F = P_F, J_F = sigma_M0) from ncg_spectral.py's KO block.  The old R1_Av_higgs_sector_probe.py
     (2026-05-14, per-vertex/edge 280-dim A_F/D_F) is a SUPERSEDED pre-WS1/pre-KO-6 construction --
     explicitly ruled out as a reuse surface here.
  2. D_F is a SPACE, not a choice: KO-2.4's computed D-space (Hermitian, gamma-odd, A4-covariant; 4 real
     dimensions for the KO-6 pair) is used WHOLE.  Every D_F-dependent quantity is computed for all 4
     basis elements + 3 declared pseudo-random unit combinations (seed 0); D_F-choice (in)dependence is
     itself a contract output, never a cherry-pick.
  3. The algebra A_F, primary vs comparison: PRIMARY = the unital *-algebra generated by the framework's
     own DERIVED physical operators -- FS-4's eight color-su(3) bilinears + FS-3's Q = N_hat/3 + the
     identity (GREEN contracts).  COMPARISON = the full gamma_F-even Hermitian block (32-dim).  Both
     computed; the physical claim rides the PRIMARY; the difference is reported.  No post-hoc switching.
  4. Home: proofs/foundations/ (a station probe -- it ADDS physics, so it does NOT go into the
     adapters, which are zero-physics contracts).  Promotion into ncg_spectral.py is an integration-time
     architect decision, explicitly deferred.

REUSE MAP (nothing below is re-derived from scratch; every recipe is the SAME construction already
verified in the named adapter files -- reconstructed verbatim here rather than imported, because
ncg_spectral.py / furey_stoica_labels.py are executable top-level scripts that end in sys.exit(); this
is the SAME precedent those two files themselves use for each other -- see their own REUSE MAP headers,
"reproduced here verbatim; no engine import, no re-fit"):
  - Cl(6) generators + gamma_5, Witt ladder/Fock (J6, A_ops, NHAT, vacuum, the 8 ladder states),
    A4 gauge lift, KO-6 pair (gamma_F=P_F, J_F=sigma_M0), the 64-dim Hermitian basis / D-space solve
    (d_space_and_eps_prime)                          : derivation_topdown/adapters/ncg_spectral.py
                                                         lines ~130-559 (KO-2 block), reconstructed
                                                         verbatim, checks re-run as IF-0.
  - Q = N_hat/3, the 8 color-su(3) mode bilinears     : derivation_topdown/adapters/furey_stoica_labels.py
                                                         FS-3 (~230-232) / FS-4 (~267-313), reconstructed
                                                         verbatim (re-expressed in the Fock/SUBSETS basis
                                                         via the SAME W change-of-basis ncg_spectral.py
                                                         uses for PF/Vsig/U_A4_F -- see the BASIS NOTE
                                                         below).
  - The cone / endomorphism_E / beta-row machine       : derivation_topdown/bridge/d4_spectral_action.py
                                                         (a5b_dirac_cone, spin_generators, endomorphism_E,
                                                         fermion_2sz2, gauge_dynkin, beta_rows,
                                                         sm_content) -- IMPORTED, never rebuilt.

BASIS NOTE (important, not in the two source adapters because neither needed to combine their objects):
ncg_spectral.py expresses PF, Vsig, U_A4_F, HERM_BASIS all in the FOCK/SUBSETS-ordered basis (every one
of them is explicitly conjugated through W = hstack(ladder_vecs), the ladder-state change-of-basis
matrix).  furey_stoica_labels.py's NHAT/su3_gens/QCHG are built directly from A_ops/Adag_ops in the
ORIGINAL (pre-W) representation and are NEVER conjugated by W in that file (it has no need to -- FS-3/4
never combine with PF/Vsig).  To use both families of objects TOGETHER (as this station must), every
A_F operator is explicitly re-expressed via W below (T_F := W^dagger T W) BEFORE anything else is done;
the sanity check "W^dagger NHAT W is exactly diagonal in the SUBSETS order" (IF-0h) is the in-code proof
that this re-expression is the correct, consistent one (PF was defined directly as diag((-1)^len(S)) in
that same SUBSETS order, so this is the unique consistent alignment, not a choice).

POISONS (binding, restated): no goal-seek toward the 0.0139% gap or toward -3C2+Tf+TH; IF-3/IF-4's
constructions are FIXED by IF-0..2's structure BEFORE the confronts run (this file is written and run in
that literal order: IF-0 -> IF-1 -> IF-2 -> IF-3 -> IF-4, no back-editing after seeing later numbers);
D_F never cherry-picked; A_F never switched post-hoc; the old R1_Av machinery not reused; retired
intermediate numbers quoted only as documented history; numbers in the report only from running code;
engine/adapters/the_net.py UNTOUCHED (this is the only new file); runtime target < 5 min.

Exit code: 0 iff IF-0 and IF-1 pass (all anchor/computation checks) AND IF-2/IF-3/IF-4 each reach one of
their pre-declared definite verdicts (always true by construction of the branch logic below -- "definite"
means "a completed, booked reading", exactly as KO-3/FS-5's own dual-outcome contracts define it).
"""
import itertools
import math
import os
import sys
import time

import numpy as np

t_start = time.time()

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, REPO)
sys.path.insert(0, os.path.join(REPO, "derivation_topdown", "dirac_srs_mdl"))
sys.path.insert(0, os.path.join(REPO, "derivation_topdown", "bridge"))
import srs  # noqa: E402  (walled-off clean-room K4-cover module; EDGES, NV)
from simulator.srs_engine.utils import AlgebraicUtility  # noqa: E402
import d4_spectral_action as d4  # noqa: E402  (the S1 cone machine -- reuse, do not rebuild)

np.set_printoptions(precision=6, suppress=True, linewidth=120)

ok_all = True


def check(name, cond, detail=""):
    global ok_all
    cond = bool(cond)
    ok_all = ok_all and cond
    print(f"    [{'PASS' if cond else 'FAIL'}] {name}" + (f"  -- {detail}" if detail else ""))
    return cond


def banner(t):
    print("=" * 100)
    print(f" {t}")
    print("=" * 100)


# ====================================================================================================
banner("IF-0  ANCHORS  (KO-6 pair + D-space, reconstructed verbatim from ncg_spectral.py; checks re-run)")
# ====================================================================================================
print("""    SUPERSESSION NOTE (adjudication 1): the old R1_Av_higgs_sector_probe.py (2026-05-14, a
    per-vertex/edge 280-dim A_F/D_F construction) is a PRE-WS1/PRE-KO-6 object and is explicitly NOT
    reused here.  The internal space used below is the CERTIFIED 8-dim Cl(6) Fock with the KO-6-
    confirming pair (gamma_F=P_F, J_F=sigma_M0) established in R2b (docs/scoping/
    R2b_ko_convention_prereg_2026-07-09.md) and ncg_spectral.py's KO-2/KO-3 blocks.

    B3 OBLIQUE-NULL PREMISE (wave motivation, quoted): B3_MZ_oblique_cone_recompute_2026-07-07.py PROVED
    the continuum D4 cone's Pi_ab is EXACTLY isotropic (no substrate-native oblique correction from the
    cone alone).  If the M_Z +7.76 sigma oblique floor is derivable content at all, the burden falls
    ENTIRELY on the INTERNAL (Cl(6)/D_F) factor -- that is the falsifiable crux this station probes
    (IF-4).""")

g6 = [np.array(g, complex) for g in AlgebraicUtility.cl6_generators()]
g5_raw = AlgebraicUtility.cl6_chirality()
I8 = np.eye(8, dtype=complex)

cliff6 = max(np.max(np.abs(g6[a] @ g6[b] + g6[b] @ g6[a] - (2.0 if a == b else 0.0) * I8))
             for a in range(6) for b in range(6))
check(f"IF-0a Cl(6) generators {{gamma^a,gamma^b}} = 2 delta^ab I  (max dev {cliff6:.2e})", cliff6 < 1e-12)
g5sq = g5_raw @ g5_raw
g5_ok = np.allclose(g5sq, I8) or np.allclose(g5sq, -I8)
check("IF-0b gamma_5 = prod(gamma^a) squares to a genuine involution (Euclidean Cl(6,0) sign, forced)",
      g5_ok)

EDGES = srs.EDGES
NE, NV = len(EDGES), srs.NV
EIDX = {(min(i, j), max(i, j)): e for e, (i, j, v) in enumerate(EDGES)}
gam = lambda x: sum(x[a] * g6[a] for a in range(NE))


def edge_rep(sig):
    R6 = np.zeros((NE, NE))
    for e, (i, j, v) in enumerate(EDGES):
        a, b = sig[i], sig[j]
        s = 1.0
        if a > b:
            a, b, s = b, a, -1.0
        R6[EIDX[(a, b)], e] = s
    return R6


def spin_lift(R):
    rowsU = [np.kron(gam(R[:, a]), I8) - np.kron(I8, g6[a].T) for a in range(NE)]
    _, s, Vh = np.linalg.svd(np.vstack(rowsU))
    M = Vh[np.sum(s > 1e-9):].conj()[0].reshape(8, 8)
    return M / np.sqrt(np.abs(np.linalg.det(M @ M.conj().T)) ** (1 / 8))


d0 = np.zeros((NV, NE))
for e, (i, j, v) in enumerate(EDGES):
    d0[i, e] = -1.0
    d0[j, e] = 1.0
Chat = np.array([[1, 1, 0], [-1, 0, 1], [0, -1, -1], [1, 0, 0], [0, 1, 0], [0, 0, 1]], float)
H1, _ = np.linalg.qr(Chat)
B1 = np.linalg.svd(d0)[2][:3].T
A4 = [dict(enumerate(p)) for p in itertools.permutations(range(4))
      if sum(1 for i in range(4) for j in range(i + 1, 4) if p[i] > p[j]) % 2 == 0]
rowsJ = []
for gA in A4:
    R6 = edge_rep(gA)
    rowsJ.append(np.kron(np.eye(3), (H1.T @ R6 @ H1).T) - np.kron(B1.T @ R6 @ B1, np.eye(3)))
_, SpJ, VpJ = np.linalg.svd(np.vstack(rowsJ))
phi = VpJ[-1].reshape(3, 3)
phi *= math.sqrt(3) / np.linalg.norm(phi)
J6 = B1 @ phi @ H1.T - H1 @ phi.T @ B1.T
wJ, VJ = np.linalg.eig(J6)
modes, _ = np.linalg.qr(VJ[:, np.where(np.abs(wJ - 1j) < 1e-9)[0]])
A_ops = [gam(np.conj(modes[:, m])) / math.sqrt(2) for m in range(3)]
Adag_ops = [a.conj().T for a in A_ops]
NHAT = sum(Adag_ops[i] @ A_ops[i] for i in range(3))
wN, VN = np.linalg.eigh(NHAT)
vac = VN[:, [int(np.argmin(wN))]]
vac /= np.linalg.norm(vac)

nilp = max(np.max(np.abs(A_ops[i] @ A_ops[i])) for i in range(3))
check(f"IF-0c ladder nilpotency a_i^2 = 0  (max abs {nilp:.2e})", nilp < 1e-12)
acomm = max(np.max(np.abs(A_ops[i] @ A_ops[j] + A_ops[j] @ A_ops[i]))
            for i in range(3) for j in range(3) if i != j)
check(f"IF-0d {{a_i,a_j}}=0 i!=j  (max abs {acomm:.2e})", acomm < 1e-12)
car = max(np.max(np.abs(A_ops[i] @ Adag_ops[j] + Adag_ops[j] @ A_ops[i]
                        - (I8 if i == j else 0.0))) for i in range(3) for j in range(3))
check(f"IF-0e {{a_i,a_j^dag}}=delta_ij  (max abs {car:.2e})", car < 1e-12)

SUBSETS = sorted([tuple(sorted(s)) for r in range(4) for s in itertools.combinations(range(3), r)],
                  key=lambda s: (len(s), s))
ladder_vecs = {}
for S in SUBSETS:
    v = vac.copy()
    for i in sorted(S, reverse=True):
        v = Adag_ops[i] @ v
    ladder_vecs[S] = v
W = np.hstack([ladder_vecs[S] for S in SUBSETS])
idx = {S: k for k, S in enumerate(SUBSETS)}
comp = lambda S: tuple(sorted(set(range(3)) - set(S)))

Gram = np.array([[(ladder_vecs[S1].conj().T @ ladder_vecs[S2]).item() for S2 in SUBSETS] for S1 in SUBSETS])
orthonorm_dev = np.max(np.abs(Gram - np.eye(8)))
check(f"IF-0f the 8 ladder states are orthonormal (max abs Gram-I = {orthonorm_dev:.2e})",
      orthonorm_dev < 1e-9)
w_unitary_dev = np.max(np.abs(W.conj().T @ W - I8))
check(f"IF-0g W (Fock basis change) is unitary (max dev {w_unitary_dev:.2e})", w_unitary_dev < 1e-9)

U_A4_comp = [spin_lift(edge_rep(gA)) for gA in A4]
U_A4_F = [W.conj().T @ U @ W for U in U_A4_comp]
a4_dev = max(np.max(np.abs(U.conj().T @ U - I8)) for U in U_A4_F)
check(f"IF-0h the 12 A4 lift operators are unitary in the Fock basis (max dev {a4_dev:.2e}; native SVD "
      f"precision of this solve, same construction/tolerance as ncg_spectral.py KO-2.0e)", a4_dev < 1e-5)

PF = np.diag([(-1.0) ** len(S) for S in SUBSETS]).astype(complex)   # gamma_F = P_F = (-1)^Nhat
check("IF-0i P_F = (-1)^Nhat squares to +I", np.allclose(PF @ PF, I8))

vac_full = ladder_vecs[(0, 1, 2)]
images = {}
for S in SUBSETS:
    v = vac_full.copy()
    for i in sorted(S, reverse=True):
        v = A_ops[i] @ v
    images[S] = v
liftable = all(np.linalg.norm(images[S]) > 1e-8 for S in SUBSETS)
check("IF-0j sigma_M0 IS liftable to the Fock (every image(S) nonzero)", liftable)
Vsig = np.zeros((8, 8), complex)
for S in SUBSETS:
    Vsig[:, idx[S]] = (W.conj().T @ images[S])[:, 0]
vsig_dev = np.max(np.abs(Vsig.conj().T @ Vsig - I8))
check(f"IF-0k sigma_M0's V_sigma is unitary (max dev {vsig_dev:.2e}) -- J_F = sigma_M0 = V_sigma o K, "
      f"the antiunitary KO-6 real structure", vsig_dev < 1e-9)

A_ops_F = [W.conj().T @ A_ops[i] @ W for i in range(3)]
Adag_ops_F = [a.conj().T for a in A_ops_F]
sigma_defining_dev = max(np.max(np.abs(Vsig @ np.conj(A_ops_F[i]) @ Vsig.conj().T - Adag_ops_F[i]))
                         for i in range(3))
check(f"IF-0l sigma_M0 defining relation (J antiunitarity/consistency): "
      f"max_i |Sigma A_i Sigma^-1 - A_i^dagger| = {sigma_defining_dev:.2e}", sigma_defining_dev < 1e-12)

# ---- the 64-dim real Hermitian basis of Herm(C^8) (ncg_spectral.py's HERM_BASIS, verbatim) ----
NFOCK = 8
HERM_BASIS = []
for k in range(NFOCK):
    E = np.zeros((NFOCK, NFOCK), complex); E[k, k] = 1.0; HERM_BASIS.append(E)
for k in range(NFOCK):
    for ell in range(k + 1, NFOCK):
        E1 = np.zeros((NFOCK, NFOCK), complex); E1[k, ell] = 1.0; E1[ell, k] = 1.0
        HERM_BASIS.append(E1)
        E2 = np.zeros((NFOCK, NFOCK), complex); E2[k, ell] = 1j; E2[ell, k] = -1j
        HERM_BASIS.append(E2)
check(f"IF-0m Hermitian-operator basis has dimension {len(HERM_BASIS)} == 8^2 = 64", len(HERM_BASIS) == 64)


def flat(M):
    return np.concatenate([M.real.flatten(), M.imag.flatten()])


B_MAT = np.array([flat(b) for b in HERM_BASIS]).T
B_PINV = np.linalg.pinv(B_MAT)


def coeffs_of(M):
    return B_PINV @ flat(M)


def matrix_of(x):
    return sum(x[m] * HERM_BASIS[m] for m in range(len(HERM_BASIS)))


def sign_transform(V, O):
    """J O J^-1 for antiunitary J = V o K:  V . conj(O) . V^dagger."""
    return V @ np.conj(O) @ V.conj().T


def get_sign(O_transformed, O, tol=1e-6):
    if np.allclose(O_transformed, O, atol=tol):
        return +1
    if np.allclose(O_transformed, -O, atol=tol):
        return -1
    return None


def d_space_and_eps_prime(gamma, V, U_A4_list, tol_sv=1e-8, tol_leak=1e-9):
    """Verbatim reconstruction of ncg_spectral.py's KO-2.4/D-space solve, EXTENDED to also return the
    real orthonormal basis P of the D-space (64,nullity) -- the source adapter only reports diagnostics,
    this station additionally needs the actual matrices to build D_F candidates."""
    cols = []
    for B in HERM_BASIS:
        odd = gamma @ B @ gamma + B
        resid = [odd] + [B @ U - U @ B for U in U_A4_list]
        cols.append(np.concatenate([flat(r) for r in resid]))
    Mx = np.array(cols).T
    _, Ss, Vt = np.linalg.svd(Mx)
    nullity = int(np.sum(Ss < tol_sv * (Ss[0] if len(Ss) else 1.0)))
    if nullity == 0:
        return {"nullity": 0, "verdict": "VACUOUS", "P": None}
    P = Vt[64 - nullity:64].conj().T.real
    naive_signs = []
    for k in range(nullity):
        Db = matrix_of(P[:, k])
        Ot = sign_transform(V, Db)
        naive_signs.append(get_sign(Ot, Db))
    Rfull = np.zeros((64, 64))
    for m in range(64):
        Rfull[:, m] = coeffs_of(sign_transform(V, HERM_BASIS[m])).real
    Proj = P @ P.T
    leak = float(np.max(np.abs((np.eye(64) - Proj) @ Rfull @ Proj)))
    clean = leak < tol_leak
    Rsub = P.T @ Rfull @ P
    evals = np.linalg.eigvalsh((Rsub + Rsub.T) / 2)
    if all(s == +1 for s in naive_signs):
        verdict = "+1 FORCED"
    elif all(s == -1 for s in naive_signs):
        verdict = "-1 FORCED"
    else:
        verdict = "UN-FORCED"
    return {"nullity": nullity, "verdict": verdict, "naive_signs": naive_signs,
            "leak": leak, "clean": clean, "evals": evals, "P": P}


dres = d_space_and_eps_prime(PF, Vsig, U_A4_F)
check(f"IF-0n the D-space (Hermitian, gamma_F-odd, A4-covariant operators) has dimension "
      f"{dres['nullity']} == 4 (the KO-6 pair's certified D-space)", dres["nullity"] == 4)
check(f"IF-0o J_F-conjugation preserves the D-space (leak = {dres['leak']:.2e} < 1e-12)",
      dres["leak"] < 1e-12, detail=f"eps'-forcing verdict = {dres['verdict']}, evals={np.round(dres['evals'],3).tolist()}")
D_SPACE_P = dres["P"]   # (64, 4) real orthonormal basis of the D-space, in HERM_BASIS coordinates

# ---- BASIS NOTE verification: re-express FS-3/FS-4's Q, su(3) bilinears in the SAME Fock/SUBSETS basis ----
su3_gens_raw, su3_labels = [], []
for i in range(3):
    for j in range(i + 1, 3):
        su3_gens_raw.append(Adag_ops[i] @ A_ops[j] + Adag_ops[j] @ A_ops[i]); su3_labels.append(f"X{i}{j}")
        su3_gens_raw.append(-1j * (Adag_ops[i] @ A_ops[j] - Adag_ops[j] @ A_ops[i])); su3_labels.append(f"Y{i}{j}")
n_ii = [Adag_ops[i] @ A_ops[i] for i in range(3)]
su3_gens_raw.append(n_ii[0] - n_ii[1]); su3_labels.append("H1")
su3_gens_raw.append((n_ii[0] + n_ii[1] - 2 * n_ii[2]) / math.sqrt(3)); su3_labels.append("H2")

su3_gens_F = [W.conj().T @ T @ W for T in su3_gens_raw]     # re-expressed in the Fock/SUBSETS basis
NHAT_F = W.conj().T @ NHAT @ W
QCHG_F = NHAT_F / 3.0
NHAT_F_diag_expected = np.diag([float(len(S)) for S in SUBSETS]).astype(complex)
nhatF_dev = np.max(np.abs(NHAT_F - NHAT_F_diag_expected))
check(f"IF-0p BASIS NOTE: W^dagger.NHAT.W is EXACTLY diag(len(S)) in the SUBSETS order used by PF "
      f"(max dev {nhatF_dev:.2e}) -- confirms su3_gens_F/QCHG_F are consistently aligned with PF/Vsig/"
      f"U_A4_F/HERM_BASIS (all Fock/SUBSETS-basis objects)", nhatF_dev < 1e-12)
herm_su3_F = max(np.max(np.abs(T - T.conj().T)) for T in su3_gens_F)
check(f"IF-0q su3_gens_F remain Hermitian after the W re-expression (max dev {herm_su3_F:.2e})",
      herm_su3_F < 1e-10)
comm_N_F = max(np.max(np.abs(T @ NHAT_F - NHAT_F @ T)) for T in su3_gens_F)
comm_Q_F = max(np.max(np.abs(T @ QCHG_F - QCHG_F @ T)) for T in su3_gens_F)
check(f"IF-0r [su3_gens_F,NHAT_F]=0 and [su3_gens_F,QCHG_F]=0 in the Fock basis "
      f"(max devs {comm_N_F:.2e}, {comm_Q_F:.2e}) -- A_F is number-conserving, hence entirely "
      f"gamma_F=P_F-EVEN (commutes with (-1)^Nhat)", comm_N_F < 1e-10 and comm_Q_F < 1e-10)
comm_gF = max(np.max(np.abs(T @ PF - PF @ T)) for T in (su3_gens_F + [QCHG_F]))
check(f"IF-0s direct check: every PRIMARY generator commutes with gamma_F=P_F (max dev {comm_gF:.2e}) "
      f"=> A_F is gamma_F-EVEN by construction (forced, not assumed)", comm_gF < 1e-10)

IF0_PASS = ok_all
print(f"\n    IF-0 VERDICT: {'PASS' if IF0_PASS else '*** FAIL ***'} "
      f"(D-space dim={dres['nullity']}, leak={dres['leak']:.2e})")

# ====================================================================================================
banner("SETUP  D_F CANDIDATES (7 declared: 4 D-space basis + 3 pseudo-random unit combos, seed 0)")
# ====================================================================================================
DF_BASIS_MATS = [matrix_of(D_SPACE_P[:, k]) for k in range(4)]
rng = np.random.default_rng(0)
DF_RANDOM_MATS = []
for _ in range(3):
    v = rng.normal(size=4)
    v = v / np.linalg.norm(v)
    DF_RANDOM_MATS.append(matrix_of(D_SPACE_P @ v))
ALL_DF = [(f"D_F#{k}(basis)", M) for k, M in enumerate(DF_BASIS_MATS)] + \
         [(f"D_F#{4+k}(rand)", M) for k, M in enumerate(DF_RANDOM_MATS)]
print(f"    {len(ALL_DF)} D_F candidates declared: {[lbl for lbl, _ in ALL_DF]}")
for lbl, D in ALL_DF:
    herm_dev = np.max(np.abs(D - D.conj().T))
    odd_dev = np.max(np.abs(PF @ D @ PF + D))
    a4_dev_D = max(np.max(np.abs(D @ U - U @ D)) for U in U_A4_F)
    check(f"    {lbl}: Hermitian (dev {herm_dev:.2e}), gamma_F-odd (dev {odd_dev:.2e}), "
          f"A4-covariant (dev {a4_dev_D:.2e})", herm_dev < 1e-9 and odd_dev < 1e-9 and a4_dev_D < 1e-4)

# ====================================================================================================
banner("SETUP  A_F ALGEBRAS  (PRIMARY: generated *-algebra;  COMPARISON: gamma_F-even Hermitian block)")
# ====================================================================================================


def flatten_c(M):
    return np.concatenate([M.real.flatten(), M.imag.flatten()])


def unflatten_c(v, n=8):
    re = v[:n * n].reshape(n, n)
    im = v[n * n:].reshape(n, n)
    return re + 1j * im


def real_span_basis(mats, tol=1e-9):
    if not mats:
        return [], 0
    V = np.array([flatten_c(M) for M in mats])
    _, S, Vt = np.linalg.svd(V, full_matrices=False)
    r = int(np.sum(S > tol * (S[0] if len(S) else 1.0)))
    basis = [unflatten_c(Vt[k]) for k in range(r)]
    return basis, r


def generate_star_algebra(generators, max_iter=8, tol=1e-9):
    """Closure under matrix products (both orders), real span, iterate until dimension saturates."""
    basis, dim = real_span_basis(generators, tol)
    prev_dim = -1
    it = 0
    while dim != prev_dim and it < max_iter:
        prev_dim = dim
        candidates = list(basis)
        for g in generators:
            for h in basis:
                candidates.append(g @ h)
                candidates.append(h @ g)
        basis, dim = real_span_basis(candidates, tol)
        it += 1
    return basis, dim, it


PRIMARY_GENERATORS = [I8, QCHG_F] + su3_gens_F
A_PRIMARY_BASIS, A_PRIMARY_DIM, primary_iters = generate_star_algebra(PRIMARY_GENERATORS)
print(f"    PRIMARY generators: I, Q=Nhat/3, 8 color-su(3) bilinears (10 Hermitian seeds).")
print(f"    Closure iteration: {primary_iters} rounds to saturation.")
# forced count (derived, not fit to the observed number): su(3) acts on N=1 as the FUNDAMENTAL (3) and on
# N=2 as the ANTIFUNDAMENTAL (3bar) -- both IRREDUCIBLE (FS-4e) and INEQUIVALENT complex reps of su(3),
# so by Burnside's theorem the associative (product-)closure of {su3_gens_F} independently saturates each
# block to the FULL Mat_3(C) (9 complex = 18 real dims each, since real span of Hermitian PRODUCTS reaches
# both the symmetric AND i*antisymmetric combinations -- verified in-code, not assumed).  On the two
# 1-dim singlet blocks (N=0, N=3) su3_gens_F vanish IDENTICALLY (FS-4e "kills_singlets"), so the ONLY
# generators reaching those blocks are I and Q -- both REAL-valued there; no product of REAL scalars ever
# produces an imaginary one, so each singlet block contributes exactly 1 REAL dimension (not a complex
# dim = 2 real), since nothing in the generating set can build "i*P_0" or "i*P_3".  Forced total:
# 18 + 18 + 1 + 1 = 38 real dimensions (NOT 40 -- an earlier hand-count assumed the singlets contribute a
# full complex dim each; the in-code closure below is what corrected that, exactly as it should).
EXPECTED_A_PRIMARY_DIM = 18 + 18 + 1 + 1
check(f"IF-setup-a PRIMARY *-algebra A_F: generated (real) dimension = {A_PRIMARY_DIM} "
      f"(forced = 38: Mat_3(C)+Mat_3(C) on the irreducible fund/antifund N=1,N=2 blocks [18+18 real] "
      f"+ 1 real scalar each on the su(3)-singlet N=0,N=3 blocks [no imaginary direction reachable "
      f"there, since su3_gens_F vanish on singlets and I,Q are real] -- see derivation above)",
      A_PRIMARY_DIM == EXPECTED_A_PRIMARY_DIM)

# COMPARISON: the full gamma_F-even Hermitian block (32-dim), analogous to KO-2.4's odd-space nullspace.
even_cols = [flat(PF @ B @ PF - B) for B in HERM_BASIS]
_, Ss_even, Vt_even = np.linalg.svd(np.array(even_cols).T)
nullity_even = int(np.sum(Ss_even < 1e-8 * Ss_even[0]))
P_even = Vt_even[64 - nullity_even:64].conj().T.real
A_COMPARISON_BASIS = [matrix_of(P_even[:, k]) for k in range(nullity_even)]
check(f"IF-setup-b COMPARISON algebra (full gamma_F-even Hermitian block): dimension = {nullity_even} "
      f"(expected 32, complementary to KO-2.4's gamma_F-odd 32-dim space)", nullity_even == 32)
print(f"    PRIMARY real dim = {A_PRIMARY_DIM};  COMPARISON real dim = {nullity_even}.")

# ====================================================================================================
banner("IF-1  THE ONE-FORM SPACE  Omega^1 = span_R{ i.a[D_F,b] : a,b in A_F }  (Hermitian closure)")
# ====================================================================================================


def hermitian_closure_span(D_F, A_basis, tol=1e-9):
    """Raw generators X_ab = i.a[D_F,b] for a,b in A_basis; Hermitian closure via (X+X^dag)/2 and
    i(X-X^dag)/2 (both Hermitian for any complex X); real span in the 64-dim HERM_BASIS coordinates."""
    vecs = []
    for a in A_basis:
        aD = a @ D_F
        for b in A_basis:
            X = 1j * (aD @ b - a @ (b @ D_F))
            Hp = (X + X.conj().T) / 2
            Hm = 1j * (X - X.conj().T) / 2
            vecs.append(coeffs_of(Hp).real)
            vecs.append(coeffs_of(Hm).real)
    V = np.array(vecs)
    _, S, Vt = np.linalg.svd(V, full_matrices=False)
    r = int(np.sum(S > tol * (S[0] if len(S) else 1.0)))
    P_Omega = Vt[:r].T   # (64, r) orthonormal columns
    return P_Omega, r


def principal_angles(P1, P2):
    # INTEGRATION FIX (2026-07-09, mandated by the adversarial check): the original
    # arccos(svd(P1^T P2)) is ill-conditioned for near-identical subspaces -- arccos(1-x)
    # ~ sqrt(2x) amplifies ULP-level noise in the cosines to an apparent ~1e-8 "angle".
    # The checker re-measured the true angles at ~1e-15 with the sin-based method
    # (scipy.linalg.subspace_angles, Knyazev-Argentati), reversing the IF-1 sub-verdict
    # to D_F-INDEPENDENT. This is a numerical-method correction, not a physics change.
    from scipy.linalg import subspace_angles
    return subspace_angles(P1, P2)


def gamma_even_odd_split(P_Omega, tol_leak=1e-9):
    """Restricted-involution diagnostic of X -> PF.X.PF on the subspace spanned by P_Omega's columns."""
    r = P_Omega.shape[1]
    if r == 0:
        return 0, 0, 0.0, np.array([])
    Rfull = np.zeros((64, 64))
    for m in range(64):
        Rfull[:, m] = coeffs_of(PF @ HERM_BASIS[m] @ PF).real
    Proj = P_Omega @ P_Omega.T
    leak = float(np.max(np.abs((np.eye(64) - Proj) @ Rfull @ Proj)))
    Rsub = P_Omega.T @ Rfull @ P_Omega
    evals = np.linalg.eigvalsh((Rsub + Rsub.T) / 2)
    n_even = int(np.sum(evals > 0))
    n_odd = int(np.sum(evals < 0))
    return n_even, n_odd, leak, evals


OMEGA1 = {}   # (algebra_name, df_label) -> (P_Omega, dim)
for alg_name, A_basis in (("PRIMARY", A_PRIMARY_BASIS), ("COMPARISON", A_COMPARISON_BASIS)):
    for lbl, D_F in ALL_DF:
        P_Omega, r = hermitian_closure_span(D_F, A_basis)
        OMEGA1[(alg_name, lbl)] = (P_Omega, r)

print("    dim(Omega^1) table (rows = D_F, cols = algebra):")
print(f"    {'D_F':<16}{'PRIMARY':>10}{'COMPARISON':>14}")
for lbl, _ in ALL_DF:
    dP = OMEGA1[("PRIMARY", lbl)][1]
    dC = OMEGA1[("COMPARISON", lbl)][1]
    print(f"    {lbl:<16}{dP:>10}{dC:>14}")

# D_F-(in)dependence: compare D_F#0's subspace against the other 6, per algebra.
print()
for alg_name in ("PRIMARY", "COMPARISON"):
    ref_lbl = ALL_DF[0][0]
    P_ref, d_ref = OMEGA1[(alg_name, ref_lbl)]
    max_angle = 0.0
    dep_found = False
    detail_rows = []
    for lbl, _ in ALL_DF[1:]:
        P_k, d_k = OMEGA1[(alg_name, lbl)]
        if d_k != d_ref:
            dep_found = True
            detail_rows.append(f"{lbl}: dim {d_k} != ref dim {d_ref} (DEPENDENT)")
            max_angle = float("inf")
            continue
        angles = principal_angles(P_ref, P_k)
        a_max = float(np.max(angles)) if len(angles) else 0.0
        max_angle = max(max_angle, a_max)
        if a_max >= 1e-9:
            dep_found = True
        detail_rows.append(f"{lbl}: max principal angle vs {ref_lbl} = {a_max:.2e}")
    verdict = "D_F-DEPENDENT" if dep_found else "D_F-INDEPENDENT"
    print(f"    [{alg_name}] Omega^1 subspace across the 7 D_F's: {verdict} "
          f"(max angle/mismatch = {max_angle:.2e}; pre-registered threshold 1e-9)")
    for row in detail_rows:
        print(f"        {row}")
    if 1e-9 <= max_angle < 1e-5:
        print(f"        TRANSPARENCY CAVEAT: the measured angle ({max_angle:.2e}) is applying the "
              f"pre-registered 1e-9 cutoff literally (so this books as D_F-DEPENDENT), but it sits only "
              f"~1-2 orders above that cutoff -- compare the ~1e-15 to 1e-16 precision achieved by every "
              f"DIRECTLY-forced algebraic identity in this file (IF-0's leak=5.33e-16, defining-relation "
              f"dev=2.0e-15, etc.).  This subspace comparison chains SEVERAL rank-revealing SVDs (the "
              f"A_F closure iteration, the D-space nullspace solve, the Hermitian-closure span), each with "
              f"its own tol=1e-9 relative rank cutoff, so ~1e-8 accumulated floating-point drift through "
              f"that chain is a plausible full explanation on its own.  Booked honestly as D_F-DEPENDENT "
              f"per the literal contract, but NOT interpreted as a confirmed small physical dependence --"
              f" it is not resolved cleanly either way at this numerical precision.")
    if alg_name == "PRIMARY":
        PRIMARY_DF_INDEPENDENT = not dep_found
    else:
        COMPARISON_DF_INDEPENDENT = not dep_found

print("\n    gamma_F/J_F structure of Omega^1 (raw A, and the symmetrized A + J_F.A.J_F^-1):")
GRADING = {}
for alg_name in ("PRIMARY", "COMPARISON"):
    for lbl, _ in ALL_DF:
        P_Omega, r = OMEGA1[(alg_name, lbl)]
        n_even, n_odd, leak, evals = gamma_even_odd_split(P_Omega)
        # A + J_F A J_F^-1: build the combined span
        if r > 0:
            extra = [coeffs_of(sign_transform(Vsig, matrix_of(P_Omega[:, k]))).real for k in range(r)]
            V_comb = np.vstack([P_Omega.T, np.array(extra)])
            _, Sc, Vtc = np.linalg.svd(V_comb, full_matrices=False)
            rc = int(np.sum(Sc > 1e-9 * Sc[0]))
            P_comb = Vtc[:rc].T
        else:
            P_comb, rc = P_Omega, 0
        n_even_c, n_odd_c, leak_c, evals_c = gamma_even_odd_split(P_comb)
        GRADING[(alg_name, lbl)] = (n_even, n_odd, leak, n_even_c, n_odd_c, rc, leak_c)

# print a compact representative row (D_F#0, both algebras) + confirm stability across all 7/2
rep = ALL_DF[0][0]
for alg_name in ("PRIMARY", "COMPARISON"):
    n_even, n_odd, leak, n_even_c, n_odd_c, rc, leak_c = GRADING[(alg_name, rep)]
    print(f"    [{alg_name}, {rep}]  raw Omega^1: dim={n_even+n_odd} (even/gauge-like={n_even}, "
          f"odd/Higgs-like={n_odd}, leak={leak:.2e})")
    print(f"    [{alg_name}, {rep}]  symmetrized A+J_F.A.J_F^-1: dim={rc} (even/gauge-like={n_even_c}, "
          f"odd/Higgs-like={n_odd_c}, leak={leak_c:.2e})")
grading_uniform = len({(v[0], v[1]) for k, v in GRADING.items() if k[0] == "PRIMARY"}) == 1
print(f"    grading pattern (even_dim,odd_dim) uniform across all 7 D_F's for PRIMARY? {grading_uniform}")
check(f"IF-1 gamma_F-grading computed for all {len(ALL_DF)*2} (D_F,algebra) combinations "
      f"(raw + symmetrized) without error", True)

IF1_PASS = ok_all
print(f"\n    IF-1 VERDICT: {'PASS' if IF1_PASS else '*** FAIL ***'}")

# ====================================================================================================
banner("IF-2  THE GAUGE/HIGGS DECOMPOSITION  (Connes' anatomy, instantiated)")
# ====================================================================================================
print("""    Method: the su(3)-adjoint action on Hermitian operators is represented by the REAL-LINEAR,
    Hermitian-preserving map L_a(X) := i[T^a,X] (a=1..8); the quadratic Casimir superoperator
    C2 := -sum_a L_a.L_a is symmetric positive-semi-definite (each L_a is antisymmetric w.r.t. the
    Tr(XY) inner product, so L_a.L_a is symmetric negative-semi-definite; the minus sign flips to the
    physics convention where C2(adjoint)>0).  CALIBRATION (native units, not assumed): diagonalize C2 on
    the FULL 64-dim Hermitian-operator space FIRST (irrep content of End(Fock) under su(3)'s own adjoint
    action), cluster the eigenvalues, and use those clusters as the reference dictionary -- then read
    Omega^1's own restricted C2 spectrum against that SAME dictionary (no external "3" assumed).""")


def build_L_full(T):
    L = np.zeros((64, 64))
    for m in range(64):
        comm = 1j * (T @ HERM_BASIS[m] - HERM_BASIS[m] @ T)
        L[:, m] = coeffs_of(comm).real
    return L


def cluster_eigs(evals, tol=1e-6):
    order = np.argsort(evals)
    ev = evals[order]
    clusters = []
    cur = [ev[0]]
    for v in ev[1:]:
        if abs(v - cur[-1]) < tol * max(1.0, abs(ev[-1])):
            cur.append(v)
        else:
            clusters.append((float(np.mean(cur)), len(cur)))
            cur = [v]
    clusters.append((float(np.mean(cur)), len(cur)))
    return clusters


L_full_su3 = [build_L_full(T) for T in su3_gens_F]
C2_full = -sum(L @ L for L in L_full_su3)
C2_full = (C2_full + C2_full.T) / 2
evals_full = np.linalg.eigvalsh(C2_full)
CAL_CLUSTERS = cluster_eigs(evals_full)
print(f"    CALIBRATION -- su(3) Casimir spectrum of the FULL 64-dim Hermitian-operator space "
      f"(End(Fock) under ad_su3), (value, multiplicity):")
for val, mult in CAL_CLUSTERS:
    print(f"        {val:>10.5f}   x{mult}")

# The DEFINITIONAL adjoint reference (not a multiplicity-based guess): su3_gens_F THEMSELVES transform
# in the adjoint representation under their OWN adjoint action, by construction (ad_{T^b}(T^a) =
# [T^b,T^a] = i f^{bac} T^c) -- this is the textbook-unambiguous way to read off "C2(adjoint) in native
# units", no heuristic needed.  (An earlier version of this file picked the LARGEST-multiplicity nonzero
# global cluster as a proxy for "adjoint" -- WRONG, caught by this direct check: that cluster is actually
# the FUNDAMENTAL/ANTIFUNDAMENTAL value, see the ratio cross-check below.)
Madj = np.array([coeffs_of(T).real for T in su3_gens_F]).T   # (64,8)
Qadj, _ = np.linalg.qr(Madj)
rank_adj = np.linalg.matrix_rank(Madj)
C2_adj_sub = Qadj.T @ C2_full @ Qadj
evals_adj = np.linalg.eigvalsh((C2_adj_sub + C2_adj_sub.T) / 2)
adj_degeneracy_spread = float(np.max(evals_adj) - np.min(evals_adj))
X_ADJ = float(np.mean(evals_adj))
check(f"IF-2 calibration: C2 restricted to span{{su3_gens_F}} (the adjoint rep BY DEFINITION) is "
      f"degenerate to spread {adj_degeneracy_spread:.2e} (rank={rank_adj}==8) -- "
      f"C2_native(adjoint) = {X_ADJ:.5f}", adj_degeneracy_spread < 1e-6 and rank_adj == 8)
# cross-check: the global calibration's clusters, expressed as ratios to X_ADJ, against textbook su(3)
# Casimir ratios (C2(fund)/C2(adj)=(4/3)/3=4/9; C2(sextet)/C2(adj)=(10/3)/3=10/9) -- printed raw, not
# assumed; confirms which OTHER clusters are "fundamental/antifundamental-shaped" vs "sextet-shaped".
print(f"    global-cluster ratios to C2_native(adjoint)={X_ADJ:.5f}  (textbook: fund/adj=4/9=0.4444, "
      f"sextet/adj=10/9=1.1111):")
for val, mult in CAL_CLUSTERS:
    if abs(val) > 1e-6:
        print(f"        {val:.5f} / {X_ADJ:.5f} = {val/X_ADJ:.4f}   (mult {mult})")

Qvals = np.array([len(S) / 3.0 for S in SUBSETS])


def q_charge_weights(P_Omega):
    r = P_Omega.shape[1]
    weights = {}
    total = 0.0
    for k in range(r):
        Dk = matrix_of(P_Omega[:, k])
        for i in range(8):
            for j in range(8):
                w = float(abs(Dk[i, j]) ** 2)
                if w < 1e-16:
                    continue
                delta = round((Qvals[i] - Qvals[j]) * 3) / 3.0
                weights[delta] = weights.get(delta, 0.0) + w
                total += w
    return weights, total


print("\n    Per-D_F irrep content + Q-charge spectrum of Omega^1_PRIMARY (the physical claim):")
IF2_ROWS = []
for lbl, D_F in ALL_DF:
    P_Omega, r = OMEGA1[("PRIMARY", lbl)]
    if r == 0:
        IF2_ROWS.append((lbl, [], {}))
        continue
    L_sub = [P_Omega.T @ L @ P_Omega for L in L_full_su3]
    leak_su3 = max(float(np.max(np.abs((np.eye(64) - P_Omega @ P_Omega.T) @ L @ (P_Omega @ P_Omega.T))))
                    for L in L_full_su3)
    C2_sub = -sum(L @ L for L in L_sub)
    C2_sub = (C2_sub + C2_sub.T) / 2
    evals_sub = np.linalg.eigvalsh(C2_sub)
    clusters_sub = cluster_eigs(evals_sub, tol=1e-5)
    qw, qtot = q_charge_weights(P_Omega)
    IF2_ROWS.append((lbl, clusters_sub, qw))
    print(f"    [{lbl}]  dim={r}  su3-ad-leak={leak_su3:.2e}")
    print(f"        Casimir clusters (value,mult): "
          + "; ".join(f"{v:.4f}x{m}" for v, m in clusters_sub))
    print(f"        Q-charge blocks (delta_Q: weight): "
          + "; ".join(f"{d:+.3f}: {w:.4f}" for d, w in sorted(qw.items())))

# identify adjoint content in Omega^1 (use D_F#0 as representative; IF-1 found the grading pattern
# UNIFORM across all 7 D_F's for PRIMARY, and the Casimir-cluster patterns above are printed for all 7
# so any exception would already be visible in the per-D_F table).
rep_lbl, rep_clusters, rep_qw = IF2_ROWS[0]
ADJOINT_TOL = 1e-3  # relative tolerance against the DEFINITIONAL native calibration unit X_ADJ
has_adjoint = any(abs(v - X_ADJ) < ADJOINT_TOL * abs(X_ADJ) for v, m in rep_clusters if abs(v) > 1e-6)
n_even_rep, n_odd_rep = GRADING[("PRIMARY", rep_lbl)][0], GRADING[("PRIMARY", rep_lbl)][1]
has_qcharged_odd = any(abs(d) > 1e-6 for d in rep_qw) and n_odd_rep > 0
has_q0_singlet = any(abs(d) < 1e-6 for d in rep_qw)

print(f"\n    [{rep_lbl}] Omega^1_PRIMARY's own Casimir clusters {rep_clusters} vs "
      f"C2_native(adjoint)={X_ADJ:.5f}: adjoint content present? {has_adjoint}")
print(f"    [{rep_lbl}] SUMMARY: Q-charged content present? {any(abs(d)>1e-6 for d in rep_qw)}  "
      f"(gamma_F-odd dims = {n_odd_rep}/{n_odd_rep+n_even_rep} from IF-1 => ALL of Omega^1 is Higgs-like)")
print(f"    [{rep_lbl}] SUMMARY: Q=0 (uncharged) component present? {has_q0_singlet}")
print("    CONFRONT with the derived charge dictionary (FS-3, Q=Nhat/3, spectrum {0,1/3x3,2/3x3,1}): "
      "Omega^1's Q-charge blocks are BY CONSTRUCTION the same 1/3-quantized unit (same Q operator is "
      "reused verbatim, not re-derived) -- this is a consistency restatement, not a new derivation.")

if has_adjoint and has_qcharged_odd:
    IF2_VERDICT = "ANATOMY-MATCHED"
    print(f"""
    IF-2 VERDICT: ANATOMY-MATCHED (structure level only, per adjudication -- NO magnitude claim).
    Omega^1_PRIMARY contains BOTH an adjoint-of-su(3)-transforming piece (Casimir = {X_ADJ:.4f}, matching
    the DEFINITIONAL native adjoint reference to {ADJOINT_TOL:.0e}) AND a Q-charged component -- and
    (IF-1) that ENTIRE space is gamma_F-odd (Higgs-like), never gauge-like.  IMPORTANT CAVEAT: in Connes'
    textbook anatomy the gauge bosons (adjoint-transforming) are gamma_F-EVEN and the Higgs (Q-charged) is
    gamma_F-ODD; here the adjoint-transforming piece is ITSELF gamma_F-odd too (forced, since A_F is
    entirely gamma_F-even and D_F entirely gamma_F-odd -- IF-1), so this is an "octet-Higgs"-shaped
    object, not a color-octet gauge boson.""")
else:
    IF2_VERDICT = "ANATOMY-OTHER"
    rep_clusters_fmt = [(round(v, 4), m) for v, m in rep_clusters]
    print(f"""
    IF-2 VERDICT: ANATOMY-OTHER. Omega^1_PRIMARY's own Casimir clusters ({rep_clusters_fmt}) do NOT contain
    the adjoint-of-su(3) eigenvalue (C2_native(adjoint) = {X_ADJ:.5f}, established via the DEFINITIONAL
    calibration on span{{su3_gens_F}} above, degenerate to < 1e-6) -- adjoint present: {has_adjoint};
    Q-charged gamma_F-odd part present: {has_qcharged_odd}.  Instead, reading the global-cluster ratio
    cross-check above, Omega^1_PRIMARY's own nonzero clusters ({[f'{v:.4f}' for v,m in rep_clusters if abs(v)>1e-6]})
    sit at ratio {[f'{v/X_ADJ:.4f}' for v,m in rep_clusters if abs(v)>1e-6]} relative to C2_native(adjoint)
    -- i.e. FUNDAMENTAL/ANTIFUNDAMENTAL-shaped (ratio ~4/9) and SEXTET-shaped (ratio ~10/9) content, plus
    a Q=+-1, su(3)-singlet (Casimir 0) piece -- but NO su(3)-adjoint-shaped piece at all.  So Omega^1(D_F
    alone) supplies Q-charged, gamma_F-odd (Higgs-like) matter that transforms as color triplet/
    antitriplet + sextet + singlet pieces under su(3) -- richer than a single SM-Higgs doublet's su(3)
    content (which is a color SINGLET), but it does NOT reproduce "a gauge-boson-shaped (adjoint) piece
    living in the Higgs sector" the way the earlier (incorrect) reading of this calibration suggested --
    that reading used a flawed largest-multiplicity heuristic for "adjoint" which this corrected,
    DEFINITIONAL calibration (C2 restricted to span{{su3_gens_F}} itself) supersedes.""")

IF2_DEFINITE = IF2_VERDICT in ("ANATOMY-MATCHED", "ANATOMY-OTHER")
check(f"IF-2 reaches a definite verdict: {IF2_VERDICT}", IF2_DEFINITE)

# ====================================================================================================
banner("IF-3  THE GAUGE-ROW SHAPE  (the internal second moment, confronted with -3C2+Tf+TH)")
# ====================================================================================================
print("""    Construction (fixed by IF-0/1's objects BEFORE this confront runs, per the poison -- no
    per-group tuning): for each group generator set {T^a} (su(3): the 8 su3_gens_F; u(1)_Q: QCHG_F
    alone), the internal second moment is
        weight(G, D_F) := sum_a Tr( [D_F,T^a]^dagger . [D_F,T^a] )     (a Dynkin-index-shaped, manifestly
    non-negative quadratic form -- Tr(M^dagger M) >= 0 for ANY M, term by term).  This is composed with
    the cone side via d4_spectral_action's OWN endomorphism_E/fermion_2sz2 pattern (imported, not
    rebuilt): cone_factor := d4.fermion_2sz2() = (1/2)tr(E^2) on the A5(b) Weyl for a unit field strength,
    the SAME universal (group-independent) constant used to build the native fermion beta-row.  The
    su(2) row is NOT-CONSTRUCTIBLE here: A_F (FS-3/FS-4) carries no weak-isospin generators at all
    (hypercharge/SU(2) live in the edge-qubit/doubling sector, explicitly out of scope -- FS-6/IF-5).""")

cone_factor = d4.fermion_2sz2()
print(f"    cone_factor = d4.fermion_2sz2() = {cone_factor:.6f}  (imported, universal, same for every group)")

f_content, h_content = d4.sm_content()
target_b = d4.beta_rows(f_content, h_content)
print(f"    TARGET (imported, unchanged): b_i = -3*C2(G)+Tf+TH = "
      f"{{1(u1): {target_b[1]}, 2(su2): {target_b[2]}, 3(su3): {target_b[3]}}}")

print("\n    Per-D_F raw weights (su(3), u(1)_Q) and the su3:u1 ratio:")
IF3_ROWS = []
for lbl, D_F in ALL_DF:
    w_su3 = sum(float(np.real(np.trace((D_F @ T - T @ D_F).conj().T @ (D_F @ T - T @ D_F))))
                for T in su3_gens_F)
    w_u1 = float(np.real(np.trace((D_F @ QCHG_F - QCHG_F @ D_F).conj().T
                                   @ (D_F @ QCHG_F - QCHG_F @ D_F))))
    ratio = (w_u1 / w_su3) if abs(w_su3) > 1e-14 else float("nan")
    IF3_ROWS.append((lbl, w_su3, w_u1, ratio))
    print(f"    {lbl:<16}  weight(su3)={w_su3:.6e}  weight(u1)={w_u1:.6e}  ratio(u1/su3)={ratio:.6f}")

target_ratio = float(target_b[1]) / float(target_b[3])
print(f"\n    TARGET ratio b1/b3 = ({target_b[1]})/({target_b[3]}) = {target_ratio:.6f}")
our_ratios = [r for *_, r in IF3_ROWS if not math.isnan(r)]
mean_ratio = float(np.mean(our_ratios)) if our_ratios else float("nan")
print(f"    Our ratio(u1/su3), mean over the 7 D_F's = {mean_ratio:.6f}  (all individually printed above)")

sign_ok = mean_ratio < 0 if not math.isnan(mean_ratio) else False
dev_after_norm = abs(mean_ratio - target_ratio)
print(f"    deviation |our_ratio - target_ratio| = {dev_after_norm:.6f}")

if sign_ok and dev_after_norm < 1e-9:
    IF3_VERDICT = "SHAPE-MATCHED"
else:
    IF3_VERDICT = "SHAPE-MISS"
    print(f"""
    STRUCTURAL REASON (not a fit failure, a construction-level fact): weight(G,D_F) is, term by term, a
    trace of a positive-semi-definite operator [D_F,T^a]^dagger[D_F,T^a] -- it is ALGEBRAICALLY FORCED
    to be >= 0 for every group.  So our_ratio(u1/su3) = weight(u1)/weight(su3) >= 0 always (both computed
    values above are strictly positive).  The TARGET ratio b1/b3 = {target_ratio:.4f} is NEGATIVE, because
    b3 = -3*C2(SU(3)) < 0: that entry is the GAUGE-BOSON SELF-ENERGY (asymptotic-freedom gluon-loop) term
    of the one-loop beta function, a qualitatively DIFFERENT diagram (vector self-interaction) from a
    matter/Higgs-loop quadratic form like Tr([D_F,T]^2).  No single overall real normalization c can turn
    a non-negative ratio into a negative one (c cancels exactly in the ratio) -- SHAPE-MISS is FORCED by
    this sign structure alone, not by any numerical coincidence.  This is exactly the sharpened wall the
    pre-reg anticipated: Omega^1(D_F) supplies matter/Higgs-loop-shaped content ONLY; it structurally
    cannot carry the gauge-self-energy (-3C2(G)) part of the target row.  The su(2) row (b2=1) is
    NOT-CONSTRUCTIBLE (no su(2) generators in A_F) -- only 2 of 3 rows are even comparable, and both
    available rows fail the sign test the same way.""")

print(f"\n    IF-3 VERDICT: {IF3_VERDICT}")
IF3_DEFINITE = IF3_VERDICT in ("SHAPE-MATCHED", "SHAPE-MISS")
check(f"IF-3 reaches a definite verdict: {IF3_VERDICT}", IF3_DEFINITE)

# ====================================================================================================
banner("IF-4  THE OBLIQUE CONFRONT  (the falsifiable crux -- Gamma-point first; may be NOT-WELL-POSED)")
# ====================================================================================================
print("""    DOCUMENTED FLOOR NUMBERS (quoted as history/comparison ONLY, per the pre-reg -- the M_Z
    scoreboard value does NOT move in this station under any verdict): substrate oblique 0.3431% vs SM
    0.3570%, gap 0.0139% (3.9% relative) -- 2026-06-30 theorem doc.  read_obliques() (derivation_topdown/
    bridge/the_run.py ~461-471) supplies the cone-side delta_r/drho/S from this SAME framework.

    THE ATTEMPT (Gamma-point, k=(0,0,0)): read_obliques()'s ENTIRE construction is built from
        c_S = gauge_singlet_projection(hashimoto(k))       -- the Perron spectral projector of the SRS
                                                               COVER's non-backtracking operator B(k),
        g_P, g_E = cavity_gf(LAM_PERRON), cavity_gf(2*sqrt(K-1))  -- tree-cavity Green's functions of the
                                                               SAME cover walker, evaluated at specific
                                                               points of the adjacency spectrum,
        h = ihara_bass_root(...), F = Feshbach functional, c_EW = 0.5 (a stated EW normalization).
    Every one of these lives on the srs COVER's dart space (dimension 2|E|, a purely GEOMETRIC/spacetime
    object -- the walker on the graph).  NONE of them references the internal Cl(6) Fock, D_F, A_F,
    Omega^1, su3_gens_F, or QCHG_F in any way -- inspected directly in the_run.py's source (quoted
    above): the internal-flavor sector and the oblique-parameter machinery are built from two
    STRUCTURALLY DISJOINT Hilbert spaces (the 8-dim internal Fock vs. the 2|E|-dim cover-dart space),
    with NO existing map between them anywhere in the framework.

    A NAIVE ansatz was considered and REJECTED (not run, to avoid inventing a number): multiplying
    delta_r/drho/S by the IF-3 internal weight ratios (mirroring how beta_rows multiplies a UNIVERSAL a4
    coefficient by group Dynkin sums) would require CHOOSING how the internal Fock's operators couple to
    the cover walker's current operators -- there is no derived vertex/propagator for that coupling
    anywhere upstream (IF-0..3 built objects WITHIN the internal Fock only).  Inventing one now to get a
    number would be exactly the goal-seeking the poisons forbid.""")

MISSING_OBJECT = ("a vertex/propagator map embedding the internal Cl(6) Fock's derived operators "
                   "(A_F / Omega^1, living on the 8-dim internal flavor space) into the SRS cover's "
                   "current-current polarization machinery (hashimoto/cavity_gf, living on the 2|E|-dim "
                   "cover-dart space) that read_obliques() is built from -- i.e., the internal-fluctuation "
                   "ANALOGUE of a Yukawa or gauge vertex coupling the D_F-fluctuation field to the cone's "
                   "fermion propagator.  No such object is constructed anywhere in the framework "
                   "(engine, adapters, or any prior proofs/ station); IF-0..3 above exhaust what can be "
                   "built purely WITHIN the internal Fock.  This is the correctly-named next station's "
                   "target -- constructing it now, with no other guide than 'reproduce the 0.0139% gap', "
                   "would be pure goal-seeking.")
print(f"\n    MISSING OBJECT (named precisely): {MISSING_OBJECT}")

IF4_VERDICT = "NOT-WELL-POSED"
print(f"""
    Gamma-point trigger check: the BZ-40 escalation is declared to fire "only if the Gamma-point result
    is nonzero" -- there IS no well-posed Gamma-point result to test for nonzero-ness (not even a
    provable zero), so the escalation condition does not apply; this is exactly the NOT-WELL-POSED branch,
    not a (silently smaller) OBLIQUE-NULL.

    IF-4 VERDICT: {IF4_VERDICT} -- the internal fluctuation sector built in IF-0..3 has no existing,
    non-invented coupling into read_obliques()'s polarization machinery.  Comparison only (NOT a scoreboard
    change): documented substrate oblique 0.3431% vs SM 0.3570% (gap 0.0139%, 3.9% relative) stands
    exactly as before this station ran.""")
IF4_DEFINITE = IF4_VERDICT in ("OBLIQUE-CONTRIBUTION-FOUND", "OBLIQUE-NULL", "NOT-WELL-POSED")
check(f"IF-4 reaches a definite verdict: {IF4_VERDICT}", IF4_DEFINITE)

# ====================================================================================================
banner("IF-5  SCOPE DECLARATION  (printed verbatim from the pre-reg)")
# ====================================================================================================
print("""    NOT claimed: any M_Z/scoreboard movement; any Higgs MAGNITUDE (D2 owns the potential; IF-2 is
    structure only); the Gilkey universal coefficients (still the named import); a full Connes
    spectral-action reconstruction (one SM generation's algebra =/= our derived algebra -- the PRIMARY
    A_F is the framework's own, and that difference is the point).""")

# ====================================================================================================
banner("SUMMARY")
# ====================================================================================================
runtime_s = time.time() - t_start
print(f"    IF-0 ANCHORS ............................. {'PASS' if IF0_PASS else 'FAIL'}")
print(f"    IF-1 ONE-FORM SPACE ....................... {'PASS' if IF1_PASS else 'FAIL'} "
      f"(dim Omega^1_PRIMARY={OMEGA1[('PRIMARY', ALL_DF[0][0])][1]}, "
      f"dim Omega^1_COMPARISON={OMEGA1[('COMPARISON', ALL_DF[0][0])][1]}; "
      f"all-odd/Higgs-like at leak~1e-15; D_F-(in)dependence borderline at ~1e-8, see caveat above)")
print(f"    IF-2 GAUGE/HIGGS DECOMPOSITION ............ {IF2_VERDICT}")
print(f"    IF-3 GAUGE-ROW SHAPE ...................... {IF3_VERDICT}")
print(f"    IF-4 OBLIQUE CONFRONT ..................... {IF4_VERDICT}")
print(f"    IF-5 SCOPE DECLARATION .................... printed above")
print(f"    runtime = {runtime_s:.1f} s")
print()

EXIT_OK = IF0_PASS and IF1_PASS and IF2_DEFINITE and IF3_DEFINITE and IF4_DEFINITE
print(f" OVERALL: {'ALL CONTRACTS REACHED THEIR DECLARED OUTCOMES' if EXIT_OK else '*** SOME CONTRACT FAILED ***'}  "
      f"(exit condition: IF-0/IF-1 pass AND IF-2/IF-3/IF-4 definite = {EXIT_OK})")
print("=" * 100)
sys.exit(0 if EXIT_OK else 1)
