#!/usr/bin/env python3
# ============================================================
# g_A reduction — native 3-WALKER COMPOSITE test. Does the color-singlet junction
# correlate the three walkers' chiralities enough to reduce the axial charge,
# or does the framework conserve it at the composite level too?
# ============================================================
#
# Scope: the decisive end of the native g_A thread.
# Predecessor gA_native_multiway_walker_2026-06-02.py (committed 28e61e1): a SINGLE
# walker CONSERVES chirality magnitude under the non-backtracking Hashimoto dynamics
# (|R(L)|=1 for all L, both natural Clifford transports) -> native single-walker
# g_A = 5/3, no reduction. The open fork: the g_A reduction must then live in either
#   (a) the MULTI-WALKER (3-quark) COMPOSITE chirality combination, or
#   (b) genuinely outside the framework's native walker+junction dynamics.
# This probe resolves (a) vs (b).
#
# THE DECISIVE QUESTION (sharp + computable). A single walker conserves chirality,
# so the composite axial charge is reduced ONLY if the junction ANTI-correlates the
# three chiralities (partial cancellation). The junction's defining structure is the
# COLOR-SINGLET (antisymmetric color, the baryon vertex). So:
#
#     does color (SU(4)_PS, in which SU(3)_color sits) COMMUTE with chirality?
#
#   - If [SU(4), gamma_chiral] = 0: color-antisymmetrization cannot touch chirality.
#     All three quarks stay in the SAME chirality sector -> composite chirality is
#     co-aligned (+3), no cancellation -> NO reduction -> fork resolves to (b).
#   - SU(4)_PS = Spin(6) is generated by the Clifford BIVECTORS gamma^a gamma^b
#     (even grade), which commute with the volume element gamma_chiral. So the
#     expectation is 0 -- but we COMPUTE it, not assume.
#
# This is native: it uses the framework's actual Cl(6) spinor + Spin(6)=SU(4)_PS
# structure + gamma_chiral (substrate_state op_5_8/5_9), and the dynamical
# chirality conservation already MEASURED in the single-walker run. Nothing imported.

import os, sys
import numpy as np
from itertools import combinations

# ---- Cl(6) gammas + chirality (exact substrate_state op_5_6/5_8/5_9 convention) ----
I2 = np.eye(2, dtype=complex)
sx = np.array([[0, 1], [1, 0]], dtype=complex)
sy = np.array([[0, -1j], [1j, 0]], dtype=complex)
sz = np.array([[1, 0], [0, -1]], dtype=complex)
sm, sp = (sx - 1j * sy) / 2, (sx + 1j * sy) / 2


def kron_chain(*m):
    out = m[0]
    for x in m[1:]:
        out = np.kron(out, x)
    return out


def site(j, op, N=3):
    return kron_chain(*[sz if k < j else (op if k == j else I2) for k in range(N)])


c = [site(j, sm) for j in range(3)]
cd = [site(j, sp) for j in range(3)]
G = []
for j in range(3):
    G.append(c[j] + cd[j])
    G.append(1j * (c[j] - cd[j]))
prod = np.eye(8, dtype=complex)
for g in G:
    prod = prod @ g
GC = -1j * prod                                  # gamma_chiral
P_plus = (np.eye(8) + GC) / 2                    # chirality +1 sector ("quarks", the 4 of SU(4))
P_minus = (np.eye(8) - GC) / 2


def comm(A, B):
    return A @ B - B @ A


def main():
    print("=" * 78)
    print(" g_A — native 3-WALKER COMPOSITE: does the color-singlet junction reduce it?")
    print("=" * 78)

    # ---- gates ----
    print("\n[gates]")
    print(f"  gamma_chiral^2 = I : {np.allclose(GC@GC, np.eye(8), atol=1e-12)}")
    print(f"  gamma_chiral Hermitian : {np.allclose(GC, GC.conj().T, atol=1e-12)}")
    rk_plus = int(np.round(np.trace(P_plus).real))
    rk_minus = int(np.round(np.trace(P_minus).real))
    print(f"  chirality sectors: dim(P_+) = {rk_plus}, dim(P_-) = {rk_minus}  "
          f"(SU(4)_PS reps 4 + 4bar)")

    # ---- THE decisive computation: do the SU(4)=Spin(6) generators (bivectors)
    #      commute with gamma_chiral? color SU(3) sits inside, so this settles it ----
    print("\n[1] SU(4)_PS = Spin(6) generators (15 Clifford bivectors gamma^a gamma^b):")
    bivectors = [G[a] @ G[b] for a, b in combinations(range(6), 2)]
    print(f"    count = {len(bivectors)} (= dim SU(4))")
    max_comm = max(np.max(np.abs(comm(Bv, GC))) for Bv in bivectors)
    print(f"    max ||[bivector, gamma_chiral]|| over all 15 = {max_comm:.2e}")
    commute = max_comm < 1e-12
    print(f"    => SU(4)_PS (and SU(3)_color inside it) {'COMMUTES with' if commute else 'does NOT commute with'} chirality.")
    if commute:
        print("    => any color/flavor operation (incl. the color-singlet antisymmetrization)")
        print("       PRESERVES each walker's chirality sector. It cannot anti-correlate")
        print("       the three chiralities. (Contrast: a single gamma^e -- the WALK")
        print("       transport, odd grade -- flips chirality; but color is even-grade.)")
    # show a single gamma (odd) does NOT commute, to make the grade point concrete
    odd_comm = np.max(np.abs(comm(G[0], GC) + comm(G[0], GC)))  # anticommutes
    print(f"    sanity: single gamma^1 ANTIcommutes with gamma_chiral "
          f"(||{{g,GC}}|| = {np.max(np.abs(G[0]@GC + GC@G[0])):.2e}); it is the walk step, not color.")

    # ---- [2] the composite axial charge: 3 quarks (all chirality +1) at the junction ----
    print("\n[2] composite chirality of the color-singlet 3-quark junction:")
    print("    a quark = a state in P_+ (chirality +1). The color-singlet is an")
    print("    antisymmetric combination over the color index, which lives ENTIRELY")
    print("    inside P_+ (color commutes with chirality, [1]).")
    # build 3 quark states in P_+ (any basis of the 4-dim +sector), form an
    # antisymmetric (color-singlet-like) combination, measure composite <sum gamma_chiral>.
    # basis of P_+:
    evals, evecs = np.linalg.eigh(GC)
    plus_basis = evecs[:, np.abs(evals - 1) < 1e-9]      # 8x4
    # three "colors" = three orthonormal quark states in P_+
    q = [plus_basis[:, i] for i in range(3)]
    # composite axial-charge (chirality) operator on the 3-walker tensor space:
    # Sigma = gamma_chiral⊗I⊗I + I⊗gamma_chiral⊗I + I⊗I⊗gamma_chiral
    I8 = np.eye(8)
    Sigma = (np.kron(np.kron(GC, I8), I8) + np.kron(np.kron(I8, GC), I8)
             + np.kron(np.kron(I8, I8), GC))
    # antisymmetric color-singlet over the 3 quark states (epsilon_ijk):
    from itertools import permutations
    def sign(p):
        s = 1
        p = list(p)
        for i in range(len(p)):
            for j in range(i + 1, len(p)):
                if p[i] > p[j]:
                    s = -s
        return s
    psi = np.zeros(8 ** 3, dtype=complex)
    for perm in permutations(range(3)):
        psi += sign(perm) * np.kron(np.kron(q[perm[0]], q[perm[1]]), q[perm[2]])
    psi /= np.linalg.norm(psi)
    chir = (psi.conj() @ Sigma @ psi).real
    print(f"    <sum_i gamma_chiral(i)> on the color-singlet 3-quark state = {chir:+.4f}")
    print(f"    (= +3: all three co-aligned, NO cancellation -> chirality reduction factor 1)")

    # ---- verdict ----
    print("\n" + "=" * 78)
    print(" VERDICT — the composite does NOT reduce g_A either (fork resolves to (b))")
    print("=" * 78)
    no_reduction = commute and abs(chir - 3.0) < 1e-9
    print(f"""  Three native facts, combined:
   1. A SINGLE walker conserves chirality magnitude under the non-backtracking
      dynamics (|R(L)|=1, measured in gA_native_multiway_walker).
   2. SU(4)_PS -- hence SU(3)_color -- COMMUTES with gamma_chiral (max commutator
      {max_comm:.1e}), because color is generated by even-grade bivectors. So the
      color-singlet junction CANNOT anti-correlate the chiralities.
   3. The color-singlet 3-quark state therefore has all three chiralities co-aligned:
      <sum gamma_chiral> = {chir:+.1f} (chirality reduction factor = 1, exactly).

  => the COMPOSITE axial charge is NOT reduced. Native 3-walker g_A = (spin-flavor
     SU(6) sum) x 1 = 5/3, EXACTLY. The fork resolves to (b): the framework does
     NOT natively produce the g_A reduction -- not at the single-walker level, not
     at the composite. The 5/3 -> 1.27 reduction is genuinely OUTSIDE the native
     walker + junction dynamics.

  WHY this is consistent: the walk transport is odd-grade (single gamma^e, flips
  chirality but conserves |chirality|); color/flavor are even-grade (bivectors,
  preserve chirality); and the BINDING is chirality-blind (Stage-2 finding). None
  of the framework's native operations DILUTES the axial charge. A reduction needs
  a MIXED-grade, chirality-DILUTING interaction the framework does not contain.

  HONEST NET for g_A: LO 5/3 is the framework's genuine native answer. The observed
  1.2723 reduction is real QCD physics (relativistic + sea/pion-cloud) that the
  framework's substrate dynamics does not reproduce. The static-arc ~1.44 was an
  IMPORTED-Melosh artifact, now fully retired. The ~26 sigma Y_p lever's g_A leg is
  NOT closable within the native framework as it stands. {'CONFIRMED' if no_reduction else 'CHECK FAILED'}.""")
    print("=" * 78)


if __name__ == "__main__":
    main()
