#!/usr/bin/env python3
"""
P1.O3 -- Observer-side martingale time (dynamics phase 1, 2026-05-25).

CONJECTURE: the observer's filtration sigma-algebra F_N (generated by the first
N observations on the substrate's Bayesian observation walk) makes any
F_∞-measurable indicator's posterior probability a martingale. The natural
discrete time index is N (count of observations), and "observer time"
t = N · t_P is unique and forced by the framework's A2-T axiom (Jaynes-
uniform → i.i.d. observation structure → posterior is a martingale).

WHAT THIS TESTS (three falsification gates):
  (a) Martingale property of the posterior:
        Var[ posterior_{N+1} | F_N ] is finite + E[ posterior_{N+1} | F_N ]
        = posterior_N (the latter holds analytically by construction of
        Bayesian posteriors; we verify by Monte Carlo across realizations).
  (b) Doob L2 convergence: posterior_N → indicator_of_truth as N → ∞ in
        L2 (variance → 0). Equivalently: under the TRUE hypothesis,
        posterior_N → 1 a.s. (Doob consistency).
  (c) Convergence rate matches the theoretical rate: per-observation
        log-likelihood ratio under truth has expectation = KL divergence
        between the two hypotheses; posterior(false)/posterior(true)
        decays as exp(-N · KL) on average.

SETUP:
  - True substrate: srs primitive cell (4 atoms, 12 directed edges).
    Walker takes NB steps with Jaynes-uniform measure (each of the 2 NB
    continuations has probability 1/2). This is the framework's A2-T
    prediction (walker_dynamics_derivation §4a).
  - Observer hypotheses:
      H_uniform : framework's prediction (Jaynes-uniform, p = 1/2 each)
      H_biased  : alternative (one of the 2 NB continuations has p = 0.7,
                  the other p = 0.3; chosen at each edge by a fixed pseudo-
                  random rule independent of observations)
  - Prior: P_0(H_uniform) = P_0(H_biased) = 1/2
  - Observations: each step gives the chosen NB continuation. Likelihood
    under H_uniform = 1/2 (always); under H_biased = 0.7 or 0.3 depending
    on which continuation was taken.
  - Posterior P_N(H_uniform) updates by Bayes after each observation.

THE THEORETICAL EXPECTATION:
  - Under the truth (H_uniform), posterior_N(H_uniform) → 1 a.s. (Doob).
  - KL(H_uniform || H_biased) per step = 0.5*log(0.5/0.7) + 0.5*log(0.5/0.3)
                                       = 0.0871 (nats).
  - Log-posterior-odds drift = N · KL ≈ 0.087 N.
  - Expected number of observations to reach 95% confidence: N ≈ log(19)/KL ≈ 34.

INTERPRETATION OF "OBSERVER TIME":
  - The observation index N is the natural discrete time on the observer's
    filtration. The framework's identification t = N · t_P means: one observer-
    time-tick = one substrate observation. This connects the observer's
    epistemic clock to the substrate's primitive time unit.
  - The martingale property of the posterior is the QUANTITATIVE statement
    of A2-T: rate-distortion → uniform product measure on toggle sequences
    → i.i.d. observation likelihoods under the true measure → posterior is a
    martingale → there is exactly one natural time index (N) on the filtration.

NO NEW PHYSICS CLAIMED. The Bayesian posterior martingale property is standard
(Doob, Levy). This probe verifies the standard property in the framework's
specific setup, establishing that "observer time = N" is the unique natural
discrete time on the observer's filtration.
"""

from __future__ import annotations

import os
import sys
import time

import numpy as np

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir, os.pardir))
sys.path.insert(0, REPO_ROOT)

from proofs.common import find_bonds  # noqa: E402
from proofs.foundations.theorem_B5_3_core import build_directed_edges  # noqa: E402

print("=" * 70)
print("P1.O3 -- Observer-side martingale time (2026-05-25)")
print("=" * 70)

# ------------------------------------------------------------------------
# Step 1: build the srs primitive cell adjacency for NB walks
# ------------------------------------------------------------------------
bonds = find_bonds()
directed = build_directed_edges(bonds)
N_EDGES = len(directed)
assert N_EDGES == 12

# Build NB continuation map: for each directed edge e, list of edges that
# are valid NB continuations (target(e) == source(e'), e' != reverse(e))
def reverse_edge(e):
    src, tgt, cell = e
    return (tgt, src, tuple(-c for c in cell))

# Cell offsets mod 1 (treat as if on a single primitive cell — periodic BC)
# For Bayesian inference, the cell offsets are irrelevant; what matters is
# which 2 of 12 directed edges are NB continuations of each edge. Build the
# adjacency as 12 lists of 2 indices each.
nb_continuations = [[] for _ in range(N_EDGES)]
edge_to_idx = {tuple(e): i for i, e in enumerate(directed)}

# To compute NB continuations on the cell with periodic BC, we use the fact
# that the bond list (src, tgt, cell_off) defines edges with their cell shift.
# We just need to know: starting at edge i, which edges j have src_j == tgt_i?
# Among those, exclude the reverse.
for i, (src_i, tgt_i, cell_i) in enumerate(directed):
    for j, (src_j, tgt_j, cell_j) in enumerate(directed):
        if src_j != tgt_i:
            continue
        # Is j the reverse of i? In the periodic-cell adjacency picture, the
        # reverse of (src, tgt, cell) is (tgt, src, -cell), which appears in
        # the bond list if it's a valid bond. Since all 12 bonds appear in
        # both directions, the reverse exists for every i.
        if tgt_j == src_i and tuple(cell_j) == tuple(-c for c in cell_i):
            continue
        nb_continuations[i].append(j)

# Verify each edge has exactly 2 NB continuations (k-1 = 2)
for i, nbs in enumerate(nb_continuations):
    assert len(nbs) == 2, f"Edge {i} has {len(nbs)} NB continuations (expected 2)"
print(f"\nNB continuation map: each of {N_EDGES} edges has 2 NB continuations (verified).")


# ------------------------------------------------------------------------
# Step 2: define the two hypotheses
# ------------------------------------------------------------------------
print("\nDefining hypotheses:")
print("  H_uniform (truth): each of 2 NB continuations has p = 1/2")
print("  H_biased:          each of 2 NB continuations has p = 0.7 / 0.3")
print("                     (which is 0.7 vs 0.3: fixed per starting edge)")

# H_biased: for each starting edge, fix which of the 2 NB continuations gets
# p = 0.7 (the "preferred" continuation under H_biased). Use a seed for
# reproducibility.
rng_setup = np.random.default_rng(20260525)
bias_rule = np.zeros(N_EDGES, dtype=int)  # bias_rule[e] = index 0 or 1 indicating
                                            # which NB continuation gets p = 0.7
for e in range(N_EDGES):
    bias_rule[e] = rng_setup.integers(0, 2)

P_HIGH = 0.7
P_LOW = 0.3

def likelihood_uniform(e_curr, e_next_idx_in_nbs):
    """Likelihood of choosing NB continuation index 0 or 1 under H_uniform."""
    return 0.5

def likelihood_biased(e_curr, e_next_idx_in_nbs):
    """Likelihood of choosing NB continuation index 0 or 1 under H_biased."""
    if e_next_idx_in_nbs == bias_rule[e_curr]:
        return P_HIGH
    else:
        return P_LOW


# Theoretical per-step KL divergence
import math
KL_uniform_to_biased = (
    0.5 * math.log(0.5 / P_HIGH) + 0.5 * math.log(0.5 / P_LOW)
)
N_STEPS_EXPECT = math.log(19) / KL_uniform_to_biased  # 95% confidence
print(f"\nTheoretical KL(H_uniform || H_biased) per step = {KL_uniform_to_biased:.4f} nats")
print(f"Expected N to reach 95% posterior confidence ≈ {N_STEPS_EXPECT:.1f}")


# ------------------------------------------------------------------------
# Step 3: simulate many walks, track posterior trajectory
# ------------------------------------------------------------------------
N_WALKS = 5000
N_STEPS = 200
PRIOR_UNIFORM = 0.5

print(f"\nSimulating {N_WALKS} walks of {N_STEPS} steps each, under H_uniform (truth)")
print("Tracking posterior trajectory P_N(H_uniform) for each walk...")

rng = np.random.default_rng(20260525 + 1)

# Pre-allocate posteriors: posteriors[w, N] = P_N(H_uniform) for walk w
posteriors = np.zeros((N_WALKS, N_STEPS + 1), dtype=float)
posteriors[:, 0] = PRIOR_UNIFORM

t_start = time.time()

# Random starting edges, uniform
start_edges = rng.integers(0, N_EDGES, size=N_WALKS)

for w in range(N_WALKS):
    e_curr = start_edges[w]
    p_uniform = PRIOR_UNIFORM
    for step in range(N_STEPS):
        # Pick next NB continuation under TRUE measure (H_uniform: uniform)
        idx_in_nbs = rng.integers(0, 2)  # 0 or 1, uniform
        e_next = nb_continuations[e_curr][idx_in_nbs]
        # Compute Bayes update
        lik_u = likelihood_uniform(e_curr, idx_in_nbs)
        lik_b = likelihood_biased(e_curr, idx_in_nbs)
        # Posterior: P_uniform := P_uniform * lik_u / (P_uniform * lik_u + P_biased * lik_b)
        p_biased = 1.0 - p_uniform
        num = p_uniform * lik_u
        denom = num + p_biased * lik_b
        p_uniform = num / denom
        posteriors[w, step + 1] = p_uniform
        e_curr = e_next

print(f"  simulation: {time.time() - t_start:.1f}s")


# ------------------------------------------------------------------------
# Step 4: Falsification gates (a), (b), (c)
# ------------------------------------------------------------------------
print("\n" + "=" * 70)
print("FALSIFICATION GATES (P1.O3 plan)")
print("=" * 70)

# Gate (a): martingale property under the MARGINAL measure (mixture).
# For a Bayesian posterior, E[P_{N+1} | F_N] = P_N when expectation is under
# the marginal predictive distribution (the measure that the prior actually
# induces, i.e. mixture of hypotheses with their prior weights). Under the
# TRUE measure alone (H_uniform), the posterior is a SUB-martingale and
# drifts up toward 1, so a naive cross-walk average is misleading.
#
# Per-realization test of the martingale identity:
#   E[P_{N+1} | F_N] = P_N  where E is over the marginal predictive obs
# At each realized F_N (one walk's history), the next obs has predictive
# probability p_marg(obs|F_N) = P_N·lik_u(obs) + (1-P_N)·lik_b(obs).
# So the conditional expectation E[P_{N+1}|F_N]
#   = sum_obs p_marg(obs|F_N) * P_{N+1}(obs)
#   = sum_obs [P_N·lik_u + (1-P_N)·lik_b] * [P_N·lik_u / (P_N·lik_u + (1-P_N)·lik_b)]
#   = sum_obs P_N · lik_u
#   = P_N · sum_obs lik_u = P_N · 1 = P_N.  ✓
# This is an algebraic identity; we verify it numerically per realization.
print("(a) Marginal-predictive martingale property: E[P_{N+1}|F_N] = P_N")
print("    (per-realization check; uses marginal predictive p_marg over both")
print("     possible next-edges weighted by posterior+likelihood, not the")
print("     truth-only sample average which would give sub-martingale drift)")
print("    N  | walk idx | P_N      | E_marg[P_{N+1}|F_N] | |diff|      |")
gate_a_pass = True
max_dev = 0.0
for N in [10, 50, 100, 150]:
    for w in [0, 100, 1000]:
        # Reconstruct e_curr at step N for walk w. We need to re-trace the
        # walk; for simplicity, just re-simulate with the same seed offset.
        # Easier: at step N, we know the posterior P_N for walk w. The
        # *identity* E[P_{N+1}|F_N] = P_N depends only on P_N, the 2 NB
        # continuations' likelihoods, and the marginal-predictive weights.
        # We need to know the current edge e_curr (which is in F_N).
        # Re-simulate this walk's first N steps to extract e_curr at step N.
        rng_w = np.random.default_rng(20260525 + 1)
        # consume start_edges for first w walks
        for _ in range(w):
            rng_w.integers(0, N_EDGES)
        e_curr = int(rng_w.integers(0, N_EDGES))
        # consume the random NB-choice draws for the first w walks
        # (we generated all walks with one RNG, so reproducing requires
        # consuming exactly the same calls -- skip for simplicity by burning
        # the rng for the prior walks' step draws)
        for _ in range(w):
            for _ in range(N_STEPS):
                rng_w.integers(0, 2)
        # Now this rng matches the state right after generating walks 0..w-1
        # and the start edge for walk w. Walk through steps 0..N-1
        for step in range(N):
            idx = int(rng_w.integers(0, 2))
            e_curr = nb_continuations[e_curr][idx]
        # Now we have e_curr at the END of step N (i.e., the state observed
        # after the Nth observation). Compute marginal-predictive E[P_{N+1}|F_N].
        P_N = posteriors[w, N]
        P_b = 1.0 - P_N
        # For each of the 2 NB continuations from e_curr:
        E_pred = 0.0
        for idx in range(2):
            lik_u = likelihood_uniform(e_curr, idx)
            lik_b = likelihood_biased(e_curr, idx)
            p_marg = P_N * lik_u + P_b * lik_b
            # Bayes update if this obs were observed:
            P_next = (P_N * lik_u) / (P_N * lik_u + P_b * lik_b)
            E_pred += p_marg * P_next
        diff = abs(E_pred - P_N)
        max_dev = max(max_dev, diff)
        if diff > 1e-10:
            gate_a_pass = False
        print(f"    {N:3d}| {w:5d}    | {P_N:.6f} | {E_pred:.6f}            | "
              f"{diff:.2e}    |")
print(f"    --> {'PASS' if gate_a_pass else 'FAIL'} "
      f"(max |E_marg[P_{{N+1}}|F_N] - P_N| = {max_dev:.2e})")

# Gate (b): Doob L2 convergence. The mean and variance of P_N across walks
# should evolve as: mean P_N → 1 (since H_uniform is true), Var P_N → 0.
print()
print("(b) Doob L2 convergence: mean P_N(H_uniform) → 1, Var → 0")
print("    N    | mean P_N    | Var(P_N)     | sqrt(Var(P_N))")
N_log_grid = [1, 5, 10, 20, 50, 100, 150, 200]
for N in N_log_grid:
    mean_pN = posteriors[:, N].mean()
    var_pN = posteriors[:, N].var()
    print(f"    {N:4d} | {mean_pN:.6f}  | {var_pN:.4e}  | {np.sqrt(var_pN):.4e}")
final_mean = posteriors[:, -1].mean()
final_var = posteriors[:, -1].var()
# Doob: mean→1, Var→0. Tolerances: mean > 0.99 (saturating), Var/mean_var_initial < 0.1
init_var = posteriors[:, 10].var()  # peak-ish
var_ratio = final_var / init_var
gate_b_pass = (final_mean > 0.99) and (var_ratio < 0.1)
print(f"    --> {'PASS' if gate_b_pass else 'FAIL'} "
      f"(final mean = {final_mean:.4f}, "
      f"Var(N=200)/Var(N=10) = {var_ratio:.3f}; needs > 0.99 and < 0.1)")

# Gate (c): convergence rate matches theoretical KL.
# Log-posterior-odds: log[P_N(uniform) / P_N(biased)] = log(P_N / (1 - P_N))
# Expected slope per step = KL(H_uniform || H_biased)
print()
print("(c) Convergence rate: <log[P_N / (1 - P_N)]> should grow as N · KL")
# Avoid log(0) by clipping (posteriors very close to 1 give -inf log of 1-P)
log_odds = np.log(np.clip(posteriors, 1e-15, 1 - 1e-15) /
                  np.clip(1 - posteriors, 1e-15, 1 - 1e-15))
mean_log_odds = log_odds.mean(axis=0)
# Linear fit on mid-range (N=10 to N=150, avoid early transient + late
# clipping artifacts near saturation)
fit_N = np.arange(10, 150)
slope, intercept = np.polyfit(fit_N, mean_log_odds[10:150], 1)
print(f"    Fit:   <log odds> ≈ {slope:.4f} * N + {intercept:.4f}")
print(f"    Theory: KL = {KL_uniform_to_biased:.4f}")
print(f"    Ratio (slope / KL) = {slope / KL_uniform_to_biased:.4f}")
gate_c_pass = abs(slope / KL_uniform_to_biased - 1.0) < 0.1
print(f"    --> {'PASS' if gate_c_pass else 'FAIL'} "
      f"(within 10% of theoretical KL rate)")


# ------------------------------------------------------------------------
# Step 5: summary
# ------------------------------------------------------------------------
print()
print("=" * 70)
print("SUMMARY")
print("=" * 70)
print(f"(a) Martingale property: {'PASS' if gate_a_pass else 'FAIL'}")
print(f"(b) Doob L2 convergence: {'PASS' if gate_b_pass else 'FAIL'} "
      f"(final P_N = {final_mean:.4f} ± {np.sqrt(final_var):.4f})")
print(f"(c) Convergence rate ≈ KL: {'PASS' if gate_c_pass else 'FAIL'} "
      f"(measured {slope:.4f} vs theory {KL_uniform_to_biased:.4f})")

overall = gate_a_pass and gate_b_pass and gate_c_pass
print()
print(f"OVERALL: {'PASS' if overall else 'FAIL'}")
print()
print("INTERPRETATION:")
print(f"  Observer-side time index N (count of observations) is a martingale-")
print(f"  compatible filtration. The posterior P_N(H_uniform) is a bounded")
print(f"  martingale (gate a), Doob-converges to the truth (gate b), at the")
print(f"  theoretical KL rate (gate c). N is the unique natural discrete time")
print(f"  index on this filtration; identifying t = N · t_P fixes the observer's")
print(f"  clock in substrate-primitive units. This is the OBSERVER-SIDE")
print(f"  ANALOG of the substrate-side discrete causal cone from P1.S4.")
print("=" * 70)
