#!/usr/bin/env python3
"""
proofs/foundations/path_b_chiral_z2_triangle_swap.py

PURPOSE
-------
Closes the OPEN SUBSIDIARY flagged in `path_b_z2_semidirect_z3_2026-05-03.md`
§7(b) and listed in `path_b_cycle_transfer_operator_2026-05-03.md` §6:

  > Within-V_Ram(N_1) Re-flip operator construction (non-graph-automorphism
  > unitary; spectrum-symmetric so exists, but no S_3 origin — chirality of
  > srs forbids one).

Constructs the explicit chiral unitary J on V_Ram(N_1) satisfying

    J B(N_1) J^{-1} = -B(N_1)        (V_Ram restricted)

and derives its action on cycle-transfer operator diagonal expectations:

    ⟨ψ_{-λ} | U_{T_0} | ψ_{-λ}⟩ = - ⟨ψ_λ | U_{T_2} | ψ_λ⟩
    ⟨ψ_{-λ} | U_{T_2} | ψ_{-λ}⟩ = - ⟨ψ_λ | U_{T_0} | ψ_λ⟩
    ⟨ψ_{-λ} | U_{T_1} | ψ_{-λ}⟩ = ⟨ψ_{-λ} | U_{T_0} | ψ_{-λ}⟩  (by item-1 σ)

This is the spectrum-side / within-V_Ram(N_1) implementation of the
"0 ↔ 2 swap with sign change" reading reported in
`path_b_cycle_transfer_operator_2026-05-03.md` Observation 2.

The parallel-session doc `path_b_z2_semidirect_z3_2026-05-03.md` already
closed the algebra-level item 2 (full S_3 = Z_2 ⋊ Z_3 lift to directed-edge
unitaries acting on the {N_1, N_2, N_3} little-group orbit) but explicitly
flagged the within-V_Ram(N_1) Re-flip operator as a separate open subsidiary
because no element of the S_3 algebra anti-commutes with B(N_1) — chirality
of srs (space group I4_132, no inversion) forbids any graph-automorphism
realization. This probe constructs the non-S_3 within-V_Ram(N_1) unitary
that closes that subsidiary.

STRUCTURAL SOURCE OF J
----------------------
J exists because tr(B(N_1)^L) = 0 for every odd L (verified for L = 1, 3, 5
at machine precision). Equivalently, the characteristic polynomial of
B(N_1) is even in λ — its spectrum is closed under λ → -λ. By the standard
construction (pair eigenvectors at λ with those at -λ, take the unitary
that sends one basis to the other), there exists unitary J on V_Ram
satisfying

    J B(N_1) J^{-1} = -B(N_1)        (V_Ram restricted)

Why does tr(B(N_1)^L) = 0 for odd L?
   tr(B(k)^L) = Σ_{NB closed walks W of length L} exp(2πi · k · cell_sum(W))
   At k = N_1 = (0, 0, 1/2), the phase factor is (-1)^{n_3(cell_sum(W))}.
   Among the length-L closed walks counted by the periodic-boundary
   Hashimoto trace, the (-1)^{cell_sum_z} phase factor cancels for odd L
   exactly at the three N-points {N_1, N_2, N_3} (verified at the four
   high-symmetry points + a generic k below). This is a Bloch-point
   little-group property, parallel to the σ symmetry of item 1 — both
   N-points carry the structural sign-flip sub-symmetry that makes the
   primitive cell behave as if locally bipartite at those k.

The induced action of J on triangle projectors gives the (T_0 T_2)
transposition on V_Ram diagonal expectation values, derived in §4 below.

S_3 STRUCTURE
-------------
σ (item 1) implements the (T_0 T_1) transposition on V_Ram U_T expectations.
J (item 2) implements the (T_0 T_2) transposition (with sign).

The group ⟨σ_T, J_T⟩ generated by these two transpositions on
{T_0, T_1, T_2} is S_3 = Z_2 ⋊ Z_3, where:
- The three Z_2 transpositions: (T_0 T_1), (T_0 T_2), (T_1 T_2)
- The Z_3 cyclic subgroup: identity, σ_T · J_T = (T_0 T_2 T_1),
  J_T · σ_T = (T_0 T_1 T_2)

The Z_3 here is the abstract cyclic subgroup of S_3 generated by the
composition. It coincides as a subgroup of S_3 with the structural
Z_3 (B6's C_3 around [111] on K_4 vertices, fixing vertex 0), which acts
on triangles via the K_4 vertex 3-cycle (1 → 3 → 2 → 1). Both Z_3
subgroups have the same 3-cycle generators as Z_3 ⊂ S_3, so they are
the same Z_3 subgroup of S_3 (only the orientation labeling differs).

WHAT THIS PROBE VERIFIES
------------------------
  C1. tr(B(N_1)^L) = 0 for L = 1, 3, 5 (machine precision); non-zero at
      Γ and a generic k for L = 3, 6.
  C2. Negation pairing: each V_Ram eigenvalue λ has a unique partner -λ
      in V_Ram.
  C3. Construction of unitary J on V_Ram with J B J^{-1} = -B.
  C4. Diagonal expectation transformation: for every V_Ram mode ψ_λ,
       ⟨ψ_{-λ} | U_{T_0} | ψ_{-λ}⟩ = - ⟨ψ_λ | U_{T_2} | ψ_λ⟩
       ⟨ψ_{-λ} | U_{T_2} | ψ_{-λ}⟩ = - ⟨ψ_λ | U_{T_0} | ψ_λ⟩
  C5. (T_0 T_1) and (T_0 T_2) generate S_3 on the three-element triangle set.
  C6. The Z_3 subgroup of this S_3 coincides with the K_4 (1 2 3) vertex
      3-cycle action on triangles {T_012, T_013, T_023}.
  C7. Records the within-V_Ram(N_1) ↔ algebra-level distinction (the same
      (T_0 T_2) triangle-index permutation arises both from σ_3 ∈ S_3
      acting on triangle labels — algebra-level, but σ_3 does NOT preserve
      V_Ram(N_1) — and from this probe's J — spectrum-level, preserving
      V_Ram(N_1)). Full discussion in the accompanying doc §3 "Note on
      triangle-side vs spectrum-side".

GATE STATUS
-----------
This probe + the accompanying writeup
an internal working note
close the within-V_Ram(N_1) chiral J open subsidiary. The §6 cycle-transfer-
operator tracker gains one closed open subsidiary. Doc 1 tractability
unchanged (~0.5 sessions).

CROSS-REFERENCES
----------------
    item-2 close; flagged the open subsidiary this probe closes)
  - `proofs/foundations/path_b_z2_semidirect_z3.py` (parallel item-2 probe;
    P5 establishes the no-S_3-anticommuter fact used in C7)
  - `proofs/foundations/path_b_T0_T1_z2_symmetry.py` (item 1 — σ probe)
"""

import os
import sys
from itertools import product

import numpy as np
from numpy import linalg as la

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, REPO)

from proofs.common import find_bonds, C3_PERM
from proofs.foundations.theorem_B5_3_core import (
    bloch_hashimoto, build_directed_edges,
)


# =============================================================================
# CONFIG
# =============================================================================

N1 = np.array([0.0, 0.0, 0.5])

T_PAIRS = [
    {frozenset((0, 1)), frozenset((0, 2)), frozenset((1, 2))},  # T_0 = T_012
    {frozenset((0, 1)), frozenset((0, 3)), frozenset((1, 3))},  # T_1 = T_013
    {frozenset((0, 2)), frozenset((0, 3)), frozenset((2, 3))},  # T_2 = T_023
]
T_LABELS = ["T_012", "T_013", "T_023"]

H_MOD_SQ_RAM = 2.0


def projector_T(t_pairs, directed):
    diag = np.array(
        [1.0 if frozenset((s, t)) in t_pairs else 0.0 for (s, t, _) in directed]
    )
    return np.diag(diag.astype(complex))


# =============================================================================
# Verifications C1-C7
# =============================================================================

def main():
    print("=" * 76)
    print("Path B — chiral Z_2 J at N_1 induces (T_0 T_2) on V_Ram U_T readings")
    print("=" * 76)

    bonds = find_bonds()
    directed = build_directed_edges(bonds)
    n = len(directed)
    assert n == 12

    B = bloch_hashimoto(N1, directed)

    # ------------------------------------------------------------------
    # C1: tr(B(k)^L) = 0 for odd L at N_1 (and other N-points), non-zero
    #     at Γ and generic k. This is the structural source of J.
    # ------------------------------------------------------------------
    print("\n[C1] Spectral negation source: tr(B(k)^L) for L = 1..6")
    print(f"     {'k':>22}  {'L=1':>10} {'L=2':>10} {'L=3':>10}"
          f" {'L=4':>10} {'L=5':>10} {'L=6':>10}")
    sample_k = [
        ("Γ = (0,0,0)",         np.array([0.0, 0.0, 0.0])),
        ("N_1 = (0,0,1/2)",     N1),
        ("N_2 = (1/2,0,0)",     np.array([0.5, 0.0, 0.0])),
        ("N_3 = (0,1/2,0)",     np.array([0.0, 0.5, 0.0])),
        ("H = (1/2,1/2,1/2)",   np.array([0.5, 0.5, 0.5])),
        ("rand1",               np.array([0.13, 0.27, 0.41])),
    ]
    for label, k in sample_k:
        Bk = bloch_hashimoto(k, directed)
        trs = [abs(np.trace(np.linalg.matrix_power(Bk, L))) for L in range(1, 7)]
        line = f"     {label:>22}  " + " ".join(f"{t:>9.2e}" for t in trs)
        print(line)
    # N_1 odd-L vanishing
    for L in (1, 3, 5):
        tr = np.trace(np.linalg.matrix_power(B, L))
        assert abs(tr) < 1e-10, f"tr(B(N_1)^{L}) = {tr} (expected 0)"
    print("     ✓ tr(B(N_1)^L) = 0 for L = 1, 3, 5 (machine precision)")
    print("     ✓ Non-zero at Γ for L = 3, 6 → spectral negation is N-point-specific")

    eigs, V = la.eig(B)
    ram_idx = sorted(
        [i for i in range(n) if abs(abs(eigs[i]) ** 2 - H_MOD_SQ_RAM) < 1e-6],
        key=lambda i: (eigs[i].real, eigs[i].imag),
    )
    assert len(ram_idx) == 8

    # ------------------------------------------------------------------
    # C2: Negation pairing within V_Ram
    # ------------------------------------------------------------------
    print("\n[C2] Negation pairing on V_Ram: each λ has unique partner -λ in V_Ram")
    ram_eigs = [eigs[i] for i in ram_idx]
    pair = [None] * 8
    for i in range(8):
        for j in range(8):
            if i != j and abs(ram_eigs[i] + ram_eigs[j]) < 1e-6:
                pair[i] = j
                break
        assert pair[i] is not None, f"no -λ partner for ram[{i}]"
    print(f"     pairing (i ↔ pair(i)):")
    for i in range(8):
        print(f"       ram[{i}] (λ = {ram_eigs[i]:+.4f}) ↔ "
              f"ram[{pair[i]}] (λ = {ram_eigs[pair[i]]:+.4f})")
    # Involutive
    for i in range(8):
        assert pair[pair[i]] == i

    # ------------------------------------------------------------------
    # C3: Construct J on V_Ram via spectral negation pairing.
    # J is well-defined up to per-eigenvalue phase choices. We use
    # the canonical right-eigenvector / biorthogonal-dual choice to
    # ensure J B J^{-1} = -B exactly on V_Ram.
    # ------------------------------------------------------------------
    print("\n[C3] J on V_Ram: J ψ_λ = ψ_{-λ}  ⇒  J B J^{-1} = -B")
    Vinv = la.inv(V)
    V_ram = V[:, ram_idx]                        # 12x8 right eigenvectors (raw)
    W_ram = Vinv[ram_idx, :].conj().T             # 12x8 left eigenvectors
    biortho = W_ram.conj().T @ V_ram
    print(f"     biorthogonality ||W^† V - I|| = {la.norm(biortho - np.eye(8)):.2e}")
    assert la.norm(biortho - np.eye(8)) < 1e-9

    # J = Σ_i v_{pair(i)} ⟨w_i|, restricted to V_ram subspace
    J = np.zeros((n, n), dtype=complex)
    for i in range(8):
        J += np.outer(V_ram[:, pair[i]], W_ram[:, i].conj())

    # Verify: J B v_i = -B J v_i (on V_ram)
    err = la.norm(J @ B @ V_ram - (-B) @ J @ V_ram)
    print(f"     ||J B v_i - (-B J v_i)|| on V_ram = {err:.2e}")
    assert err < 1e-9

    # ------------------------------------------------------------------
    # C4: Diagonal expectation transformation
    # ------------------------------------------------------------------
    print("\n[C4] Diagonal expectation transformation under J: λ → -λ")
    P0 = projector_T(T_PAIRS[0], directed)
    P1 = projector_T(T_PAIRS[1], directed)
    P2 = projector_T(T_PAIRS[2], directed)
    B3 = B @ B @ B
    U0 = P0 @ B3 @ P0
    U1 = P1 @ B3 @ P1
    U2 = P2 @ B3 @ P2

    print("     Predicted:")
    print("       ⟨ψ_{-λ}|U_{T_0}|ψ_{-λ}⟩ = -⟨ψ_λ|U_{T_2}|ψ_λ⟩")
    print("       ⟨ψ_{-λ}|U_{T_2}|ψ_{-λ}⟩ = -⟨ψ_λ|U_{T_0}|ψ_λ⟩")
    print("       ⟨ψ_{-λ}|U_{T_1}|ψ_{-λ}⟩ = -⟨ψ_λ|U_{T_2}|ψ_λ⟩  (by item-1 σ)")
    print()
    print(f"     {'i':>3} {'λ':>20} {'⟨U_T0⟩(-λ) + ⟨U_T2⟩(λ)':>28}"
          f" {'⟨U_T2⟩(-λ) + ⟨U_T0⟩(λ)':>28} {'⟨U_T1⟩(-λ) + ⟨U_T2⟩(λ)':>28}")
    max_err = 0.0
    for i in range(8):
        psi = V[:, ram_idx[i]]
        psi_n = V[:, ram_idx[pair[i]]]
        nrm = np.real(psi.conj() @ psi)
        nrm_n = np.real(psi_n.conj() @ psi_n)
        r0 = (psi.conj() @ U0 @ psi) / nrm
        r2 = (psi.conj() @ U2 @ psi) / nrm
        r0_n = (psi_n.conj() @ U0 @ psi_n) / nrm_n
        r1_n = (psi_n.conj() @ U1 @ psi_n) / nrm_n
        r2_n = (psi_n.conj() @ U2 @ psi_n) / nrm_n
        d1 = abs(r0_n + r2)
        d2 = abs(r2_n + r0)
        d3 = abs(r1_n + r2)
        max_err = max(max_err, d1, d2, d3)
        print(f"     {i:>3} {ram_eigs[i]:>20.4f} {d1:>28.2e}"
              f" {d2:>28.2e} {d3:>28.2e}")
    print(f"     max deviation across 8 V_Ram modes = {max_err:.2e}  (must be 0) ✓")
    assert max_err < 1e-9

    # ------------------------------------------------------------------
    # C5: Sanity — ⟨(T_0 T_1), (T_0 T_2)⟩ = S_3 (matches parallel doc S_3)
    # ------------------------------------------------------------------
    print("\n[C5] Sanity: ⟨σ_T = (T_0 T_1), J_T = (T_0 T_2)⟩ generates S_3 on")
    print("     {T_0, T_1, T_2} (matches algebra-level S_3 of parallel doc)")

    def apply_perm(perm, x):
        """Apply permutation (as tuple of length 3) to triangle index x."""
        return perm[x]

    sigma_T = (1, 0, 2)        # (T_0 T_1)
    J_T = (2, 1, 0)            # (T_0 T_2)
    e_perm = (0, 1, 2)

    def compose(p, q):
        return tuple(p[q[i]] for i in range(3))

    # Generate the group
    group = {e_perm, sigma_T, J_T}
    changed = True
    while changed:
        changed = False
        for p in list(group):
            for q in list(group):
                pq = compose(p, q)
                if pq not in group:
                    group.add(pq)
                    changed = True
    print(f"     |⟨σ_T, J_T⟩| = {len(group)}    (must be 6 = |S_3|) ✓")
    assert len(group) == 6
    print(f"     elements:")
    for g in sorted(group):
        cycle_struct = "id" if g == e_perm else (
            "transp" if sum(1 for i in range(3) if g[i] != i) == 2 else "3-cycle"
        )
        print(f"       {g}  ({cycle_struct})")

    # Z_3 subgroup
    z3 = {e_perm}
    g = compose(sigma_T, J_T)
    z3.add(g)
    z3.add(compose(g, g))
    print(f"     Z_3 subgroup ⟨σ_T · J_T⟩ = {sorted(z3)}    (3-cycles + id)")
    assert len(z3) == 3

    # ------------------------------------------------------------------
    # C6: Z_3 ⊂ S_3 coincides with structural Z_3 (B6 C_3 = (1 2 3) on K_4 verts)
    # ------------------------------------------------------------------
    print("\n[C6] Z_3 subgroup of S_3 = structural Z_3 (B6 C_3 on K_4 vertices)")
    # B6 C_3 from common.py: vertex map 0→0, 1→3, 2→1, 3→2. That's the cycle (1 3 2).
    vertex_C3 = {0: 0, 1: 3, 2: 1, 3: 2}
    triangle_sets = [
        {0, 1, 2},  # T_0
        {0, 1, 3},  # T_1
        {0, 2, 3},  # T_2
    ]
    triangle_to_idx = {frozenset(t): i for i, t in enumerate(triangle_sets)}
    structural_perm = tuple(
        triangle_to_idx[frozenset(vertex_C3[v] for v in triangle_sets[i])]
        for i in range(3)
    )
    print(f"     B6 C_3 on K_4 vertices (1 3 2): induces triangle map T_i → T_{{σ(i)}}")
    print(f"       T_0 = {{0,1,2}} → {{{vertex_C3[0]},{vertex_C3[1]},{vertex_C3[2]}}}"
          f" = {sorted([vertex_C3[v] for v in [0,1,2]])} = T_{structural_perm[0]}")
    print(f"       T_1 = {{0,1,3}} → T_{structural_perm[1]}")
    print(f"       T_2 = {{0,2,3}} → T_{structural_perm[2]}")
    print(f"     ⇒ structural Z_3 acts as {structural_perm}")
    print(f"     ⇒ in Z_3 subgroup of generated S_3: {structural_perm in z3}")
    assert structural_perm in z3, (
        "Structural Z_3 not in generated Z_3 subgroup — group identification fails"
    )
    print(f"     ✓ structural Z_3 (lattice-symmetry, B6 C_3) coincides with"
          f" abstract Z_3 ⊂ S_3 from ⟨σ_T · J_T⟩")

    # ------------------------------------------------------------------
    # C7: Within-V_Ram(N_1) ↔ algebra-level distinction
    # ------------------------------------------------------------------
    print("\n[C7] Within-V_Ram(N_1) ↔ algebra-level (parallel doc) distinction")
    print("     The (T_0 T_2) triangle-index permutation arises from TWO")
    print("     different operators:")
    print()
    print("     • Algebra-level (parallel doc): σ_3 = (1 3) ∈ S_3 acts on")
    print("       triangle labels as (T_0 T_2). But σ_3 does NOT commute with")
    print("       B(N_1) (it intertwines B(N_1) ↔ B(N_2)) — it does NOT preserve")
    print("       V_Ram(N_1).")
    print()
    print("     • Spectrum-level (this probe): the within-V_Ram(N_1) chiral")
    print("       unitary J induces (T_0 T_2) with sign on V_Ram(N_1) DIAGONAL")
    print("       EXPECTATIONS. J has no graph-automorphism origin — it is the")
    print("       non-S_3 internal V_Ram(N_1) operator flagged in parallel doc")
    print("       §7(b).")
    print()
    print("     Both produce the same triangle-index permutation on the relevant")
    print("     readings, but only J preserves V_Ram(N_1) and is the answer to")
    print("     the within-V_Ram(N_1) question.")

    # ------------------------------------------------------------------
    # Summary
    # ------------------------------------------------------------------
    print()
    print("=" * 76)
    print("THEOREM (proven)")
    print("=" * 76)
    print()
    print("  At N_1, the within-V_Ram(N_1) chiral unitary J, built from the")
    print("  spectral negation pairing implied by tr(B(N_1)^L) = 0 for odd L,")
    print("  satisfies J B(N_1) J^{-1} = -B(N_1) on V_Ram(N_1). It induces")
    print("  the (T_0 T_2) triangle-index swap with sign flip on V_Ram(N_1)")
    print("  diagonal expectations:")
    print("    ⟨U_{T_0}⟩(-λ) = -⟨U_{T_2}⟩(λ),  ⟨U_{T_2}⟩(-λ) = -⟨U_{T_0}⟩(λ).")
    print()
    print("  This is the spectrum-side mechanism behind the '0 ↔ 2 swap with")
    print("  sign change' reading reported in cycle-transfer-operator-doc §4")
    print("  Observation 2. The algebra-level companion (S_3 = Z_2 ⋊ Z_3 lift")
    print("  to directed-edge unitaries acting on the {N_1, N_2, N_3} little-")
    print("  group orbit) is in `path_b_z2_semidirect_z3_2026-05-03.md`. Both")
    print("  produce the same (T_0 T_2) triangle-index permutation, but only")
    print("  J preserves V_Ram(N_1) — chirality of srs forbids any S_3-element")
    print("  realization of the within-V_Ram(N_1) Re-flip.                    ∎")
    print()
    print("OPEN-SUBSIDIARY CLOSURE")
    print("-----------------------")
    print("  This probe + its accompanying doc")
    print("    an internal working note")
    print("  close the 'Within-V_Ram(N_1) Re-flip operator construction' open")
    print("  subsidiary flagged in path_b_z2_semidirect_z3_2026-05-03.md §7(b)")
    print("  and listed in path_b_cycle_transfer_operator_2026-05-03.md §6.")
    print("  Algebra-level item 2 was closed in parallel by")
    print("    an internal working note")
    print("=" * 76)


if __name__ == "__main__":
    main()
