#!/usr/bin/env python3
"""Phase 1.3 / S1 — is the Z2 mirror the BODY-CENTERING translation?

srs lives on the BCC lattice T_I (primitive vectors A_PRIM); the simple-cubic
lattice T_P sits inside at index 2, quotient generated by the body-centering
translation t = (1/2,1/2,1/2)_cubic. Restricting periodicity to T_P folds each
cubic-fractional momentum kappa onto TWO BCC fibers:

    k1_i = kappa . a_i,     k2 = k1 + DELTA,   DELTA = (1/2, 1/2, -1/2)
    (DELTA_i = q . a_i for the odd cubic shift q = (0,0,1))

Gates:
  F1 ANTIPERIOD: spec A_srs(k + DELTA) = -spec A_srs(k) for random k.
     If true, the body-centering character acts as the SPECTRAL MIRROR:
     the lattice-character L-function == the bipartite sign L-function of
     Phase 1.1, and the mirror is GEOMETRIC (winding through the body center).
  F2 FOLDING = COVER: spec A_srsz(kappa) = spec A_srs(k1) u spec A_srs(k2)
     (crystallographic srs-z fibers == folded srs == bipartite double).
  F3 Hashimoto determinant version of F2 (sampled in u):
     det(I - u B_srsz(kappa)) = det(I - u B_srs(k1)) det(I - u B_srs(k2)).
  F4 L-fiber identity: det(I - u B_srs(k+DELTA)) = det(I - u B_sgn(k))
     (shifted fiber == sign-voltage-twisted fiber; ties F1 to 1.1's L(u,sgn)).

If F1..F4 pass: zeta_srsz(u) = zeta_srs(u) * L(u, sgn) holds with the sign
character REALIZED as the body-centering translation -- the bet's premise (K1)
is discharged, and "mirror holonomy" = body-center winding parity.
"""
import os
import sys
import numpy as np
from numpy import linalg as la

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
from proofs.common import find_bonds, A_PRIM  # noqa: E402
from simulator.srs_engine.srsz_substrate import _build_srsz_bonds  # noqa: E402

RNG = np.random.default_rng(20260611)
TOL = 1e-9
FAILURES = []
DELTA = np.array([0.5, 0.5, -0.5])  # q=(0,0,1) dotted into A_PRIM rows


def gate(name, ok, detail=""):
    print(f"  [{'PASS' if ok else 'FAIL'}] {name}" + (f"  ({detail})" if detail else ""))
    if not ok:
        FAILURES.append(name)


def directed_edges(bonds):
    edges = [(b[0], b[1], tuple(b[2])) for b in bonds]
    rev = {}
    for a, (i, j, c) in enumerate(edges):
        target = (j, i, tuple(-x for x in c))
        for b2, e2 in enumerate(edges):
            if e2 == target:
                rev[a] = b2
    assert len(rev) == len(edges) and all(rev[rev[a]] == a for a in rev)
    return edges, rev


def bloch_A(k, bonds, n):
    A = np.zeros((n, n), dtype=complex)
    for b in bonds:
        i, j, c = b[0], b[1], np.asarray(b[2], dtype=float)
        A[j, i] += np.exp(2j * np.pi * np.dot(k, c))
    return A


def bloch_B(k, edges, rev, sign=+1):
    n = len(edges)
    B = np.zeros((n, n), dtype=complex)
    for a, (i, j, c) in enumerate(edges):
        for b2, (i2, j2, c2) in enumerate(edges):
            if i2 == j and b2 != rev[a]:
                B[b2, a] = sign * np.exp(2j * np.pi * np.dot(k, np.asarray(c2, float)))
    return B


def specs(M):
    w = la.eigvals(M)
    return np.sort_complex(np.round(w, 10))


def poly_eq(fL, fR, n_samples=30, tol=TOL):
    us = 1.2 * (RNG.random(n_samples) - 0.5 + 1j * (RNG.random(n_samples) - 0.5))
    worst = 0.0
    for u in us:
        L, R = fL(u), fR(u)
        worst = max(worst, abs(L - R) / max(1.0, abs(L), abs(R)))
    return worst < tol, worst


def main():
    print("=" * 72)
    print(" PHASE 1.3/S1 -- mirror character == body-centering translation?")
    print("=" * 72)
    srs_bonds = find_bonds()
    edges, rev = directed_edges(srs_bonds)
    out = _build_srsz_bonds()
    z_verts, z_bonds = out[0], out[1]
    z_edges, z_rev = directed_edges(z_bonds)
    print(f"  srs: 4 atoms, {len(edges)} directed bonds (BCC cells); "
          f"srs-z: {len(z_verts)} atoms, {len(z_edges)} directed bonds (cubic cells)")

    # --- F1: antiperiod -------------------------------------------------------
    ok_all, worst = True, 0.0
    for _ in range(6):
        k = RNG.random(3)
        s1 = np.sort(la.eigvalsh(bloch_A(k, srs_bonds, 4)))
        s2 = np.sort(-la.eigvalsh(bloch_A(k + DELTA, srs_bonds, 4)))
        d = np.abs(s1 - s2).max()
        worst = max(worst, d)
        ok_all &= d < TOL
    gate("F1 antiperiod: spec A(k+DELTA) = -spec A(k)", ok_all, f"worst {worst:.2e}")

    # --- F2: srs-z fibers == folded srs --------------------------------------
    ok_all, worst = True, 0.0
    for _ in range(6):
        kap = RNG.random(3)
        k1 = A_PRIM @ kap          # kappa . a_i
        k2 = k1 + DELTA
        sz = np.sort(la.eigvalsh(bloch_A(kap, z_bonds, len(z_verts))))
        sf = np.sort(np.concatenate([la.eigvalsh(bloch_A(k1, srs_bonds, 4)),
                                     la.eigvalsh(bloch_A(k2, srs_bonds, 4))]))
        d = np.abs(sz - sf).max()
        worst = max(worst, d)
        ok_all &= d < TOL
    gate("F2 folding: spec A_srsz(kappa) = spec A(k1) u spec A(k2)", ok_all,
         f"worst {worst:.2e}")

    # --- F3: Hashimoto determinant folding ------------------------------------
    kap = RNG.random(3)
    k1 = A_PRIM @ kap
    k2 = k1 + DELTA
    Bz = bloch_B(kap, z_edges, z_rev)
    B1 = bloch_B(k1, edges, rev)
    B2 = bloch_B(k2, edges, rev)
    ok, worst = poly_eq(
        lambda u: la.det(np.eye(len(z_edges)) - u * Bz),
        lambda u: la.det(np.eye(12) - u * B1) * la.det(np.eye(12) - u * B2))
    gate("F3 det(I-uB_srsz) = det(I-uB(k1)) det(I-uB(k2))", ok, f"worst {worst:.2e}")

    # --- F4: shifted fiber == sign-twisted fiber (ties to 1.1 L(u,sgn)) -------
    k = RNG.random(3)
    Bshift = bloch_B(k + DELTA, edges, rev)
    Bsgn = bloch_B(k, edges, rev, sign=-1)
    ok, worst = poly_eq(
        lambda u: la.det(np.eye(12) - u * Bshift),
        lambda u: la.det(np.eye(12) - u * Bsgn))
    gate("F4 det(I-uB(k+DELTA)) = det(I-uB_sgn(k))", ok, f"worst {worst:.2e}")

    print("\n" + "=" * 72)
    if FAILURES:
        print(f" RESULT: {len(FAILURES)} GATE(S) FAILED: {FAILURES}")
        return 1
    print(" RESULT: ALL GATES PASS -- the mirror IS the body-centering translation:")
    print("   zeta_srsz = zeta_srs * L(u,sgn) with sgn = body-center winding parity.")
    print("   K1 (premise) DISCHARGED: srs-z == bipartite double == folded srs.")
    print("=" * 72)
    return 0


if __name__ == "__main__":
    sys.exit(main())
