#!/usr/bin/env python3
"""
Phase 0 — associativity smuggle audit of the closed NA chain.

CONTEXT
=======
NA-4 sharpening
hypothesized that Layer-1 escape takes the form of a multiway-branch
associator [a, b, c] = (ab)c - a(bc). This Phase 0 audit maps where
associativity is assumed in the framework's closed NA chain (NA-1, NA-2',
NA-3) and the upstream multiway / Hilbert-space machinery.

Goal: identify EVERY load-bearing associativity assumption, so that the
proper non-associative extension (Option 2 / free-magma walker, deferred)
has a concrete handle.

This is a STRUCTURAL READING audit — no machine-precision computation.
"""

from __future__ import annotations

print("=" * 78)
print("Phase 0: Associativity smuggle audit — closed NA chain")
print("=" * 78)
print()


# ============================================================================
# Site A — A3 multiway theorem §4 Step 1 (free involutive monoid as GROUP)
# ============================================================================
print("=" * 78)
print("Site A: theorem_A3_complex_hilbert_from_multiway.md §4 Step 1")
print("=" * 78)
print()
print("""  QUOTE (verbatim):
    "By A1, each generator e ∈ E satisfies T_e² = id, so T_e is its own
    inverse. Compositions of generators (with the relations e · e = ε
    giving cancellation) form an ASSOCIATIVE structure with identity
    (the empty word ε); every element h = e₁ · e₂ · ... · e_n has
    inverse h⁻¹ = e_n · e_{n-1} · ... · e₁ (reverse the order, apply
    each involution again to cancel). Hence F_inv(E) is a GROUP."

  ASSOCIATIVITY ASSERTION:
    Explicit. "Compositions of generators form an associative structure"
    is asserted with no upstream derivation. The associativity comes from
    the meta-mathematical convention that string concatenation is
    associative — a property of strings, not of toggles.

  WHAT DEPENDS ON IT:
    - F_inv(E) being a group (not just a magma or loop)
    - Cayley graph of F_inv(E)
    - Adjacency operator on Cayley graph
    - Hamiltonian via Strauch 2006 + Childs 2009 (continuum limit on
      Cayley graphs)
    - Self-adjoint H, unitary U(t) = exp(-iHt)
    - Therefore: complex Hilbert space conclusion of A3-T

  FIX REQUIRED if associativity broken:
    F_inv(E) becomes a free MAGMA (with involutivity), not a group.
    Cayley graph generalization → "Cayley quasi-graph" or magma word
    tree. Hamiltonian identification breaks (Strauch + Childs require
    group structure). Hilbert space construction needs entirely
    different setup.
""")


# ============================================================================
# Site B — Branch measure theorem (P1, P3) Kolmogorov product measure
# ============================================================================
print("=" * 78)
print("Site B: theorem_multiway_branch_measure.md (P1, P3)")
print("=" * 78)
print()
print("""  QUOTE (verbatim):
    "(P1) Definition. On the space Σ* = ∪_L E^L of finite toggle
    sequences, μ is the uniform product measure: μ(B) = |E|^{-L}
    for B ∈ E^L."

    "(P3) Multiplicative compounding. For any event A ⊆ Σ* that is a
    product of step-wise events A = ∏_i A_i with A_i ⊆ E,
    μ(A) = ∏_i μ_1(A_i) where μ_1(e) = 1/|E|."

  ASSOCIATIVITY ASSERTION:
    Implicit but load-bearing. The "product measure" structure assumes
    sequence space Σ* = ∪_L E^L treats event composition as Cartesian
    product. Cartesian product is associative: (A_1 × A_2) × A_3 =
    A_1 × (A_2 × A_3). Therefore μ(A) is bracket-independent.

  WHAT DEPENDS ON IT:
    - Kolmogorov 1933 product-measure construction
    - Closed-cycle generating function (cited in §11)
    - Bloch-lift theorem (theorem_bloch_lift_mu.md)
    - Hashimoto B as 1-step amplitude operator (W3 closure)
    - Spec(B) as physical observable set (W4 closure)

  FIX REQUIRED if associativity broken:
    Σ* is not a sequence space but a TREE space (each path has
    bracketing structure). μ becomes path-bracketing-dependent;
    μ(A_1 × A_2 × A_3) splits into μ((A_1 × A_2) × A_3) and
    μ(A_1 × (A_2 × A_3)) — generally different. Non-associativity
    measured by associator [μ; A_1, A_2, A_3] := μ((A_1×A_2)×A_3) -
    μ(A_1×(A_2×A_3)).

    The "associator measure" is the natural Layer-1 quantity that
    F_inv(E) projection averages out.
""")


# ============================================================================
# Site C — NA-2' compression theorem Step 1 (group again)
# ============================================================================
print("=" * 78)
print("Site C: theorem_F_inv_E_to_srs_compression.md Step 1")
print("=" * 78)
print()
print("""  QUOTE (verbatim):
    "By A1 the substrate dynamics is generated by the finite alphabet E
    of binary self-inverse toggle operators T_e (e ∈ E, T_e² = id).
    Compositions modulo e·e = ε form the free involutive monoid F_inv(E),
    a discrete countable GROUP (Serre 1980 §I.1 Proposition 4)."

  ASSOCIATIVITY ASSERTION:
    Same as Site A — "F_inv(E) is a group" cited from Serre 1980.
    Same smuggle: "compositions" treated as string concatenation
    (associative) without separate derivation.

  WHAT DEPENDS ON IT:
    - Cayley graph A_{F_inv(E)}
    - Strauch + Childs continuum-limit Hamiltonian
    - Layer-1 visible/dark decomposition (Step 3 of NA-2' compression)
    - ARG-1 alphabet localization
    - ARG-2 geometric embedding
    - Sunada Bloch decomposition (Step 6) over Z^d-periodic structure
    - srs identification at Layer-2

  FIX REQUIRED if associativity broken:
    Same as Site A. Cascade: NA-2' compression chain breaks at Step 1;
    Layer-1/Layer-2 split via π = Π_MDL becomes a non-associative
    quotient (some kind of magma Cayley structure). The bridge from
    F_inv(E) → srs needs entirely new machinery.
""")


# ============================================================================
# Site D — Hashimoto B^L matrix multiplication
# ============================================================================
print("=" * 78)
print("Site D: walker_dynamics Step 7 — B^L matrix amplitude")
print("=" * 78)
print()
print("""  QUOTE (effective):
    "Step 7: L-step amplitude = B^L [matrix composition] (closes W3)"

  ASSOCIATIVITY ASSERTION:
    Matrix multiplication is associative: (B · B) · B = B · (B · B) = B³.
    The L-step amplitude on the observer's Hashimoto walk space is
    therefore unambiguously B^L.

  WHAT DEPENDS ON IT:
    - W3 walker dynamics closure
    - Spec(B^L) = Spec(B)^L (eigenvalues of L-step = L-th powers)
    - Predictions reading off Spec(B): Yukawa hierarchies (|h|^L), CKM
      phases (arg h^L), λ_Higgs (tan²(arg h)), η_B, etc.
    - Cosmology cascade (B^N walks)

  FIX REQUIRED if associativity broken:
    Substrate's "L-step amplitude" has bracketing dependence:
        A_substrate^[bracketing](L) ≠ B_observer^L
    in general. The observer's matrix B doesn't capture the substrate's
    true L-step content. Layer-1 escape: the discrepancy (B^L)_observer
    - A_substrate is exactly the associator content NA-4 identified.

    All Spec(B)-based predictions are observer-side approximations.
    The discrepancy is bounded by the associator magnitude — small if
    substrate is "approximately associative", potentially large at
    high enough L (relevant for cosmology / long-time observables).
""")


# ============================================================================
# Site E — Sunada arc-transitivity (group automorphism action)
# ============================================================================
print("=" * 78)
print("Site E: Sunada 2012 arc-transitivity (Row 4 + R-9 + W4)")
print("=" * 78)
print()
print("""  CONTEXT:
    Per `walker_dynamics_derivation.md` Step 4 (Jaynes uniform per-step
    NB survival) — load-bearing prerequisite for W4 walker dynamics
    closure. Per Sunada 2012, srs is unique strongly isotropic 3D
    3-regular crystal net up to handedness; equivalently, srs is the
    unique vertex+edge-transitive (= flag-transitive) k=3 3D net.

  ASSOCIATIVITY ASSERTION:
    Arc-transitivity = transitivity of the GROUP of graph automorphisms
    on directed edges. Group action is associative: (g · h) · v =
    g · (h · v) for g, h ∈ Aut(G), v an arc. Sunada 2012's result is
    about classical group symmetry of 3D nets.

  WHAT DEPENDS ON IT:
    - W4 walker dynamics (Jaynes per-step uniform — depends on
      arc-transitivity for per-step branching to be observer-state-
      independent)
    - Row 4 audit-v2 closure (DOMINANT-CONDITIONAL → UNIQUE)
    - 30+ inheritance rows downstream of Row 4
    - NA-2', NA-3 multiway closures use arc-transitivity at Steps 2/4/5

  FIX REQUIRED if associativity broken:
    Arc-transitivity assumes a GROUP of automorphisms. Non-associative
    substrate would have a MAGMA / LOOP / QUASIGROUP of automorphisms.
    Arc-transitivity in the magma sense is a different (weaker?)
    condition. Sunada 2012's classical theorem doesn't apply.

    Loop / quasigroup analog of Sunada-style theorems exist in less
    well-developed corners of the literature; framework would need to
    cite or develop these.
""")


# ============================================================================
# Site F — walker_dynamics Step 1 (free monoid)
# ============================================================================
print("=" * 78)
print("Site F: walker_dynamics_derivation.md Step 1 (free monoid)")
print("=" * 78)
print()
print("""  QUOTE (already identified in 2026-05-06 NA-4 sharpening):
    "A1 forces T_e·T_e = I for each edge e. Toggle streams form the
    free monoid E*; under the congruence {e·e ~ ε}, we get F_inv(E)."

  ASSOCIATIVITY ASSERTION:
    "Toggle streams form the free monoid E*". Free monoid is associative
    by string-concatenation convention. This is the ROOT smuggle —
    sites A, C are downstream of this same modeling step.

  ROOT ASSESSMENT:
    Sites A, C, F all reduce to ONE SMUGGLE: at the modeling step that
    turns toggle DYNAMICS into toggle STRINGS, associativity is
    automatic. The actual content of A1 (T_e self-inverse) doesn't
    require associativity — it's a unary property of each generator.
    The associativity is in how the generators COMPOSE.

  FIX REQUIRED if associativity broken:
    Replace "toggle streams = free monoid" with "toggle stream =
    free magma + involutivity" or "= free Moufang loop" or similar
    weaker structure. Different starting structure, then the rest of
    the framework's apparatus would need re-derivation.
""")


# ============================================================================
# Site G — Bloch decomposition (Z^d as abelian group)
# ============================================================================
print("=" * 78)
print("Site G: Sunada 2013 Bloch decomposition (Z^d periodicity)")
print("=" * 78)
print()
print("""  CONTEXT:
    NA-2' compression Step 6 invokes Sunada 2013 §6 Theorem 6.4 for
    Bloch decomposition of operators on Z^d-periodic structures.
    K = ⊕_k B(k) over BZ, with k ∈ T^d = R^d / Z^d (Brillouin zone).

  ASSOCIATIVITY ASSERTION:
    Z^d is an abelian GROUP. Bloch decomposition is the Fourier
    transform on Z^d-modules; uses Z^d's group structure (and
    abelian-ness). Without group structure, no Pontryagin dual,
    no Brillouin zone, no Bloch waves.

  WHAT DEPENDS ON IT:
    - All Bloch-momentum analyses (Γ, P, H, N points)
    - Hashimoto B(k) at specific k-points (k_P, etc.)
    - h-eigenvalue at P-point (theorem_bloch_lift_mu.md C3)
    - Ramanujan saturation via |h|² = k* − 1
    - Ratio of compressed predictions: V_us, V_cb, λ_Higgs, etc.

  FIX REQUIRED if associativity broken:
    No clean fix — Bloch decomposition is fundamentally a GROUP-Fourier
    technique. If substrate is non-associative at some level but Z^d
    spatial periodicity still holds at OBSERVER level, then Bloch
    decomposition still works at observer level — but is an OBSERVER-
    SIDE construct, not substrate-true. Layer-1 substrate has no
    Bloch decomposition (or a non-associative analog).

    Implication: framework's k-space analysis is observer-side; the
    Layer-1 substrate has different structure that's invisible in
    k-space.
""")


# ============================================================================
# Site H — Local CAR / Jordan-Wigner (Cl algebra associativity)
# ============================================================================
print("=" * 78)
print("Site H: Local CAR + Jordan-Wigner → Cl(2k) associative algebra")
print("=" * 78)
print()
print("""  CONTEXT:
    `theorem_car_local_jordan_wigner.md` derives canonical anti-
    commutation relations (CAR) for shared-vertex toggles, then
    Jordan-Wigner mapping gives k anti-commuting generators γ_i with
    γ_i² = ±I and {γ_i, γ_j} = 0 for i ≠ j. These generate Cl(2k).

  ASSOCIATIVITY ASSERTION:
    Cl(2k) is an ASSOCIATIVE algebra (matrix algebra). The relations
    {γ_i, γ_j} = 2δ_ij involve only PAIRS of generators (anti-
    commutation is 2-letter). Associativity enters at 3-letter
    compositions γ_i γ_j γ_k — implicitly assumed associative because
    Cl(2k) is treated as a matrix algebra.

  WHAT DEPENDS ON IT:
    - Cl(6) Fock at vertex (16-state generation per Furey 2018)
    - Cl(0,2) ≅ ℍ at edge (G2 theorem, derives SU(2)_L)
    - All gauge group derivations (G2, G2-D, B6, sin²θ_W)
    - Cl-bivector tower (Cl(8), Cl(10), ... at higher k)

  FIX REQUIRED if associativity broken:
    Cl(2k) is replaced by an alternative algebra with the SAME 2-letter
    anti-commutation relations but DIFFERENT 3-letter behavior. Octonions
    are EXACTLY this: octonions have {e_i, e_j} = -2δ_ij i ≠ j relations
    (same as Cl) but [e_i, e_j, e_k] ≠ 0 (associator ≠ 0). So octonions
    are the "natural Cl-like algebra" with non-trivial associator.

    THIS IS THE KEY STRUCTURAL CONNECTION: octonionic structure at
    Layer-1 of the substrate would IDENTICALLY satisfy CAR at the
    2-letter level (so observer doesn't notice) but produce different
    3+ letter products. The associator [γ_i, γ_j, γ_k] ≠ 0 is invisible
    to 2-letter (anti-)commutation tests but shows up in any composite
    operator built from 3+ generators.

    All of framework's predictions involving 3+ generator products at
    Cl algebra level potentially have non-trivial associator content.
""")


# ============================================================================
# Synthesis
# ============================================================================
print("=" * 78)
print("Synthesis — common source + cascade structure")
print("=" * 78)
print()
print("""  The 8 smuggle sites (A-H) are NOT independent. They flow from a
  small number of root assumptions:

  ROOT 1: Toggle compositions form a free associative structure.
          (Sites A, C, F — all the "F_inv(E) is a group" claims)

  ROOT 2: Local CAR generates an associative Clifford algebra.
          (Site H)

  ROOT 3: Branch measures factor as Kolmogorov product over independent
          steps.
          (Site B)

  ROOT 4: Group-action / group-Fourier techniques (arc-transitivity,
          Bloch decomposition, matrix multiplication).
          (Sites D, E, G)

  CASCADE TOPOLOGY:
    Root 1 + Root 2 jointly establish the framework's algebraic
    substrate as fully associative.
    Root 3 propagates associativity to the measure level.
    Root 4 propagates associativity to all operator-level analyses.

  SINGLE STRUCTURAL CHOICE: at A1 + Local CAR + A3-T, the framework
  assumes substrate composition is associative. Once made, this choice
  is propagated by every downstream theorem via standard tools (group
  theory, matrix algebra, Kolmogorov product, Fourier transform).

  THE NON-ASSOCIATIVE EXTENSION REQUIRED:
    Replacing the associative assumption at the source means rebuilding
    the entire downstream chain with non-associative analogs:
    - Free magma (with involutivity) instead of F_inv(E)
    - Non-associative algebra at vertex (octonions are the natural
      candidate per Site H)
    - Non-Kolmogorov measure on tree-bracketed paths
    - Loop / quasigroup automorphism instead of group automorphism
    - No clean Bloch decomposition (or need non-associative analog)

  THIS IS WHY OPTION 2 (FREE-MAGMA WALKER) IS MULTI-SESSION.
  It's not just one walker change — it's a chain of substitutions
  through the entire closed NA chain.
""")


# ============================================================================
# Octonions as the natural non-associative substitution
# ============================================================================
print("=" * 78)
print("The natural fix at Site H: octonions")
print("=" * 78)
print()
print("""  Octonions 𝕆 are a 8-dim non-associative normed division algebra.
  Their Clifford-like properties:

    {e_i, e_j} = -2 δ_ij   for i, j = 1..7     (same as Cl(0,7))
    [e_i, e_j, e_k] ≠ 0    in general          (NEW: associator)

  The associator is totally antisymmetric and lives in a 7-dim space
  (since octonions are 8-dim and the 1-dim real part associates with
  everything). The associator structure constants are encoded in the
  Fano plane / G_2 invariant 3-form.

  CRUCIAL OBSERVATION:
    Cl(0,7) and 𝕆 SHARE the 2-letter anti-commutation structure.
    Any 2-letter test (CAR, anti-commutation, basic Clifford
    relations) gives the same answer for both. The DIFFERENCE only
    appears at 3+ letter composites.

    Framework's Local CAR theorem derives 2-letter relations. At
    that level, Cl(2k) and the corresponding-dim octonionic-like
    algebra are INDISTINGUISHABLE.

    The framework's CHOICE of Cl(2k) (associative) over 𝕆 (non-
    associative) is made AT THE LEVEL of "minimum closed associative
    algebra they generate" — i.e., the SMALLEST associative algebra
    is selected. But MDL-uniqueness of associative-vs-non-associative
    is never tested.

  COMPRESSIBILITY ACCOUNTING (from earlier audit):
    Cl(6,0): 64-dim, Spin(6) = 15-dim Lie group
    𝕆: 8-dim, G_2 = 14-dim Lie group of automorphisms
    Both have ~similar description-length (algebra dim + group dim).

    MDL doesn't uniquely select Cl over 𝕆. Under A2-T plural retention,
    BOTH should be retained — Cl associative compression AND
    octonionic non-associative compression. The framework currently
    only runs the Cl side.

  CASCADE LIST (for Phase 2 / free-magma walker):
    Sites that need replacement under non-associative extension:
    - Site H: Cl(2k) → octonionic-like algebra
    - Site A: F_inv(E) group → free magma with involutivity
    - Site C: same as Site A
    - Site F: free monoid → free magma
    - Site B: Kolmogorov product → tree-bracketed measure
    - Site D: B^L matrix product → bracketing-aware substrate operator
    - Site E: arc-transitive group → arc-transitive loop/magma
    - Site G: Bloch decomposition → non-associative Fourier analog
""")


# ============================================================================
# Phase 0 verdict
# ============================================================================
print("=" * 78)
print("Phase 0 verdict + recommendations")
print("=" * 78)
print()
print("""  PHASE 0 FINDINGS:

  ✓ 8 distinct associativity smuggle sites identified in closed NA
    chain + upstream multiway / Hilbert / gauge machinery.
  ✓ Smuggles flow from 4 ROOT ASSUMPTIONS, not 8 independent ones.
  ✓ Single deepest source: at A1 + Local CAR + A3-T, framework treats
    compositions as forming an associative group.
  ✓ Octonions 𝕆 are the natural non-associative substitution at Site H
    — they share 2-letter anti-commutation with Cl but differ at
    associator level (3+ letter products).
  ✓ Framework's MDL-uniqueness comparison Cl-vs-𝕆 was never run; A2-T
    plural retention should retain BOTH if neither dominates.

  REVISION TO NA-4 SHARPENING:

  Original NA-4 sharpening claimed associator [a,b,c] is the form of
  Layer-1 escape. Phase 0 strengthens this:
  - The associator IS specifically the 3-letter content of substrate
    composition that the observer's 2-letter (anti-)commutation
    apparatus cannot detect.
  - Octonions are the structurally-natural carrier (8-dim, G_2 autom,
    Fano plane structure constants).
  - Tits-Freudenthal magic-square then gives F_4, E_6, E_7, E_8 from
    octonions × {ℝ, ℂ, ℍ, 𝕆} — exactly the user's E(8) intuition,
    recovered from substrate Layer-1 if octonionic.

  RECOMMENDATIONS FOR NEXT WORK:

  ✓ Phase 0 COMPLETE. Map of smuggle sites and root assumptions in hand.

  RECOMMENDED NEXT (per prior discussion):
  - Test (iii) Spec(B) residue inspection (2-4 sessions): reframe
    cosmology Item 5 + Λ_CC Path B + n_s as Layer-1 escape evidence.
    Phase 0 tightens the test: each blocked observable should be
    checked for whether the structural blockage is associativity-
    compatible (i.e., would the associator add the missing content?).

  DEFERRED (multi-session research-level):
  - Phase 2 / Option 2 — free-magma walker (5-10 sessions): rebuild
    the closed NA chain with non-associative substitutions at the
    8 sites. Phase 0's mapping makes this tractable but still
    multi-sprint.

  - Octonionic Cl-replacement (3-5 sessions): replace Cl(2k) with
    octonionic algebra at Site H specifically, test whether 2-letter
    CAR predictions are preserved while 3-letter composites get
    associator content. Most-bounded structural test.

  IMMEDIATE PIVOT:
    Test (iii) Spec(B) inspection. Phase 0 has sharpened the test
    hypothesis substantially.

  V_PHASE_0_COMPLETE = TRUE
  V_SMUGGLE_SITES_MAPPED = 8 (A-H)
  V_ROOT_ASSUMPTIONS = 4
  V_DEEPEST_SOURCE = "A1 + Local CAR + A3-T treat compositions as forming an associative group"
  V_NATURAL_FIX_AT_SITE_H = "octonions (share 2-letter CAR, differ at 3-letter associator)"
  V_NEXT_BOUNDED_TEST = "Spec(B) residue inspection (2-4 sessions)"
  V_DEFERRED_RESEARCH = "free-magma walker (Option 2, 5-10 sessions)"
""")


print("=" * 78)
print("PHASE 0 ASSOCIATIVITY-SMUGGLE AUDIT COMPLETE")
print("=" * 78)
