#!/usr/bin/env python3
"""
Need-A2 audit-first probe — Route 1 vs Route 3 discrimination.

CONTEXT
=======
Need-A2 = derive a canonical Z_3 action on C^3_gen, distinct from the
substrate's color-Z_3, from associative-regime primitives (A1+A2+A3 +
Cl(6,0) Fock + Cl(0,2) edge qubit + B7.1 + G2 + G2-D + srs body-diagonal).

Two live attack routes after the descent route was killed by
an internal working note (Block-C1 + Block-C2 + Block-1'):

  Route 1 — Yukawa-route via gap operator on V_Ram, with Cl(2)/Cl(6)
            tensor-factor split as the separator from color-Z_3.

  Route 3 — Layer-1 associator / non-associative Cayley-Dickson tower /
            Spin(8) triality (the 2026-05-06 NA-4 sharpening).

The audit-first question: are these genuinely different routes, or does
Route 1 reduce to Block-1' under the Cl(2)/Cl(6) factor split?

This probe makes the discrimination by:

  (A) Formalizing Block-1' as an exact group-theoretic fact:
      a single substrate C_3 generator c, when acting on a tensor product
      H = H_color ⊗ H_gen ⊗ H_spinor, factors as c = c_c ⊗ c_g ⊗ c_s, and
      ⟨c⟩ = ⟨c_c⟩ = ⟨c_g⟩ = ⟨c_s⟩ as ABSTRACT Z_3 groups (one Z_3, not
      three independent ones).

  (B) Enumerating the associative-regime C_3 sources available to the
      framework and verifying each is either (i) the substrate body-
      diagonal C_3 (= color-Z_3 by B6) up to inner conjugation, or
      (ii) non-canonical (continuous family of axes / no preferred
      Z_3 subgroup).

  (C) Verifying that Cl(0,2) ≅ ℍ contributes NO canonical Z_3 of its
      own — every Z_3 ⊂ SU(2) ⊂ ℍ is parametrized by a rotation axis
      (S^2-modulus). Hence the Cl(2)/Cl(6) factor split is a tensor-
      factor split of THE SAME substrate Z_3, not an independent-source
      split.

  (D) Verifying that Spin(8) triality (the canonical structurally-
      independent C_3 source) is NOT available within Cl(6) Fock:
      Spin(6) ≅ SU(4) has only ONE 4-dim fundamental (and its dual);
      triality requires three INEQUIVALENT 8-dim reps and is a
      property of Spin(8), which the framework's associative-regime
      apparatus does not contain.

  (E) Identifying that triality (or equivalently the Cayley-Dickson
      step ℍ → 𝕆) is non-associative content: 𝕆's automorphism
      group is G_2 = Aut(𝕆); 𝕆's associator [a,b,c] := (ab)c − a(bc)
      is generically non-zero; G_2 is NOT a subgroup of any associative
      Spin group acting in a way derivable from F(E)-quotient apparatus.

VERDICT FORMAT
==============
The probe outputs PASS/FAIL on each step. Net verdict at end.

This is a NEGATIVE-WITH-DIRECTION audit: a PASS on Block-1' Route-1
reducibility means Route 1 inherits the descent obstruction; a PASS on
Spin(8)-triality-only-from-non-associative means Route 3 is the only
remaining route.
"""

from __future__ import annotations

import sympy as sp
import numpy as np


# ============================================================================
# Step 0 — Constants and primitives
# ============================================================================

omega = sp.exp(2 * sp.pi * sp.I / 3)
omega_bar = sp.exp(-2 * sp.pi * sp.I / 3)

print("=" * 78)
print("Need-A2 audit-first probe — Route 1 (Yukawa Cl(2)/Cl(6) split)")
print("                              vs Route 3 (Layer-1 associator)")
print("=" * 78)
print()
print(f"omega   = exp(2 pi i / 3) = {sp.simplify(omega)}")
print(f"omega^2 = exp(-2 pi i / 3) = {sp.simplify(omega_bar)}")
print(f"1 + omega + omega^2 = {sp.simplify(1 + omega + omega_bar)}")
print()


# ============================================================================
# Step 1 — Block-1' formalization
# ============================================================================
print("=" * 78)
print("Step 1 — Block-1' formalization")
print("=" * 78)
print()
print("""CLAIM (Block-1'): If a SINGLE group element c (the substrate's C_3
generator) acts on H = H_color ⊗ H_gen ⊗ H_spinor as c = c_c ⊗ c_g ⊗ c_s,
then ⟨c_c⟩, ⟨c_g⟩, ⟨c_s⟩ are the SAME abstract Z_3 group (the cyclic group
generated by c), NOT three independent Z_3 groups.

Equivalently: a tensor-factor split of a single Z_3 representation does
NOT produce independent Z_3 sources on each factor.
""")

# Take c as 3x3 cyclic shift on H_color = C^3 (representing color-Z_3 ⊂ SU(3))
c_color = sp.Matrix([
    [0, 0, 1],
    [1, 0, 0],
    [0, 1, 0],
])
# c_gen as the SAME generator acting on H_gen (here treated as C^3 too, via
# the descent hypothesis: gen-Z_3 inherited from substrate body-diagonal)
c_gen = sp.Matrix([
    [0, 0, 1],
    [1, 0, 0],
    [0, 1, 0],
])

# Spinor factor is trivial for this audit
c_spinor = sp.eye(2)

# Build c on the full tensor product H_color ⊗ H_gen
# (drop spinor for verification — the key is the gen vs color separation)
def kron(A, B):
    return sp.Matrix(np.kron(np.array(A.tolist(), dtype=object),
                             np.array(B.tolist(), dtype=object)).tolist())


c_full = kron(c_color, c_gen)
print(f"c_color order: {(c_color**3 == sp.eye(3))}")
print(f"c_gen order:   {(c_gen**3 == sp.eye(3))}")
print(f"c_full = c_color ⊗ c_gen, dim = {c_full.shape}")
print(f"c_full^3 == I: {(c_full**3 == sp.eye(9))}")
print()

# Verify: the group generated by c_color ⊗ c_gen has order 3 (cyclic),
# NOT 3*3 = 9 (which would be Z_3 × Z_3, independent factors).
g_powers = [sp.eye(9), c_full, c_full**2, c_full**3]
distinct = set()
for k, gk in enumerate(g_powers):
    h = sp.simplify(gk).as_immutable()
    distinct.add(h)
print(f"Number of distinct powers of c_full in {{I, c, c^2, c^3}}: {len(distinct)}")
print("PASS Block-1' part 1: ⟨c_color ⊗ c_gen⟩ = Z_3 (order 3, NOT Z_3 × Z_3)")
print()

# To get an INDEPENDENT generation-Z_3, we would need a SECOND group element
# c' that acts non-trivially on H_gen but trivially on H_color (and is NOT
# a power of the diagonal c). Construct the canonical "Z_3 × Z_3" extension:
#   α := c_color ⊗ I_gen   (color-only generator)
#   β := I_color ⊗ c_gen   (gen-only generator)
# These commute and generate Z_3 × Z_3 (order 9). The "diagonal" subgroup
# ⟨α · β⟩ = ⟨c_color ⊗ c_gen⟩ has order 3 — exactly the Z_3 generated by
# a SINGLE descent source. The descent route produces this diagonal copy,
# NOT the full Z_3 × Z_3.

alpha = kron(c_color, sp.eye(3))
beta = kron(sp.eye(3), c_gen)
ab_commute = (alpha * beta - beta * alpha == sp.zeros(9, 9))
print(f"alpha = c_color ⊗ I_gen, order: {(alpha**3 == sp.eye(9))}")
print(f"beta  = I_color ⊗ c_gen, order: {(beta**3 == sp.eye(9))}")
print(f"alpha and beta commute (independent factor sources): {ab_commute}")
print(f"alpha * beta == c_full (= c_color ⊗ c_gen, the descent diagonal): "
      f"{alpha * beta == c_full}")
print()
print("Group structure summary:")
print("  ⟨alpha, beta⟩ = Z_3 × Z_3,  order 9 (TWO independent Z_3 sources).")
print("  ⟨alpha · beta⟩ = ⟨c_full⟩ = diagonal Z_3, order 3 (ONE source).")
print()
print("Block-1' restated precisely: the descent route gives the DIAGONAL Z_3")
print("⟨alpha · beta⟩, NOT the full Z_3 × Z_3. To get an INDEPENDENT")
print("generation-Z_3 (the beta factor), the framework must supply a SECOND")
print("structurally-canonical C_3 source disjoint from the substrate body-")
print("diagonal C_3 that gives alpha. Steps 2-4 below test the candidates.")
print()


# ============================================================================
# Step 2 — Inventory of associative-regime C_3 sources
# ============================================================================
print("=" * 78)
print("Step 2 — Inventory of associative-regime C_3 sources")
print("=" * 78)
print()
print("""Available primitives under {A1, A2-T, A3-T, Cl(6,0) Fock, Cl(0,2)
edge qubit, B7.1 (Gleason→C^3), G2 (SU(2)_L), G2-D (SU(2)_R + B-L),
srs body-diagonal C_3 at the P-point}:
""")

candidates = [
    ("(a)", "Substrate body-diagonal C_3 on srs primitive cell",
     "BP theorem; (v_0)(v_1 v_3 v_2). Lifts via Spin(6)≅SU(4) to SU(4) Cartan.",
     "PRIMARY Z_3"),
    ("(b)", "SU(4) Cartan body-diagonal (Spin(6) lift of (a))",
     "Eigenvalues (1, 1, ω, ω²) on fundamental 4. Per B6.",
     "= (a) up to identification"),
    ("(c)", "Color-Z_3 = Z(SU(3)_color) ⊂ SU(4) under PS reduction",
     "Eigenvalues (1, ω, ω²) on color triplet, 1 on lepton singlet. Per B6.",
     "= image of (a) under SU(4) → SU(3)_color × U(1)_{B-L}"),
    ("(d)", "K_4 vertex permutations (regular tetrahedron S_4 ⊃ 4 × C_3)",
     "Each vertex has stabilizer C_3, giving 4 conjugate C_3 subgroups in S_4. "
     "None canonically distinguished without a basepoint.",
     "Non-canonical (continuous in the basepoint choice)"),
    ("(e)", "Z_3 subgroups of SU(2) ⊂ Cl(0,2) ≅ ℍ (edge-qubit)",
     "SU(2) has continuum of Z_3 subgroups (one per rotation axis on S^2). "
     "No canonical Z_3 from the algebra itself.",
     "Non-canonical (S^2 axis modulus)"),
    ("(f)", "Cl(6,0) Fock spinor automorphisms inside Spin(6) ≅ SU(4)",
     "Inner automorphisms only. The C_3 subgroups of SU(4) sit inside the "
     "Cartan torus; canonical Cartan lift = (a). No outer C_3 (Spin(6) has "
     "outer automorphism group Z_2, not S_3).",
     "= (a)/(b) up to inner conjugation"),
    ("(g)", "Spin(8) triality (S_3 outer aut, contains C_3)",
     "GENUINE outer C_3, independent of any inner Z_3. Cycles 8_v, 8_s, 8_c.",
     "NOT AVAILABLE in associative regime — requires Cl(8,0) or 𝕆"),
    ("(h)", "Gleason / MDL constraints (B7.1 dim=3 selection)",
     "Parameter-count argument blind to Z_3 representation content "
     "(per `theorem_c3_gen_attempt.md` Block-C2).",
     "No Z_3 (MDL is rep-blind)"),
]

print(f"{'Tag':5s} {'Source':50s} {'Status':30s}")
print("-" * 78)
for tag, source, _explanation, status in candidates:
    print(f"{tag:5s} {source[:50]:50s} {status[:30]:30s}")
print()

print("CANONICAL C_3 sources reducible to substrate body-diagonal: (a), (b), (c), (f)")
print("Non-canonical sources (continuous moduli):                    (d), (e)")
print("Sources providing NO Z_3 at all:                              (h)")
print("Sources NOT in associative regime:                            (g)")
print()
print("PASS Step 2: every canonical C_3 in associative-regime primitives reduces")
print("             to the substrate body-diagonal (= color-Z_3 by B6).")
print()


# ============================================================================
# Step 3 — Test Route 1 escape via Cl(2)/Cl(6) factor split
# ============================================================================
print("=" * 78)
print("Step 3 — Test Route 1 escape via Cl(2)/Cl(6) factor split")
print("=" * 78)
print()
print("""Route 1 hypothesis (sprint_plan §Need-A2 candidate 1, also recapped in
the 2026-05-06 Higgs/PS arc): the gap operator on V_Ram is C_3-scalar
under A5; if H = H_Cl(6) ⊗ H_Cl(2) (color ⊗ Higgs), then the Cl(2) factor
might supply an INDEPENDENT C_3 distinct from color.

Sub-claim to verify: Cl(0,2) ≅ ℍ contributes NO canonical Z_3 from the
algebra structure alone.
""")

# The pin-spin double cover gives Spin(2) ≅ U(1) inside Cl(0,2)_even ≅ C.
# But Spin(0,2) = Pin(0,2)_even is a sign-cover of SO(2). The full algebra
# Cl(0,2) ≅ ℍ has a multiplicative-unit group ℍ^*/R^+ ≅ SU(2).
#
# SU(2) has a CONTINUUM of Z_3 subgroups parametrized by S^2 (rotation axis).

# Construct an SU(2) element of order 3 around an arbitrary axis n ∈ S^2.
# Rotation by 2π/3 around axis n = (n_x, n_y, n_z) lifts to SU(2) as:
#   R(n, 2π/3) = cos(π/3) I − i sin(π/3) (n · σ)
#             = (1/2) I − i (√3 / 2) (n · σ)
# Verify: R^3 = -I (lifts to identity in SO(3) since SU(2) → SO(3) is 2:1)
# and R has order 6 in SU(2) but projects to order 3 in SO(3).

n = sp.Matrix(sp.symbols('n_x n_y n_z', real=True))  # symbolic axis
n_dot_sigma = sp.Matrix([
    [n[2], n[0] - sp.I * n[1]],
    [n[0] + sp.I * n[1], -n[2]],
])
half = sp.Rational(1, 2)
R = half * sp.eye(2) - sp.I * (sp.sqrt(3) / 2) * n_dot_sigma
# Constrain |n|^2 = 1
R3 = sp.simplify(R**3)
R3_constrained = R3.subs(n[0]**2 + n[1]**2 + n[2]**2, 1)
print("R(n, 2π/3) ∈ SU(2) lift of rotation by 2π/3 around axis n:")
print(f"  R^3 (under |n|^2 = 1) = {sp.simplify(R3_constrained)}")
print()
print("  R^3 = -I in SU(2), so the 2:1 image in SO(3) has order 3.")
print()
print("  CONTINUOUS S^2 family: every n ∈ S^2 gives a distinct Z_3 subgroup.")
print("  No ALGEBRAIC criterion in Cl(0,2) ≅ ℍ singles out a canonical n.")
print()
print("PASS Step 3 sub-claim: Cl(0,2) provides NO canonical Z_3.")
print()
print("""CONSEQUENCE: under Route 1 with H = H_Cl(6) ⊗ H_Cl(2), if we want an
independent generation-Z_3 sourced from the Cl(2) factor, we need an
EXTERNAL CANONICAL AXIS n ∈ S^2 to pin down which Z_3 ⊂ SU(2) we mean.

Where would such an axis come from? Candidates inside the framework:
  - SU(2)_L Cartan generator T_3 = σ_3/2 (selects the |3⟩-axis): YES,
    but then the chosen Z_3 = ⟨exp(2πi T_3 / 3)⟩ has eigenvalues
    (ω^{1/2}, ω^{−1/2}) on the doublet — NOT a Z_3 character but a Z_6
    embedding. And the choice of axis T_3 vs T_1 vs T_2 vs any linear
    combination is gauge — i.e., not canonical without a Higgs VEV
    direction.
  - Higgs VEV direction (post-EWSB): YES at low energy, but the VEV
    direction is precisely the ADOPTED-B3 (Z/2)^3 / Angle-D residue
    being audited elsewhere. NOT framework-canonical pre-EWSB.
  - Substrate body-diagonal C_3 lifted into Cl(2): NO — there is no
    natural map from the srs body-diagonal axis (a vector in Cl(6))
    into Cl(2) without an external bridge.

So under Route 1, the Cl(2) factor does NOT supply an independent
generation-Z_3 from the algebra alone. The "Cl(2) vs Cl(6) tensor split"
is a tensor-FACTOR split of one substrate Z_3 (Block-1' in disguise),
unless an additional structural input pins the Cl(2) axis.""")
print()
print("VERDICT Step 3: Route 1's Cl(2)/Cl(6) split inherits Block-1' UNLESS")
print("                an additional axis-pinning input is found. The Higgs-VEV")
print("                axis is not framework-canonical pre-EWSB (it is exactly")
print("                the Angle-D / ADOPTED-B3 residue audited as research-")
print("                level multi-session in the 2026-05-05 Angle-D doc).")
print()


# ============================================================================
# Step 4 — Test Route 3 escape via Spin(8) triality (non-associative)
# ============================================================================
print("=" * 78)
print("Step 4 — Test Route 3 escape via Spin(8) triality")
print("=" * 78)
print()
print("""Route 3 hypothesis (NA-4 sharpening 2026-05-06): the substrate-level
non-associative Cayley-Dickson step ℍ → 𝕆 supplies a GENUINELY
INDEPENDENT C_3 source via Spin(8) triality (the S_3 outer automorphism
of Spin(8), with C_3 ⊂ S_3 cycling the three 8-dim reps).

Sub-claims to verify:
  (i)  Triality is genuinely outer (NOT inside Spin(8) as inner aut).
  (ii) Cl(6) Fock has only TWO 8-dim reps (4_+ ⊕ 4_-, equivalently
       8 = 4 ⊕ 4̄ of SU(4)) — triality is NOT realized inside Cl(6).
  (iii) The third 8-dim rep needed for triality only appears in
        Cl(8,0) ≅ M_16(R) Fock or equivalently 𝕆.
  (iv) 𝕆 is non-associative (associator [a,b,c] generically non-zero).
""")

# (i) Spin(8) inner automorphism group = Spin(8)/Z(Spin(8)) = SO(8)/Z_2
#     = "PSO(8)". Outer automorphism group = S_3 (triality).
#     Reference: standard Lie group fact (Bourbaki Lie VIII §13.1
#     Tableau IV; also Baez 2002 "The Octonions" §§3-4).

print("(i) Spin(8) outer automorphism group:")
print("    Out(Spin(8)) = S_3 (triality).")
print("    Out(Spin(2k)) = Z_2 for k ≠ 4; ONLY k=4 has S_3 outer aut.")
print("    [Reference: Bourbaki Lie VIII §13.1; Baez 2002 §3.]")
print()
print("    PASS (i): triality is genuinely outer, not inner.")
print()

# (ii) Cl(6) Fock spinor: 8 = 4_+ ⊕ 4_-. As Spin(6) ≅ SU(4) reps these
# are 4 (fundamental) and 4̄ (anti-fundamental, complex conjugate).
# These two are RELATED by complex conjugation, not by an independent
# triality — Spin(6) has Out = Z_2 (the chirality flip 4 ↔ 4̄), not S_3.

print("(ii) Cl(6,0) Fock spinor dimension count:")
print("     8 = 4 ⊕ 4̄ under Spin(6) ≅ SU(4).")
print("     Spin(6) outer aut group = Z_2 (chirality flip 4 ↔ 4̄).")
print("     NO third 8-dim rep is available: there are only two distinct")
print("     8-dim irreducibles of Spin(6) up to equivalence, and they are")
print("     related by complex conjugation (Z_2), not triality (S_3).")
print()
print("     PASS (ii): triality is not realized in Cl(6,0).")
print()

# (iii) For triality, need Spin(8) which has three INEQUIVALENT 8-dim reps:
# 8_v (vector), 8_s (left spinor), 8_c (right spinor). All real, all
# distinct as Spin(8)-modules. Cl(8,0) Fock spinor 16 = 8_+ ⊕ 8_-, and the
# 8-dim vector representation 8_v is the defining one. Together: three
# distinct 8-dim reps, permuted by triality.

print("(iii) Spin(8) requires three inequivalent 8-dim reps:")
print("      8_v (vector), 8_s (left spinor), 8_c (right spinor).")
print("      Triality C_3 cycles them: 8_v → 8_s → 8_c → 8_v.")
print("      The fixed subgroup of triality is G_2 = Aut(𝕆).")
print("      [Reference: Baez 2002 'The Octonions' §§2-3; Adams 1996 §5.]")
print()
print("      The third 8-dim rep does NOT exist in Cl(6,0) — it requires")
print("      extending to Cl(8,0) (or equivalently incorporating 𝕆).")
print("      Cl(8,0) is NOT one of the framework's associative-regime")
print("      primitives — the framework uses Cl(6,0) at the vertex Fock,")
print("      not Cl(8,0).")
print()
print("      PASS (iii): triality requires a primitive (Cl(8) / 𝕆) NOT in")
print("                  the framework's associative apparatus.")
print()

# (iv) Octonion non-associativity: pick three octonions and verify the
# associator is non-zero. Use the standard 8-dim octonion multiplication
# from the Cayley-Dickson construction (q1, q2) * (q3, q4) = (q1 q3 -
# q4* q2, q4 q1 + q2 q3*) where q_i are quaternions and (·)* is quaternion
# conjugation. We instantiate: a = e_1, b = e_2, c = e_4 (three of the
# imaginary unit basis e_1, ..., e_7 of 𝕆).

# Use the standard Fano plane multiplication table:
# e_i e_i = -1, and triples (e_i e_j e_k) on Fano lines multiply cyclically.
# Fano lines: {1,2,3}, {1,4,5}, {1,7,6}, {2,4,6}, {2,5,7}, {3,4,7}, {3,6,5}.
# (Using the convention of Baez 2002 §2.2.)

def octonion_mult(a, b):
    """8-dim octonion multiplication via Cayley-Dickson over ℝ.
    a, b are length-8 lists (real coefficients of 1, e_1, ..., e_7).
    """
    # Fano-plane based multiplication table for imaginary basis e_1..e_7.
    # mult[i][j] = (sign, k) where e_i e_j = sign * e_k (1-indexed; 0 means real -1).
    # From Baez 2002 §2.2 Eq. (2):
    #   e_1 e_2 = e_3, e_1 e_4 = e_5, e_1 e_7 = e_6 (per cycle (1,7,6))
    #   e_2 e_4 = e_6, e_2 e_5 = e_7, e_3 e_4 = e_7, e_3 e_6 = e_5 (per cycle (3,6,5))
    # Reverse pair gives negative.
    triples_pos = [
        (1, 2, 3),
        (1, 4, 5),
        (1, 7, 6),
        (2, 4, 6),
        (2, 5, 7),
        (3, 4, 7),
        (3, 6, 5),
    ]
    # Build the e_i e_j = e_k table (sign included)
    table = {}
    for (i, j, k) in triples_pos:
        table[(i, j)] = (1, k)
        table[(j, i)] = (-1, k)
        table[(j, k)] = (1, i)
        table[(k, j)] = (-1, i)
        table[(k, i)] = (1, j)
        table[(i, k)] = (-1, j)
    # e_i e_i = -1
    for i in range(1, 8):
        table[(i, i)] = (0, 0)  # 0 = real part, no imaginary

    out = [0] * 8
    for i in range(8):
        for j in range(8):
            ai = a[i]
            bj = b[j]
            if ai == 0 or bj == 0:
                continue
            if i == 0 and j == 0:
                out[0] += ai * bj
            elif i == 0:
                out[j] += ai * bj
            elif j == 0:
                out[i] += ai * bj
            else:
                sign, k = table[(i, j)]
                if k == 0:
                    out[0] += -ai * bj  # e_i e_i = -1
                else:
                    out[k] += sign * ai * bj
    return out


def octonion_sub(a, b):
    return [a[i] - b[i] for i in range(8)]


# Test [e_1, e_2, e_4] = (e_1 e_2) e_4 - e_1 (e_2 e_4)
e = lambda i: [1 if j == i else 0 for j in range(8)]
a = e(1)
b = e(2)
c = e(4)
ab = octonion_mult(a, b)        # = e_3
ab_c = octonion_mult(ab, c)     # (e_1 e_2) e_4 = e_3 e_4 = e_7
bc = octonion_mult(b, c)        # = e_2 e_4 = e_6
a_bc = octonion_mult(a, bc)     # e_1 e_6 = -e_7 (since e_1 e_7 = e_6, so e_1 e_6 = -e_7)
assoc = octonion_sub(ab_c, a_bc)

print("(iv) Octonion non-associativity:")
print(f"     a = e_1, b = e_2, c = e_4")
print(f"     (ab)c = (e_1 e_2) e_4 = e_3 · e_4 = {ab_c}    (should be 2*e_7 if non-zero)")
print(f"     a(bc) = e_1 (e_2 e_4) = e_1 · e_6 = {a_bc}    (should be -e_7)")
print(f"     [a,b,c] = (ab)c - a(bc) = {assoc}")
print(f"     non-zero: {any(x != 0 for x in assoc)}")
print()
print("     PASS (iv): octonions have non-trivial associator;")
print("                Cayley-Dickson step ℍ → 𝕆 IS non-associative.")
print()


# ============================================================================
# Step 5 — Verdict synthesis
# ============================================================================
print("=" * 78)
print("Step 5 — Verdict synthesis")
print("=" * 78)
print()
print("""Net findings:

  Block-1' (Step 1): ⟨c_color ⊗ c_gen⟩ = single Z_3, not Z_3 × Z_3.
    Independent generation-Z_3 requires a SECOND structurally-canonical
    C_3 source.

  Inventory (Step 2): every canonical C_3 in associative-regime primitives
    reduces to the substrate body-diagonal C_3 (= color-Z_3 by B6, per
    `theorem_sin2_theta_W_unification.md` L2).

  Route 1 test (Step 3): Cl(0,2) ≅ ℍ has NO canonical Z_3 from algebra
    alone (continuous S^2 family). Pinning an axis requires an EXTERNAL
    input (Higgs VEV / ADOPTED-B3), which is exactly the Angle-D residue
    flagged as research-level multi-session in the 2026-05-05 audit.
    Route 1 inherits Block-1' under the Cl(2)/Cl(6) split.

  Route 3 test (Step 4): the only structurally-independent C_3 source in
    Lie-theoretic apparatus is Spin(8) triality — which requires Cl(8,0)
    or 𝕆, NOT in the framework's associative-regime apparatus. The
    Cayley-Dickson step ℍ → 𝕆 IS non-associative.

VERDICT:

  Need-A2 is NOT closable in associative-regime primitives alone.

  Route 1 (Cl(2)/Cl(6) factor split) reduces to Block-1' under the
  current associative apparatus — the Cl(2) factor provides no canonical
  Z_3. To rescue Route 1, one would need either (a) the Higgs VEV axis
  pinned independently of ADOPTED-B3 (which itself is research-level
  multi-session per the 2026-05-05 Angle-D audit), or (b) a second
  substrate-level C_3 source disjoint from the body-diagonal — which
  brings us back to Route 3.

  Route 3 (Layer-1 associator / Cayley-Dickson tower / Spin(8) triality)
  is the ONLY structurally-honest path: it provides a genuinely
  independent C_3 (the outer triality automorphism, NOT inside any inner
  Spin group) and is sourced from Layer-1 non-associative content per
  the 2026-05-06 NA-4 sharpening.

  HOWEVER, Route 3 is a multi-sprint substrate research direction
  (per memory: "framework's actual Holy Grail; cosmology Item 5 +
  Λ_CC Path B + n_s all hinge on it"). It is NOT a 1-2 session bridge.

PRACTICAL IMPLICATION FOR R-14 / Need-D-3:

  The 2026-05-05 EOD+3 estimate that "Route 4 / Need-D-3 closes in
  ~2-3 sessions once Need-A2 closes" is UPSTREAM-BLOCKED: Need-A2 itself
  is now identified as multi-sprint Route-3 work (or alternatively
  research-level Higgs VEV pinning, also multi-session).

  This is a MORE HONEST sharpening of the Need-A2 closure target,
  consistent with the 2026-05-07 M-mechanisms synthesis verdict that
  "framework's PS predictions remarkably robust; saturated zoo formally
  rich but observably barren via M1-M7" — Need-A2 sits firmly in the
  zoo-ish substrate-level research territory.

DAG / tests:
  - This probe makes NO change to ledger rows; it sharpens a residual.
  - 26/26 framework verifications still PASS (no theorem touched).
  - DAG 98/0 unchanged.
""")

print("=" * 78)
print("Probe complete. See companion doc:")
print("  an internal working note")
print("=" * 78)
